using System.Collections.Generic;

// 번역표: 한국어 → { 한국어(고쳐 쓸 때만), 영어, 일본어, 중국어 }
public static class LocTable
{
    static string[] E(string ko, string en, string ja, string zh) => new[] { ko, en, ja, zh };
    static string[] L(string en, string ja, string zh) => new[] { "", en, ja, zh };

    public static readonly Dictionary<string, string[]> Entries = new Dictionary<string, string[]>
    {
        // ================================================================= 메뉴 · 설정 · 튜토리얼
        { "게임 시작", L("Start Game", "ゲーム開始", "开始游戏") },
        { "게임 종료", L("Quit Game", "ゲーム終了", "退出游戏") },
        { "튜토리얼", L("Tutorial", "チュートリアル", "教程") },
        { "설정", L("Settings", "設定", "设置") },
        { "언어", L("Language", "言語", "语言") },
        { "볼륨", L("Volume", "音量", "音量") },
        { "일반", L("General", "一般", "常规") },
        { "화면", L("Display", "画面", "显示") },
        { "조작", L("Controls", "操作", "操作") },
        { "전체 볼륨", L("Master Volume", "全体音量", "总音量") },
        { "음악", L("Music", "音楽", "音乐") },
        { "효과음", L("Sound Effects", "効果音", "音效") },
        { "화면 모드", L("Display Mode", "画面モード", "显示模式") },
        { "전체 화면", L("Fullscreen", "フルスクリーン", "全屏") },
        { "창 모드", L("Windowed", "ウィンドウ", "窗口") },
        { "해상도", L("Resolution", "解像度", "分辨率") },
        { "수직 동기화", L("VSync", "垂直同期", "垂直同步") },
        { "화면 흔들림", L("Screen Shake", "画面の揺れ", "屏幕震动") },
        { "번쩍임 효과", L("Flash Effects", "フラッシュ効果", "闪光效果") },
        { "켜짐", L("On", "オン", "开") },
        { "꺼짐", L("Off", "オフ", "关") },
        { "위로 이동", L("Move Up", "上に移動", "向上移动") },
        { "아래로 이동", L("Move Down", "下に移動", "向下移动") },
        { "왼쪽 이동", L("Move Left", "左に移動", "向左移动") },
        { "오른쪽 이동", L("Move Right", "右に移動", "向右移动") },
        { "무기 교체", L("Swap Weapon", "武器切替", "切换武器") },
        { "스킬 1", L("Skill 1", "スキル1", "技能1") },
        { "스킬 2", L("Skill 2", "スキル2", "技能2") },
        { "스킬 3", L("Skill 3", "スキル3", "技能3") },
        { "상호작용 (상점 · 확정)", L("Interact (Shop · Confirm)", "決定・ショップ", "互动（商店 · 确认）") },
        { "특수 강화", L("Special Upgrade", "特殊強化", "特殊强化") },
        { "키를 누르세요", L("Press a key", "キーを押す", "请按键") },
        { "버튼을 누른 뒤 바꿀 키를 누르세요 (ESC: 취소)", L("Click a button, then press the new key (ESC: cancel)", "ボタンを押してから新しいキーを押してください（ESC：キャンセル）", "点击按钮后按下新按键（ESC：取消）") },
        { "기본값으로", L("Reset to Default", "初期設定に戻す", "恢复默认") },
        { "거너", L("Gunner", "ガンナー", "枪手") },
        { "검사", L("Swordsman", "剣士", "剑士") },
        { "도적", L("Rogue", "盗賊", "盗贼") },
        { "궁수", L("Archer", "弓使い", "弓箭手") },
        { "연금술사", L("Alchemist", "錬金術師", "炼金术士") },
        { "마지막 총잡이", L("The Last Gunslinger", "最後のガンマン", "最后的枪手") },
        { "떠돌이 기사", L("Wandering Knight", "さすらいの騎士", "流浪骑士") },
        { "그림자 칼날", L("Shadow Blade", "影の刃", "暗影之刃") },
        { "숲의 사냥꾼", L("Hunter of the Woods", "森の狩人", "森林猎手") },
        { "미친 학자", L("Mad Scholar", "狂った学者", "疯狂学者") },
        { "준비 중", L("Coming Soon", "準備中", "敬请期待") },
        { "리볼버와 여러 특수 총기를 다루는 총잡이. 모든 캐릭터의 기준.", L("A gunslinger who handles a revolver and many special guns. The baseline for every character.", "リボルバーと様々な特殊銃を扱うガンマン。全キャラクターの基準。", "使用左轮手枪和各种特殊枪械的枪手。所有角色的基准。") },
        { "무겁고 느리지만 한 번에 여럿을 베는 장검의 달인.", L("A longsword master—heavy and slow, but cuts through many at once.", "重く遅いが、一度に多くを斬り伏せる長剣の達人。", "沉重缓慢，却能一次斩倒众敌的长剑大师。") },
        { "적을 꿰뚫는 화살과 하늘을 덮는 화살비의 명사수.", L("A marksman of piercing arrows and sky-darkening arrow rain.", "敵を貫く矢と空を覆う矢の雨の名手。", "擅长穿透之箭与遮天箭雨的神射手。") },
        { "터지는 플라스크로 적 무리를 한꺼번에 녹이는 괴짜 학자.", L("An eccentric scholar who melts whole crowds with exploding flasks.", "爆発するフラスコで敵の群れをまとめて溶かす変わり者の学者。", "用爆炸烧瓶一口气融化敌群的怪胎学者。") },
        { "아직 준비 중인 캐릭터입니다.", L("This character is still in development.", "まだ準備中のキャラクターです。", "该角色仍在制作中。") },
        { "리볼버", L("Revolver", "リボルバー", "左轮手枪") },
        { "장검", L("Longsword", "長剣", "长剑") },
        { "표창", L("Throwing Star", "手裏剣", "飞镖") },
        { "사냥 활", L("Hunting Bow", "狩猟弓", "猎弓") },
        { "플라스크", L("Flask", "フラスコ", "烧瓶") },
        { "마우스 방향으로 총알 발사", L("Fires bullets toward the cursor", "マウスの方向に弾を発射", "朝鼠标方向射击") },
        { "끝없이 날아가는 표창", L("Throwing stars that fly forever", "どこまでも飛ぶ手裏剣", "无限飞行的飞镖") },
        { "적을 하나 더 꿰뚫는 화살", L("Arrows that pierce one extra enemy", "敵をもう一体貫く矢", "多穿透一个敌人的箭") },
        { "던진 자리에서 터지는 플라스크 (범위 피해)", L("Flasks that burst where they land (area damage)", "投げた場所で弾けるフラスコ（範囲ダメージ）", "落地即爆的烧瓶（范围伤害）") },
        { "타겟팅 필살기", L("Targeting Ultimate", "ターゲティング必殺技", "锁定必杀技") },
        { "회전 베기", L("Spin Slash", "回転斬り", "回旋斩") },
        { "은신", L("Stealth", "隠密", "隐身") },
        { "화살비", L("Arrow Rain", "矢の雨", "箭雨") },
        { "대폭발 플라스크", L("Great Blast Flask", "大爆発フラスコ", "大爆炸烧瓶") },
        { "누르고 있으면 시간이 느려지며 적을 조준, 떼면 조준한 적 모두에게 사격", L("Hold to slow time and mark enemies; release to fire at every marked target", "押し続けると時間が遅くなり敵を照準、離すと照準した敵全員を撃つ", "按住时时间变慢并瞄准敌人，松开后向所有目标射击") },
        { "검을 사방으로 휘둘러 주변을 벱니다. 오래 누를수록 피해가 커집니다", L("Swings your sword in every direction. The longer you hold, the more damage", "剣を四方に振るい周囲を斬ります。長く押すほどダメージ増加", "向四周挥剑斩击，按得越久伤害越高") },
        { "누르고 있는 동안 화살비를 떨어뜨릴 위치를 조정하고, 떼면 쏟아붓습니다", L("Hold to aim where the arrow rain falls, release to unleash it", "押している間に矢の雨の位置を調整し、離すと降り注ぎます", "按住时调整箭雨落点，松开后倾泻而下") },
        { "누를수록 커지는 플라스크를 던져 크게 폭발하고 산성 웅덩이를 남깁니다", L("Throws a flask that grows as you hold, exploding hugely and leaving an acid pool", "押すほど大きくなるフラスコを投げて大爆発し、酸の水たまりを残します", "按住时烧瓶越来越大，投出后大爆炸并留下酸液池") },
        { "캐릭터", L("Characters", "キャラクター", "角色") },
        { "보유 포인트: ", L("Points: ", "所持ポイント: ", "持有点数：") },
        { "선택됨", L("Selected", "選択中", "已选择") },
        { "잠김", L("Locked", "ロック", "未解锁") },
        { "잠긴 캐릭터", L("Locked Character", "ロック中のキャラクター", "未解锁角色") },
        { "취소", L("Cancel", "キャンセル", "取消") },
        { "선택", L("Select", "選択", "选择") },
        { "구매", L("Buy", "購入", "购买") },
        { "포인트로 잠금을 풀면 이 캐릭터의 모습과 능력을 볼 수 있습니다.", L("Unlock with points to see this character and their abilities.", "ポイントで解放すると、このキャラクターの姿と能力が見られます。", "用点数解锁后即可查看该角色的外观和能力。") },
        { "포인트가 부족합니다. 게임에서 적을 처치하면 포인트가 쌓입니다.", L("Not enough points. Defeat enemies in-game to earn points.", "ポイントが足りません。ゲームで敵を倒すとポイントが貯まります。", "点数不足。在游戏中击败敌人即可累积点数。") },
        { "약 ", L("about ", "約", "约") },
        { "칸", L(" tiles", "マス", "格") },
        { "기본 무기", L("Weapon", "基本武器", "基础武器") },
        { "획득 포인트 ", L("Points earned ", "獲得ポイント ", "获得点数 ") },
        { "보유 ", L("Total ", "所持 ", "持有 ") },
        { "대상 없음", L("No target", "対象なし", "没有目标") },
        { "쉬움", L("Easy", "イージー", "简单") },
        { "보통", L("Normal", "ノーマル", "普通") },
        { "어려움", L("Hard", "ハード", "困难") },
        { "무한", L("Endless", "エンドレス", "无尽") },
        { "보통 · 어려움", L("Normal · Hard", "ノーマル · ハード", "普通 · 困难") },
        { "쉬움을 클리어하면 보통 · 어려움이 열립니다", L("Clear Easy to unlock Normal · Hard", "イージーをクリアするとノーマル · ハードが解放されます", "通关简单难度后解锁普通 · 困难") },
        { "어려움을 클리어하면 무한 모드가 열립니다", L("Clear Hard to unlock Endless mode", "ハードをクリアするとエンドレスモードが解放されます", "通关困难难度后解锁无尽模式") },
        { "Space 대사 넘기기 · ESC 건너뛰기", L("Space Next line · ESC Skip", "Space セリフ送り · ESC スキップ", "Space 下一句 · ESC 跳过") },
        { "건너뛰기", L("Skip", "スキップ", "跳过") },
        { "클리어!", L("Clear!", "クリア！", "通关！") },
        { "새 난이도 해금: ", L("New difficulty unlocked: ", "新しい難易度解放: ", "解锁新难度：") },
        { "플레이해 주셔서 고맙습니다!", L("Thank you for playing!", "遊んでくれてありがとう！", "感谢游玩！") },
        { "리치 왕이 지하 묘역을 깨우자, 죽은 자들이 땅 위로 기어 나왔다.", L("When the Lich King woke the catacombs, the dead crawled up to the surface.", "リッチ王が地下墓所を目覚めさせると、死者たちが地上へ這い出してきた。", "巫妖王唤醒了地下墓穴，亡者纷纷爬上了地面。") },
        { "마을에 남은 마지막 총잡이는 무너진 신전의 구멍으로 몸을 던졌다.", L("The last gunslinger left in town leapt into the hole of the ruined temple.", "町に残った最後のガンマンは、崩れた神殿の穴へ身を投げた。", "镇上最后一名枪手，纵身跳进了倒塌神殿的洞口。") },
        { "리치 왕을 쓰러뜨리면 그 너머 지옥의 문도 열릴 것이다.", L("Defeat the Lich King, and the gate to Hell beyond will open.", "リッチ王を倒せば、その先の地獄の門も開くだろう。", "击败巫妖王，彼方的地狱之门也将开启。") },
        { "탄창은 가득하다. 이제 세상을 구할 차례다.", L("The magazine is full. Time to save the world.", "弾倉は満タンだ。世界を救う番だ。", "弹匣已满。该去拯救世界了。") },
        { "지옥 너머, 모든 괴물이 모여드는 불타는 사막.", L("Beyond Hell lies a burning desert where every monster gathers.", "地獄の先、あらゆる怪物が集まる燃える砂漠。", "地狱彼方，是群魔聚集的燃烧沙漠。") },
        { "쓰러뜨린 왕들이 몇 번이고 다시 일어선다.", L("The fallen kings rise again, and again.", "倒した王たちが何度でも立ち上がる。", "被击倒的王者们一次又一次地站起。") },
        { "끝은 없다. 얼마나 버틸 수 있을까?", L("There is no end. How long can you last?", "終わりはない。どこまで耐えられるか？", "没有尽头。你能坚持多久？") },
        { "킹 슬라임이 녹아내리자, 초원에 오랜만에 바람이 불었다.", L("As the King Slime melted away, the wind finally blew across the meadow again.", "キングスライムが溶け落ちると、草原に久しぶりの風が吹いた。", "史莱姆王融化殆尽，草原上久违地吹起了风。") },
        { "리치 왕의 저주도, 지옥 군주의 불길도 모두 꺼졌다.", L("The Lich King's curse and the Demon Lord's flames were gone.", "リッチ王の呪いも、地獄の君主の炎も、すべて消えた。", "巫妖王的诅咒与地狱领主的烈焰，都已熄灭。") },
        { "총잡이는 마지막 탄피를 주워 모자 띠에 꽂았다.", L("The gunslinger picked up the last shell casing and tucked it into his hatband.", "ガンマンは最後の薬莢を拾い、帽子のバンドに差した。", "枪手捡起最后一枚弹壳，插在了帽带上。") },
        { "살아남은 사람들은 그를 이렇게 불렀다.", L("The survivors gave him a name.", "生き残った人々は、彼をこう呼んだ。", "幸存的人们这样称呼他。") },
        { "총으로 세상을 구한 자 — Gun Saver.", L("The one who saved the world with a gun — Gun Saver.", "銃で世界を救った者 — Gun Saver。", "用枪拯救世界之人 — Gun Saver。") },
        { "하지만 지평선 너머, 붉게 타오르는 사막에서 무언가 꿈틀거리고 있었다...", L("But beyond the horizon, something stirred in a desert burning red...", "だが地平線の彼方、赤く燃える砂漠で何かが蠢いていた……", "然而在地平线彼方，赤红燃烧的沙漠中，有什么正在蠢动……") },
        { "무한 모드", L("Endless", "エンドレス", "无尽模式") },
        { "보스 처치 ", L("Bosses ", "ボス撃破 ", "击败首领 ") },
        { "최고 ", L("Best ", "最高 ", "最佳 ") },
        { "사막의 모래 폭풍 속에서 보스가 나타났다!", L("A boss emerges from the desert sandstorm!", "砂漠の砂嵐の中からボスが現れた！", "首领从沙漠风暴中现身！") },
        { "보스 처치!  특수 능력 포인트 +1", L("Boss defeated!  Special point +1", "ボス撃破！  特殊能力ポイント+1", "击败首领！  特殊能力点数+1") },
        { "무한 모드 · 불타는 사막", L("Endless · Burning Desert", "エンドレス · 燃える砂漠", "无尽模式 · 燃烧沙漠") },
        { "얼마나 버틸 수 있을까?", L("How long can you last?", "どこまで耐えられるか？", "你能坚持多久？") },
        { "생존 시간 ", L("Survived ", "生存時間 ", "生存时间 ") },
        { "최고 기록 ", L("Best ", "最高記録 ", "最佳纪录 ") },
        { "닫기", L("Close", "閉じる", "关闭") },
        { "이전", L("Prev", "前へ", "上一页") },
        { "다음", L("Next", "次へ", "下一页") },
        { "시작하기", L("Let's Go", "始める", "开始") },
        { "지하 묘역에서 살아남아라", L("Survive the Catacombs", "地下墓所を生き延びろ", "在地下墓穴中活下去") },
        { "나의 첫 유니티 게임", L("My First Unity Game", "初めてのUnityゲーム", "我的第一款Unity游戏") },
        { "다시 시작", L("Restart", "リスタート", "重新开始") },
        { "메인 메뉴로", L("Main Menu", "メインメニューへ", "返回主菜单") },
        { "다시 하기", L("Try Again", "もう一度", "再来一次") },
        { "사망하셨습니다...", L("You Died...", "あなたは死んだ…", "你死了……") },
        { "일시정지", L("Paused", "一時停止", "暂停") },
        { "[ESC] 계속하기", L("[ESC] Resume", "[ESC] 再開", "[ESC] 继续") },
        { "[P] 상점    [ESC] 메뉴", E("[ESC] 메뉴 · 설정", "[ESC] Menu · Settings", "[ESC] メニュー・設定", "[ESC] 菜单 · 设置") },
        { "[P] 또는 [ESC] 로 닫기", E("[ESC] 로 닫기", "[ESC] to close", "[ESC] で閉じる", "按 [ESC] 关闭") },
        { "일시정지 1초", L("Paused 1s", "一時停止 1秒", "暂停 1秒") },
        { "일시정지 ", L("Paused ", "一時停止 ", "暂停 ") },
        { "레벨 업!", L("Level Up!", "レベルアップ！", "升级！") },
        { "좀 쎈 보스", L("A Tough Boss", "ちょっと強いボス", "有点强的首领") },
        { "능력을 하나 선택하세요", L("Choose an ability", "能力を一つ選んでください", "请选择一项能力") },
        { "카드를 눌러 선택", L("Click a card to choose", "カードを押して選択", "点击卡牌选择") },
        { "상점", L("Shop", "ショップ", "商店") },
        { "코인 : 0", L("Coins : 0", "コイン : 0", "金币 : 0") },
        { "신전 문이 열렸다!", L("The temple gate is open!", "神殿の扉が開いた！", "神殿之门开启了！") },
        { "지옥의 문", L("Gate of Hell", "地獄の門", "地狱之门") },
        { "포인트 3개로 세 갈래에서 특수 능력 3개를 고르세요", L("Spend 3 points to pick 3 special abilities from the three branches", "3ポイントで3系統から特殊能力を3つ選んでください", "用3点在三个分支中选择3项特殊能力") },
        { "현재 / 최대", L("Now / Max", "現在 / 最大", "当前 / 最大") },

        // ================================================================= 툴팁
        { "타겟팅 스킬", L("Targeting Skill", "ターゲティングスキル", "锁定技能") },
        { "게이지가 가득 차면 우클릭을 누르고 있는 동안 시간이 느려지며 주변 적을 차례로 조준합니다.\n버튼을 떼면 조준한 모든 적에게 일제 사격!\n\n일반 사격으로 적을 맞히면 게이지가 찹니다.",
          E("게이지가 가득 차면 우클릭으로 필살기를 씁니다. 들고 있는 무기마다 조준 화면과 필살기가 다릅니다.\n\n게이지는 시간이 지나면 차고, 적을 처치하면 잠깐 더 빨리 찹니다.",
            "When the gauge is full, right-click to use your ultimate. Each weapon has its own aiming screen and ultimate.\n\nThe gauge fills over time, and faster for a moment after each kill.",
            "ゲージが満タンになったら右クリックで必殺技。武器ごとに照準画面と必殺技が違います。\n\nゲージは時間で溜まり、敵を倒すと少しの間速く溜まります。",
            "能量满时右键释放必杀技。每种武器的瞄准画面和必杀技都不同。\n\n能量随时间积累，击杀敌人后短时间内积累更快。") },

        // ================================================================= 특수 능력 (이름 · 설명)
        { "지옥불 산탄총", L("Hellfire Shotgun", "獄炎ショットガン", "狱火霰弹枪") },
        { "영혼 저격총", L("Soul Sniper", "ソウルスナイパー", "灵魂狙击枪") },
        { "저주받은 쌍권총", L("Cursed Twin Pistols", "呪われた二丁拳銃", "被诅咒的双枪") },
        { "화염 방사기", L("Flamethrower", "火炎放射器", "火焰喷射器") },
        { "영혼 인도 지팡이", L("Soulguide Staff", "魂導きの杖", "引魂法杖") },
        { "번개 사슬총", L("Chain Lightning Gun", "連鎖雷撃銃", "连锁闪电枪") },
        { "부메랑 낫", L("Boomerang Scythe", "ブーメラン鎌", "回旋镰刀") },
        { "용암 유탄 발사기", L("Lava Grenade Launcher", "溶岩グレネードランチャー", "熔岩榴弹发射器") },
        { "그림자 대시", L("Shadow Dash", "シャドウダッシュ", "暗影冲刺") },
        { "시간 왜곡", L("Time Warp", "時間歪曲", "时间扭曲") },
        { "희생의 계약", L("Blood Pact", "犠牲の契約", "牺牲契约") },
        { "영혼 폭발", L("Soul Burst", "ソウルバースト", "灵魂爆发") },
        { "해골 소환", L("Summon Skeletons", "スケルトン召喚", "召唤骷髅") },
        { "거울 분신", L("Mirror Image", "鏡の分身", "镜像分身") },
        { "피의 갈고리", L("Blood Hook", "血のフック", "鲜血钩索") },
        { "수호 영혼", L("Guardian Souls", "守護の魂", "守护之魂") },
        { "복수의 가시", L("Thorns of Vengeance", "復讐の棘", "复仇之刺") },
        { "탄창 저주", L("Cursed Magazine", "弾倉の呪い", "弹匣诅咒") },
        { "불사의 맹세", L("Oath of Undying", "不死の誓い", "不死誓约") },
        { "총알 대신 앞쪽 부채꼴(6칸) 안의 적 모두에게\n즉시 250% 피해와 강한 넉백. 발사 간격 1.4배.", L("Instead of bullets, hits every enemy in a cone ahead (6 tiles)\nfor 250% damage with strong knockback. Fire interval x1.4.", "弾の代わりに前方の扇形(6マス)内の敵全員に\n即座に250%ダメージと強いノックバック。発射間隔1.4倍。", "不发射子弹，直接对前方扇形(6格)内所有敌人\n造成250%伤害并强力击退。射击间隔1.4倍。") },
        { "누르고 있다가 떼면 발사합니다. 모든 적을 관통하고\n충전 정도에 따라 피해 60%~320%.", L("Hold and release to fire. Pierces every enemy;\n60%-320% damage depending on charge.", "押し続けて離すと発射。全ての敵を貫通し\nチャージに応じて60%〜320%ダメージ。", "按住后松开发射。穿透所有敌人，\n根据蓄力造成60%~320%伤害。") },
        { "누르고 있으면 연사합니다. 발사 간격 절반, 발당 피해 55%.\n두 발에 탄 1개만 씁니다.", L("Hold for rapid fire. Half the fire interval, 55% damage per shot.\nOnly 1 ammo per 2 shots.", "押し続けると連射。発射間隔半分、1発55%ダメージ。\n2発で弾1つしか使いません。", "按住连射。射击间隔减半，每发55%伤害。\n每2发只消耗1颗子弹。") },
        { "누르고 있으면 불을 뿜어 적을 관통하고 불태웁니다.\n탄약 대신 과열 게이지를 씁니다.", L("Hold to spew fire that pierces and burns enemies.\nUses an overheat gauge instead of ammo.", "押し続けると火を噴き、敵を貫通して燃やします。\n弾薬の代わりに過熱ゲージを使います。", "按住喷火，穿透并点燃敌人。\n使用过热槽代替弹药。") },
        { "가장 가까운 적을 쫓아가는 유도탄을 쏩니다.\n발당 피해 70%, 조준이 필요 없습니다.", L("Fires homing shots that chase the nearest enemy.\n70% damage per shot, no aiming needed.", "最も近い敵を追う誘導弾を撃ちます。\n1発70%ダメージ、照準不要。", "发射追踪最近敌人的导弹。\n每发70%伤害，无需瞄准。") },
        { "맞은 적에게서 최대 4마리에게 번개가 튑니다.\n튈 때마다 피해가 20%씩 줄어듭니다.", L("Lightning jumps from the target to up to 4 enemies.\nEach jump deals 20% less damage.", "命中した敵から最大4体に雷が飛びます。\n飛ぶたびにダメージが20%ずつ減ります。", "闪电从命中的敌人弹射到最多4个敌人。\n每次弹射伤害降低20%。") },
        { "날아갔다 돌아오며 오가는 길의 적을 모두 벱니다.\n피해 150%, 한 번에 하나만 던질 수 있습니다.", L("Flies out and back, cutting every enemy on the way.\n150% damage, only one at a time.", "飛んで戻ってくる間に道中の敵を全て斬ります。\n150%ダメージ、一度に1つだけ投げられます。", "飞出再飞回，斩击沿途所有敌人。\n150%伤害，一次只能投掷一把。") },
        { "마우스 위치에 떨어져 폭발(피해 200%)하고\n잠깐 용암 웅덩이를 남깁니다. 탄 2개 사용.", L("Lands at the cursor and explodes (200% damage),\nleaving a brief lava pool. Uses 2 ammo.", "マウス位置に落ちて爆発(200%ダメージ)し\n一時的に溶岩溜まりを残します。弾2つ使用。", "落在鼠标位置爆炸(200%伤害)，\n并短暂留下熔岩池。消耗2发弹药。") },
        { "마우스 방향으로 짧게 돌진합니다.\n돌진 중에는 무적. 쿨타임 3초.", L("Dash a short distance toward the cursor.\nInvincible while dashing. Cooldown 3s.", "マウス方向に短く突進します。\n突進中は無敵。クールタイム3秒。", "向鼠标方向短距离冲刺。\n冲刺时无敌。冷却3秒。") },
        { "마우스 위치에 4초 동안 불 장판을 깝니다.\n0.5초마다 공격력 75% 피해. 쿨타임 12초.", L("Creates a fire field at the cursor for 4s.\n75% damage every 0.5s. Cooldown 12s.", "マウス位置に4秒間炎のフィールドを敷きます。\n0.5秒ごとに攻撃力75%ダメージ。クールタイム12秒。", "在鼠标位置生成持续4秒的火焰领域。\n每0.5秒造成75%伤害。冷却12秒。") },
        { "5초 동안 모든 적이 50% 느려집니다.\n플레이어는 정상 속도. 쿨타임 20초.", L("All enemies are 50% slower for 5s.\nYou move at normal speed. Cooldown 20s.", "5秒間、全ての敵が50%遅くなります。\nプレイヤーは通常速度。クールタイム20秒。", "5秒内所有敌人减速50%。\n玩家速度不变。冷却20秒。") },
        { "최대 체력 20%를 바쳐 8초 동안\n공격력 2배, 연사 1.5배. 쿨타임 25초.", L("Sacrifice 20% max HP for 8s of\ndouble damage and x1.5 fire rate. Cooldown 25s.", "最大体力の20%を捧げ8秒間\n攻撃力2倍、連射1.5倍。クールタイム25秒。", "献祭20%最大生命，8秒内\n攻击力2倍、射速1.5倍。冷却25秒。") },
        { "적을 처치하면 영혼이 쌓입니다(최대 40).\n5개 이상일 때 모두 터뜨려 주변에 피해. 쿨타임 5초.", L("Kills store souls (max 40).\nWith 5+, detonate them all to damage nearby enemies. Cooldown 5s.", "敵を倒すと魂が溜まります(最大40)。\n5つ以上で全て炸裂させ周囲にダメージ。クールタイム5秒。", "击杀敌人积累灵魂(最多40)。\n达到5个以上时全部引爆伤害周围。冷却5秒。") },
        { "아군 해골 3기를 10초 동안 부릅니다.\n적에게 달려가 자폭(공격력 300%). 쿨타임 15초.", L("Summons 3 allied skeletons for 10s.\nThey run at enemies and explode (300%). Cooldown 15s.", "味方のスケルトン3体を10秒間呼び出します。\n敵に突っ込んで自爆(攻撃力300%)。クールタイム15秒。", "召唤3具友方骷髅，持续10秒。\n冲向敌人自爆(300%)。冷却15秒。") },
        { "제자리에 분신을 남기고 반투명해집니다.\n3초 동안 적이 분신을 쫓습니다. 쿨타임 12초.", L("Leave a decoy behind and turn translucent.\nEnemies chase the decoy for 3s. Cooldown 12s.", "その場に分身を残して半透明になります。\n3秒間、敵は分身を追います。クールタイム12秒。", "原地留下分身并变为半透明。\n敌人会追击分身3秒。冷却12秒。") },
        { "사슬을 던져 적을 끌어오거나(피해 150%)\n벽 쪽으로 날아갑니다. 쿨타임 4초.", L("Throw a chain to pull an enemy in (150%)\nor fly toward a wall. Cooldown 4s.", "鎖を投げて敵を引き寄せる(150%ダメージ)か\n壁の方へ飛びます。クールタイム4秒。", "投出锁链拉回敌人(150%伤害)\n或飞向墙壁。冷却4秒。") },
        { "영혼 구체 3개가 주위를 돌며\n닿은 적에게 공격력 80% 피해를 줍니다.", L("3 soul orbs circle you,\ndealing 80% damage to enemies they touch.", "魂の球3つが周囲を回り\n触れた敵に攻撃力80%のダメージを与えます。", "3颗灵魂球环绕你，\n对接触的敌人造成80%伤害。") },
        { "피격될 때마다 주변 적에게\n공격력 300% 피해를 주고 밀어냅니다.", L("Each time you are hit, nearby enemies\ntake 300% damage and are pushed away.", "被弾するたびに周囲の敵に\n攻撃力300%のダメージを与え押し返します。", "每次受击时对周围敌人\n造成300%伤害并击退。") },
        { "탄창의 마지막 한 발이 피해 3배가 되고\n맞은 곳에서 폭발합니다.", L("The last bullet in each magazine deals triple damage\nand explodes on impact.", "弾倉の最後の1発がダメージ3倍になり\n命中地点で爆発します。", "弹匣最后一发造成3倍伤害\n并在命中处爆炸。") },
        { "한 판에 한 번, 죽을 피해를 받으면\n체력 1로 버티고 3초 동안 무적이 됩니다.", L("Once per run, survive a lethal hit\nwith 1 HP and become invincible for 3s.", "1プレイに1回、致命ダメージを受けても\n体力1で耐え、3秒間無敵になります。", "每局一次，受到致命伤害时\n以1点生命存活并无敌3秒。") },

        // ================================================================= 보스 · 스테이지
        { "킹 슬라임이 둘로 갈라졌다!", L("The King Slime split in two!", "キングスライムが二つに分裂した！", "史莱姆王分裂成了两只！") },
        { "슬라임이 또 갈라진다!", L("The slimes split again!", "スライムがまた分裂する！", "史莱姆又分裂了！") },
        { "리치 왕이 망자의 의식을 시작한다!", L("The Lich King begins the Rite of the Dead!", "リッチ王が死者の儀式を始める！", "巫妖王开始了亡者仪式！") },
        { "지옥의 군주가 십자 불길을 내뿜는다!", L("The Demon Lord unleashes the Hellfire Cross!", "地獄の君主が十字の業火を放つ！", "地狱领主喷出十字烈焰！") },
        { "킹 슬라임이 미친 듯이 뛰어오른다!", L("The King Slime is leaping wildly!", "キングスライムが狂ったように跳ね回る！", "史莱姆王疯狂地跳跃！") },
        { "특수 강화 [", L("Special Upgrade [", "特殊強化 [", "特殊强化 [") },
        { "]   포인트 ", L("]   Points ", "]   ポイント ", "]   点数 ") },
        { "중간 보스 등장!\n쓰러뜨리면 특수 능력 포인트 +1", L("A mid-boss appears!\nDefeat it for +1 special point", "中ボス出現！\n倒すと特殊能力ポイント+1", "中头目出现！\n击败可获得特殊能力点数+1") },
        { "특수 능력 포인트 +1!\n[", L("Special point +1!\n[", "特殊能力ポイント+1！\n[", "特殊能力点数+1！\n[") },
        { "] 또는 아래 버튼으로 강화", L("] or the button below to upgrade", "] または下のボタンで強化", "] 或下方按钮进行强化") },
        { "신전 문이 열렸다!\n문으로 들어가세요", L("The temple gate is open!\nEnter the gate", "神殿の扉が開いた！\n扉に入ってください", "神殿之门开启了！\n请进入大门") },
        { "지옥의 군주를 쓰러뜨렸다!\n성문 너머로 초원이 보인다", L("The Demon Lord has fallen!\nA meadow lies beyond the gate", "地獄の君主を倒した！\n城門の向こうに草原が見える", "击败了地狱领主！\n城门外是一片草原") },
        { "킹 슬라임을 쓰러뜨렸다!\n모든 스테이지 클리어!", L("The King Slime has fallen!\nAll stages cleared!", "キングスライムを倒した！\n全ステージクリア！", "击败了史莱姆王！\n全部关卡通关！") },
        { "3장 · 초원\n특수 능력 포인트 +2", L("Chapter 3 · Meadow\nSpecial points +2", "第3章・草原\n特殊能力ポイント+2", "第3章 · 草原\n特殊能力点数+2") },
        { "2장 · 불타는 지옥", L("Chapter 2 · Burning Hell", "第2章・燃える地獄", "第2章 · 燃烧地狱") },
        { "지옥의 문이 당신을 끌어당긴다!  ", L("The gate is pulling you in!  ", "門があなたを引き寄せる！  ", "大门正在将你吸入！  ") },
        { "신전 문으로 들어가세요  ", L("Enter the gate  ", "門に入ってください  ", "请进入大门  ") },
        { "초", L("s", "秒", "秒") },
        { "떠돌이 상점이 나타났다!\n10초 안에 다가가 [{INTERACT}]", L("A wandering shop appeared!\nReach it within 10s and press [{INTERACT}]", "さすらいのショップが現れた！\n10秒以内に近づいて [{INTERACT}]", "流浪商店出现了！\n10秒内靠近并按 [{INTERACT}]") },
        { "상점 열기", L("Open Shop", "ショップを開く", "打开商店") },
        { "상점  ", L("Shop  ", "ショップ  ", "商店  ") },

        // ================================================================= 레벨업 능력
        { "관통하는 총알", L("Piercing Bullets", "貫通する弾", "穿透子弹") },
        { "총알의 관통력이 증가합니다 \n( 관통 ", L("Bullets pierce more enemies \n( Pierce ", "弾の貫通力が上がります \n( 貫通 ", "子弹穿透力提升 \n( 穿透 ") },
        { "코인충", L("Coin Hoarder", "コイン好き", "金币狂") },
        { "코인을 더 많이 획득합니다.\n( 코인 획득량 ", L("Gain more coins.\n( Coins per pickup ", "より多くのコインを獲得します。\n( コイン獲得量 ", "获得更多金币。\n( 金币获取量 ") },
        { "재활용 에너지", L("Recycled Energy", "リサイクルエネルギー", "能量回收") },
        { "스킬 게이지가 20% 감소합니다\n( 게이지 -20% )", L("The skill gauge fills 20% faster\n( Gauge -20% )", "スキルゲージが20%早く溜まります\n( ゲージ -20% )", "技能能量积累加快20%\n( 能量 -20% )") },
        { "노려보는 눈빛", L("Piercing Glare", "睨みつける眼光", "凝视之眼") },
        { "스킬을 사용하는 동안 타겟이 된 적이 더 느려집니다. \n( 속도 -20% )", L("Targeted enemies slow down more while aiming. \n( Speed -20% )", "スキル使用中、狙った敵がさらに遅くなります。 \n( 速度 -20% )", "瞄准期间被锁定的敌人更慢。 \n( 速度 -20% )") },
        { "더 많은 경험치", L("More Experience", "経験値アップ", "更多经验") },
        { "킬 경험치 +10%", L("Kill EXP +10%", "撃破経験値 +10%", "击杀经验 +10%") },
        { "코인 자석", L("Coin Magnet", "コインマグネット", "金币磁铁") },
        { "주변의 코인을 끌어옵니다.\n( 범위 ", L("Pulls in nearby coins.\n( Range ", "周囲のコインを引き寄せます。\n( 範囲 ", "吸引附近的金币。\n( 范围 ") },
        { "멀티 샷", L("Multi Shot", "マルチショット", "多重射击") },
        { "한 번에 쏘는 총알이 1발 늘어나지만, 한 발당 피해는 줄어듭니다.\n( ", L("Fire 1 more bullet per shot, but each deals less damage.\n( ", "一度に撃つ弾が1発増えますが、1発あたりのダメージは減ります。\n( ", "每次多射1发子弹，但每发伤害降低。\n( ") },
        { "발 ", L(" shots ", "発 ", "发 ") },
        { "밀어내기", L("Knockback", "押し返し", "击退") },
        { "총알이 적을 밀어내는 효과 +25%\n( 최대 ", L("Bullet knockback +25%\n( Max ", "弾のノックバック +25%\n( 最大 ", "子弹击退效果 +25%\n( 最多 ") },
        { "번 )", L(" times )", "回 )", "次 )") },
        { "강철같은 심장", L("Heart of Steel", "鋼の心臓", "钢铁之心") },
        { "체력을 즉시 모두 회복하며, 최대 체력이 12% 증가합니다.", L("Fully restores HP and increases max HP by 12%.", "体力を即座に全回復し、最大体力が12%増えます。", "立即回满生命，最大生命提高12%。") },
        { "단단한 신체", L("Tough Body", "頑丈な体", "坚韧体魄") },
        { "받는 피해를 12% 감소시킵니다.\n( 최대 ", L("Take 12% less damage.\n( Max ", "受けるダメージを12%減らします。\n( 最大 ", "受到的伤害降低12%。\n( 最多 ") },
        { "생명의 샘", L("Fountain of Life", "生命の泉", "生命之泉") },
        { "시간이 지나면 체력이 조금씩 회복됩니다.\n( 초당 ", L("Slowly regenerate HP over time.\n( Per second ", "時間とともに体力が少しずつ回復します。\n( 毎秒 ", "随时间缓慢恢复生命。\n( 每秒 ") },
        { "피의 굶주림", L("Bloodthirst", "血の飢え", "嗜血") },
        { "적을 처치할 때마다 체력을 회복합니다.\n( 처치당 ", L("Heal each time you kill an enemy.\n( Per kill ", "敵を倒すたびに体力を回復します。\n( 撃破ごと ", "每次击杀恢复生命。\n( 每次击杀 ") },
        { "[{INTERACT}] 확정 : ", L("[{INTERACT}] Confirm : ", "[{INTERACT}] 決定 : ", "[{INTERACT}] 确认 : ") },
        { "카드를 클릭해 고른 뒤 [{INTERACT}]로 확정", L("Click a card, then press [{INTERACT}] to confirm", "カードをクリックして [{INTERACT}] で決定", "点击卡牌后按 [{INTERACT}] 确认") },
        { "총알이 적을 뚫고 지나갑니다.", L("Bullets pass through enemies.", "弾が敵を貫通します。", "子弹会穿透敌人。") },
        { "관통: 적 ", L("Pierce: ", "貫通: 敵 ", "穿透: ") },
        { "마리", L(" enemies", "体", "个敌人") },
        { "코인을 주울 때 더 많이 얻습니다.", L("Get more from each coin you pick up.", "コインを拾うとより多く手に入ります。", "拾取金币时获得更多。") },
        { "코인 1개당 획득량: ", L("Per coin: ", "コイン1枚あたり: ", "每枚金币获得: ") },
        { "스킬 게이지가 더 빨리 가득 찹니다. (적을 처치하면 잠깐 더 빨라짐)", L("The skill gauge fills faster. (Even faster for a moment after kills)", "スキルゲージが早く溜まります。(敵を倒すと少しの間さらに速い)", "技能能量积累更快。(击杀后短时间更快)") },
        { "게이지가 가득 차는 시간: ", L("Time to fill: ", "満タンまでの時間: ", "充满时间: ") },
        { "스킬을 쓰는 동안 적이 더 느려집니다.", L("Enemies are slower while you aim.", "スキル使用中、敵がさらに遅くなります。", "使用技能时敌人更慢。") },
        { "스킬 중 시간 속도: ", L("Time speed while aiming: ", "スキル中の時間速度: ", "技能期间时间速度: ") },
        { "적을 처치할 때 얻는 경험치가 늘어납니다.", L("Gain more EXP from kills.", "敵を倒した時の経験値が増えます。", "击杀获得的经验增加。") },
        { "경험치 배율: ", L("EXP multiplier: ", "経験値倍率: ", "经验倍率: ") },
        { "주변의 코인을 끌어옵니다.", L("Pulls in nearby coins.", "周囲のコインを引き寄せます。", "吸引附近的金币。") },
        { "끌어오는 범위: ", L("Pull range: ", "引き寄せ範囲: ", "吸引范围: ") },
        { "한 번에 여러 발을 부채꼴로 발사합니다. 발사 수가 늘수록 한 발당 피해는 줄어듭니다.", L("Fire several bullets in a fan. More bullets means less damage each.", "一度に複数の弾を扇状に撃ちます。弾数が増えるほど1発のダメージは減ります。", "一次呈扇形发射多发子弹。子弹越多每发伤害越低。") },
        { "발사 수: ", L("Shots: ", "発射数: ", "发射数: ") },
        { "발 (최대 5발)\n현재 한 발당 피해: ", L(" (max 5)\nDamage per shot: ", "発 (最大5発)\n現在の1発あたりダメージ: ", "发 (最多5发)\n当前每发伤害: ") },
        { "총알이 적을 더 멀리 밀어냅니다.", L("Bullets push enemies farther.", "弾が敵をより遠くへ押し返します。", "子弹将敌人击退得更远。") },
        { "넉백: 기본의 ", L("Knockback: base x", "ノックバック: 基本の ", "击退: 基础的 ") },
        { "최대 체력이 늘어나고, 선택하는 순간 체력을 모두 회복합니다.", L("Raises max HP and fully heals you when chosen.", "最大体力が増え、選んだ瞬間に体力が全回復します。", "提高最大生命，选择时回满生命。") },
        { "최대 체력: ", L("Max HP: ", "最大体力: ", "最大生命: ") },
        { "적에게 받는 피해가 줄어듭니다.", L("Take less damage from enemies.", "敵から受けるダメージが減ります。", "受到敌人的伤害降低。") },
        { "받는 피해 감소: ", L("Damage reduction: ", "被ダメージ軽減: ", "减伤: ") },
        { "시간이 지나면 체력이 조금씩 회복됩니다.", L("Slowly regenerate HP over time.", "時間とともに体力が少しずつ回復します。", "随时间缓慢恢复生命。") },
        { "초당 회복: ", L("Regen per second: ", "毎秒回復: ", "每秒恢复: ") },
        { "적을 처치할 때마다 체력을 회복합니다.", L("Heal each time you kill an enemy.", "敵を倒すたびに体力を回復します。", "每次击杀恢复生命。") },
        { "처치당 회복: ", L("Heal per kill: ", "撃破ごとの回復: ", "每次击杀恢复: ") },
        { "\n\n<color=#F5D478>현재 ", L("\n\n<color=#F5D478>Now ", "\n\n<color=#F5D478>現在 ", "\n\n<color=#F5D478>当前 ") },

        // ================================================================= 상점
        { "최대", L("MAX", "最大", "已满") },
        { "구매\n", L("Buy\n", "購入\n", "购买\n") },
        { " 코인", L(" coins", " コイン", " 金币") },
        { "코인 : ", L("Coins : ", "コイン : ", "金币 : ") },
        { "총알 공격력\n", L("Bullet Damage\n", "弾の攻撃力\n", "子弹攻击力\n") },
        { "발, 발당 ", L(" shots, each ", "発、1発 ", "发，每发 ") },
        { "공격 속도\n초당 ", L("Fire Rate\n", "攻撃速度\n毎秒 ", "攻击速度\n每秒 ") },
        { "발 (최대)", L("/s (MAX)", "発 (最大)", "发 (已满)") },
        { "공격 속도 (초당)\n", L("Fire Rate (per sec)\n", "攻撃速度 (毎秒)\n", "攻击速度 (每秒)\n") },
        { "발", L("", "発", "发") },
        { "재장전 속도\n", L("Reload Time\n", "リロード速度\n", "换弹速度\n") },
        { "초 (최대)", L("s (MAX)", "秒 (最大)", "秒 (已满)") },
        { "초 -> ", L("s -> ", "秒 -> ", "秒 -> ") },
        { "최대 탄창\n", L("Magazine Size\n", "最大弾倉\n", "弹匣容量\n") },
        { "이동 속도\n", L("Move Speed\n", "移動速度\n", "移动速度\n") },
        { " (최대)", L(" (MAX)", " (最大)", " (已满)") },
        { "스킬 강화", L("Skill Upgrades", "スキル強化", "技能强化") },
        { "우클릭 필살기를 무기마다 따로 강화합니다 · 위력 +20% · 특성은 무기마다 다름", L("Upgrade each weapon's right-click ultimate · Power +20% · Traits differ per weapon", "右クリック必殺技を武器ごとに強化します・威力+20%・特性は武器ごとに異なる", "分别强化每种武器的右键必杀技 · 威力+20% · 特性因武器而异") },
        { "상점으로", L("Back to Shop", "ショップへ", "返回商店") },
        { "기본 권총", L("Basic Pistol", "基本拳銃", "基础手枪") },
        { "위력", L("Power", "威力", "威力") },
        { "<color=#a39aa8>최대</color>", L("<color=#a39aa8>MAX</color>", "<color=#a39aa8>最大</color>", "<color=#a39aa8>已满</color>") },
        { " 코인</color>", L(" coins</color>", " コイン</color>", " 金币</color>") },
        { "코인이 부족합니다 (", L("Not enough coins (", "コインが足りません (", "金币不足 (") },
        { "무기 강화", L("Weapon Upgrades", "武器強化", "武器强化") },
        { "무기마다 따로 강화됩니다 (권총 강화와 별개) · 피해 +15% · 연사 +10% · 탄창 +25% · 특성은 무기마다 다름", L("Each weapon is upgraded separately (not the pistol) · Damage +15% · Fire rate +10% · Magazine +25% · Traits differ", "武器ごとに個別に強化されます(拳銃とは別) · ダメージ+15% · 連射+10% · 弾倉+25% · 特性は武器ごと", "每种武器单独强化(与手枪无关) · 伤害+15% · 射速+10% · 弹匣+25% · 特性因武器而异") },
        { "피해", L("Damage", "ダメージ", "伤害") },
        { "연사", L("Fire Rate", "連射", "射速") },
        { "탄창", L("Magazine", "弾倉", "弹匣") },
        { "\n<color=#a39aa8>해당 없음</color>", L("\n<color=#a39aa8>N/A</color>", "\n<color=#a39aa8>対象外</color>", "\n<color=#a39aa8>不适用</color>") },

        // ================================================================= 필살기 · 강화 특성
        { "지옥불 포격", L("Hellfire Barrage", "獄炎砲撃", "狱火炮击") },
        { "관통 레일건", L("Piercing Railgun", "貫通レールガン", "穿透电磁炮") },
        { "총알 폭풍", L("Bullet Storm", "弾丸の嵐", "子弹风暴") },
        { "화염 회오리", L("Fire Tornado", "炎の竜巻", "火焰龙卷") },
        { "영혼 떼", L("Soul Swarm", "魂の群れ", "灵魂群") },
        { "뇌운", L("Thunderstorm", "雷雲", "雷云") },
        { "죽음의 춤", L("Dance of Death", "死の舞", "死亡之舞") },
        { "용암 융단폭격", L("Lava Carpet Bombing", "溶岩絨毯爆撃", "熔岩地毯轰炸") },
        { "일제 사격", L("Volley", "一斉射撃", "齐射") },
        { "타겟 수", L("Targets", "ターゲット数", "目标数") },
        { "영혼 구슬", L("Soul Orbs", "魂の球", "灵魂球") },
        { "포격 횟수", L("Blasts", "砲撃回数", "炮击次数") },
        { "광선 굵기", L("Beam Width", "光線の太さ", "光束宽度") },
        { "지속 시간", L("Duration", "持続時間", "持续时间") },
        { "회오리 지속", L("Tornado Time", "竜巻の持続", "龙卷持续") },
        { "뇌운 지속", L("Storm Time", "雷雲の持続", "雷云持续") },
        { "폭격 줄", L("Bomb Rows", "爆撃の列", "轰炸行数") },
        { "특성", L("Trait", "特性", "特性") },
        { "+2마리", L("+2", "+2体", "+2个") },
        { "+1개", L("+1", "+1個", "+1个") },
        { "+1회", L("+1", "+1回", "+1次") },
        { "+0.4초", L("+0.4s", "+0.4秒", "+0.4秒") },
        { "+1.5초", L("+1.5s", "+1.5秒", "+1.5秒") },
        { "+0.8초", L("+0.8s", "+0.8秒", "+0.8秒") },
        { "+2줄", L("+2 rows", "+2列", "+2行") },
        { "사거리", L("Range", "射程", "射程") },
        { "충전 속도", L("Charge Speed", "チャージ速度", "蓄力速度") },
        { "관통", L("Pierce", "貫通", "穿透") },
        { "냉각", L("Cooling", "冷却", "冷却") },
        { "연쇄", L("Chain", "連鎖", "连锁") },
        { "낫 크기", L("Blade Size", "鎌の大きさ", "镰刀大小") },
        { "폭발 범위", L("Blast Radius", "爆発範囲", "爆炸范围") },
        { "사거리 +1", L("Range +1", "射程 +1", "射程 +1") },
        { "충전 시간 -15%", L("Charge time -15%", "チャージ時間 -15%", "蓄力时间 -15%") },
        { "관통 +1", L("Pierce +1", "貫通 +1", "穿透 +1") },
        { "열 발생 -20%", L("Heat -20%", "発熱 -20%", "发热 -20%") },
        { "연쇄 +1", L("Chain +1", "連鎖 +1", "连锁 +1") },
        { "크기·거리 +15%", L("Size·Reach +15%", "大きさ・距離 +15%", "大小·距离 +15%") },
        { "범위 +0.6", L("Radius +0.6", "範囲 +0.6", "范围 +0.6") },

        // ================================================================= 진화
        { " 진화!", L(" evolved!", " 進化！", " 进化！") },
        { "사거리 +2, 부채꼴이 넓어지고 피해 320%. 맞은 적이 불탑니다.", L("Range +2, wider cone, 320% damage. Hit enemies burn.", "射程+2、扇形が広がりダメージ320%。命中した敵が燃えます。", "射程+2，扇形更宽，伤害320%。命中的敌人会燃烧。") },
        { "충전 시간 0.8초. 완충 사격이 맞은 곳에서 폭발합니다.", L("0.8s charge. Fully charged shots explode where they hit.", "チャージ0.8秒。フルチャージ射撃が命中地点で爆発します。", "蓄力0.8秒。满蓄力射击在命中处爆炸。") },
        { "두 총구에서 동시에 발사합니다 (탄약 소모는 그대로).", L("Fires from both barrels at once (same ammo use).", "両方の銃口から同時に発射します(弾薬消費はそのまま)。", "两把枪同时开火(弹药消耗不变)。") },
        { "열이 40% 덜 오르고 불길 화상 피해가 강해집니다.", L("40% less heat and stronger burn damage.", "熱が40%上がりにくくなり、炎の燃焼ダメージが強くなります。", "发热降低40%，燃烧伤害增强。") },
        { "한 번에 유도탄 2발을 쏩니다.", L("Fires 2 homing shots at once.", "一度に誘導弾を2発撃ちます。", "一次发射2发导弹。") },
        { "번개가 7번 튀고, 튈 때 피해가 덜 줄어듭니다.", L("Lightning jumps 7 times and loses less damage per jump.", "雷が7回飛び、飛ぶたびのダメージ減少が小さくなります。", "闪电弹射7次，每次弹射伤害衰减更少。") },
        { "낫이 더 커지고 더 멀리 날아가며 피해 220%.", L("Bigger scythe that flies farther, 220% damage.", "鎌が大きくなり遠くまで飛び、ダメージ220%。", "镰刀更大、飞得更远，伤害220%。") },
        { "폭발 후 작은 용암탄 3개로 흩어집니다.", L("Splits into 3 small lava bombs after exploding.", "爆発後、小さな溶岩弾3つに分かれます。", "爆炸后分裂成3颗小熔岩弹。") },
        { "쿨타임 1.8초. 도착 지점에서 충격파가 터집니다.", L("1.8s cooldown. A shockwave bursts where you land.", "クールタイム1.8秒。到着地点で衝撃波が炸裂します。", "冷却1.8秒。在落点爆发冲击波。") },
        { "장판이 더 넓고 6초 동안 지속됩니다. 쿨타임 9초.", L("Wider field that lasts 6s. 9s cooldown.", "フィールドが広くなり6秒間持続します。クールタイム9秒。", "领域更大，持续6秒。冷却9秒。") },
        { "적이 75% 느려지고 7초 동안 지속됩니다.", L("Enemies are 75% slower for 7s.", "敵が75%遅くなり7秒間持続します。", "敌人减速75%，持续7秒。") },
        { "체력을 잃지 않고 12초 동안 지속됩니다.", L("No HP cost and lasts 12s.", "体力を失わず12秒間持続します。", "不消耗生命，持续12秒。") },
        { "영혼 3개부터 쓸 수 있고 폭발 범위가 넓어집니다.", L("Usable from 3 souls with a larger blast.", "魂3つから使え、爆発範囲が広がります。", "3个灵魂即可使用，爆炸范围更大。") },
        { "해골 5마리를 부르고 쿨타임 10초.", L("Summons 5 skeletons, 10s cooldown.", "スケルトンを5体呼び、クールタイム10秒。", "召唤5具骷髅，冷却10秒。") },
        { "분신이 5초 동안 남고 사라질 때 폭발합니다.", L("The decoy lasts 5s and explodes when it fades.", "分身が5秒間残り、消える時に爆発します。", "分身持续5秒，消失时爆炸。") },
        { "쿨타임 2초, 갈고리 피해 300%.", L("2s cooldown, 300% hook damage.", "クールタイム2秒、フックダメージ300%。", "冷却2秒，钩索伤害300%。") },
        { "영혼이 5개로 늘고 피해가 강해집니다.", L("5 orbs with stronger damage.", "魂が5つに増え、ダメージが強くなります。", "灵魂增至5个，伤害增强。") },
        { "반격 범위와 피해가 크게 늘어납니다.", L("Much larger counterattack radius and damage.", "反撃範囲とダメージが大きく増えます。", "反击范围和伤害大幅提升。") },
        { "탄창의 마지막 두 발이 저주탄이 됩니다.", L("The last two bullets become cursed.", "弾倉の最後の2発が呪い弾になります。", "弹匣最后两发成为诅咒弹。") },
        { "두 번 부활하고, 부활할 때 체력 50%로 일어납니다.", L("Revive twice, getting up with 50% HP.", "2回復活し、復活時は体力50%で起き上がります。", "可复活两次，复活时恢复50%生命。") },

        // ================================================================= 특수 능력 상태 글자
        { "낫 준비", L("Scythe ready", "鎌 準備完了", "镰刀就绪") },
        { "낫 회수 중", L("Scythe returning", "鎌 回収中", "镰刀回收中") },
        { "완충!", L("Full charge!", "フルチャージ！", "蓄满！") },
        { "충전 ", L("Charge ", "チャージ ", "蓄力 ") },
        { "냉각 완료", L("Cooled down", "冷却完了", "冷却完成") },
        { "과열!", L("Overheated!", "オーバーヒート！", "过热！") },
        { "열기 ", L("Heat ", "熱 ", "热量 ") },
        { "시간 왜곡!", L("Time Warp!", "時間歪曲！", "时间扭曲！") },
        { "희생의 계약! 공격력 2배", L("Blood Pact! Double damage", "犠牲の契約！攻撃力2倍", "牺牲契约！攻击力2倍") },
        { "영혼 부족 ", L("Not enough souls ", "魂が足りない ", "灵魂不足 ") },
        { "해골 소환!", L("Skeletons!", "スケルトン召喚！", "召唤骷髅！") },
        { "저주탄 장전!", L("Cursed round loaded!", "呪い弾 装填！", "诅咒弹上膛！") },
        { "계약 종료", L("Pact ended", "契約終了", "契约结束") },
        { "가시 반격!", L("Thorns!", "棘の反撃！", "荆棘反击！") },
        { "불사의 맹세가 발동했다!", L("Oath of Undying activated!", "不死の誓いが発動した！", "不死誓约发动了！") },
        { "영혼 폭발 준비", L("Soul Burst ready", "ソウルバースト準備完了", "灵魂爆发就绪") },
        { "무기  [Q] 교체  [R] 장전", L("Weapons  [Q] Swap  [R] Reload", "武器  [Q] 切替  [R] リロード", "武器  [Q] 切换  [R] 换弹") },
        { "스킬", L("Skills", "スキル", "技能") },
        { "패시브", L("Passives", "パッシブ", "被动") },
        { "사용 중 · ", L("In hand · ", "使用中・", "使用中 · ") },
        { "과열", L("Overheated", "過熱", "过热") },
        { "준비", L("Ready", "準備完了", "就绪") },
        { "회수 중", L("Returning", "回収中", "回收中") },
        { "] 준비", L("] Ready", "] 準備完了", "] 就绪") },
        { " · 영혼 ", L(" · Souls ", "・魂 ", " · 灵魂 ") },
        { "부활 ", L("Revives ", "復活 ", "复活 ") },
        { "사용함", L("Used", "使用済み", "已使用") },
        { "장전 중", L("Reloading", "リロード中", "换弹中") },

        // ================================================================= 스킬 트리
        { "무기  [Q] 교체", L("Weapons  [Q] Swap", "武器  [Q] 切替", "武器  [Q] 切换") },
        { "패시브  항상 적용", L("Passives  Always on", "パッシブ  常時発動", "被动  始终生效") },
        { "스킬  [{SKILL1}] 사용", L("Skills  [{SKILL1}] Use", "スキル  [{SKILL1}] 使用", "技能  [{SKILL1}] 使用") },
        { "선택을 취소했습니다.", L("Selection cancelled.", "選択を取り消しました。", "已取消选择。") },
        { "이미 진화한 능력입니다.", L("Already evolved.", "すでに進化した能力です。", "该能力已进化。") },
        { "스킬 칸({SKILL1} · {SKILL2} · {SKILL3})이 가득 찼습니다. 가진 스킬을 진화시켜 보세요.", L("Skill slots ({SKILL1} · {SKILL2} · {SKILL3}) are full. Try evolving a skill you have.", "スキル枠({SKILL1}・{SKILL2}・{SKILL3})がいっぱいです。持っているスキルを進化させてみましょう。", "技能栏({SKILL1} · {SKILL2} · {SKILL3})已满。试试进化已有的技能。") },
        { "포인트를 모두 썼습니다. 다른 능력을 먼저 취소하세요.", L("No points left. Cancel another ability first.", "ポイントを使い切りました。先に他の能力を取り消してください。", "点数已用完。请先取消其他能力。") },
        { "진화 완료", L("Evolved", "進化完了", "已进化") },
        { "진화!", L("Evolve!", "進化！", "进化！") },
        { "진화 가능", L("Can evolve", "進化可能", "可进化") },
        { "진화: ", L("Evolve: ", "進化: ", "进化: ") },
        { "강화 완료", L("Upgrade", "強化完了", "强化完成") },
        { "포인트 ", L("Points ", "ポイント ", "点数 ") },
        { "선택 완료", L("Confirm", "選択完了", "确认选择") },
        { "남은 포인트 ", L("Points left ", "残りポイント ", "剩余点数 ") },
        { "특수 능력 포인트 ", L("Special points ", "特殊能力ポイント ", "特殊能力点数 ") },
        { "새 능력을 배우거나 가진 능력을 진화", L("Learn a new ability or evolve one you have", "新しい能力を覚えるか、持っている能力を進化", "学习新能力或进化已有能力") },
        { "파란 테두리는 이미 가진 능력입니다. 한 번 더 고르면 진화해서 더 강해집니다. 남은 포인트는 아껴 두었다가 나중에 써도 됩니다.", L("Abilities with a blue frame are ones you own. Pick them again to evolve them. You can save leftover points for later.", "青い枠はすでに持っている能力です。もう一度選ぶと進化して強くなります。残ったポイントは取っておいて後で使えます。", "蓝框表示已拥有的能力。再次选择即可进化变强。剩余点数可以留到以后使用。") },
        { "능력 ", L("Choose ", "能力を ", "请选择 ") },
        { "개를 고르세요", L(" abilities", "つ選んでください", "项能力") },
        { "개 · 노드를 눌러 선택", L(" · click nodes to choose", "つ・ノードを押して選択", "点 · 点击节点选择") },
        { "무기는 {SWAP}로 기본 권총과 번갈아 쓰고, 스킬은 고른 순서대로 {SKILL1} · {SKILL2} · {SKILL3}에 배정됩니다. 다시 누르면 선택이 취소됩니다.", L("Swap weapons with the pistol using {SWAP}; skills go to {SKILL1} · {SKILL2} · {SKILL3} in the order you pick them. Click again to cancel.", "武器は{SWAP}で基本拳銃と切り替え、スキルは選んだ順に{SKILL1}・{SKILL2}・{SKILL3}に割り当てられます。もう一度押すと選択を取り消します。", "武器用{SWAP}与基础手枪切换，技能按选择顺序分配到{SKILL1} · {SKILL2} · {SKILL3}。再次点击取消选择。") },
        { " → 진화", L(" → Evolve", " → 進化", " → 进化") },
        { "  (선택됨)", L("  (selected)", "  (選択中)", "  (已选择)") },
        { "  (진화 완료)", L("  (evolved)", "  (進化済み)", "  (已进化)") },
        { "<color=#9fd8ff>진화</color>  ", L("<color=#9fd8ff>Evolve</color>  ", "<color=#9fd8ff>進化</color>  ", "<color=#9fd8ff>进化</color>  ") },
        { "무기 · {SWAP}로 교체", L("Weapon · Swap with {SWAP}", "武器・{SWAP}で切替", "武器 · {SWAP}切换") },
        { "스킬 · {SKILL1}/{SKILL2}/{SKILL3}", L("Skill · {SKILL1}/{SKILL2}/{SKILL3}", "スキル・{SKILL1}/{SKILL2}/{SKILL3}", "技能 · {SKILL1}/{SKILL2}/{SKILL3}") },
        { "패시브 · 항상 적용", L("Passive · Always on", "パッシブ・常時発動", "被动 · 始终生效") },

        // ================================================================= 능력치 창
        { "공격력", L("Attack", "攻撃力", "攻击力") },
        { "방어력", L("Defense", "防御力", "防御力") },
        { "공격 속도", L("Fire Rate", "攻撃速度", "攻击速度") },
        { "재장전", L("Reload", "リロード", "换弹") },
        { "이동 속도", L("Move Speed", "移動速度", "移动速度") },
        { "능력치", L("Stats", "ステータス", "属性") },
        { "눌러서 능력치 창을 열고 닫습니다.", L("Click to open or close the stats panel.", "押してステータス画面を開閉します。", "点击打开或关闭属性面板。") },
        { "/초", L("/s", "/秒", "/秒") },
        // ================================================================= 튜토리얼
        { "기본 조작", L("Basic Controls", "基本操作", "基本操作") },
        { "이동", L("Move", "移動", "移动") },
        { "좌클릭", L("Left Click", "左クリック", "左键") },
        { "우클릭", L("Right Click", "右クリック", "右键") },
        { "마우스 방향으로 사격", L("Shoot toward the cursor", "マウスの方向に射撃", "朝鼠标方向射击") },
        { "무기 교체 (특수 무기를 얻은 뒤)", L("Swap weapons (after getting special weapons)", "武器切替(特殊武器を手に入れた後)", "切换武器(获得特殊武器后)") },
        { "일시정지 · 설정", L("Pause · Settings", "一時停止・設定", "暂停 · 设置") },
        { "필살기", L("Ultimates", "必殺技", "必杀技") },
        { "스킬 게이지", L("Skill Gauge", "スキルゲージ", "技能能量") },
        { "시간이 지나면 차고, 적을 처치하면 잠깐 더 빨리 찹니다", L("Fills over time, and faster for a moment after each kill", "時間で溜まり、敵を倒すと少しの間速く溜まります", "随时间积累，击杀后短时间积累更快") },
        { "게이지가 가득 차면 필살기를 씁니다", L("Use your ultimate when the gauge is full", "ゲージが満タンになったら必殺技を使います", "能量满时释放必杀技") },
        { "조준형", L("Aimed", "照準型", "瞄准型") },
        { "누르고 있으면 시간이 느려지며 적을 조준, 떼면 발동", L("Hold to slow time and mark enemies, release to fire", "押し続けると時間が遅くなり敵を狙い、離すと発動", "按住时时间变慢并锁定敌人，松开释放") },
        { "즉발형", L("Instant", "即発型", "瞬发型") },
        { "산탄총 · 쌍권총 · 유탄은 누르는 즉시 발동", L("Shotgun · Twin Pistols · Grenade fire instantly", "ショットガン・二丁拳銃・グレネードは押した瞬間に発動", "霰弹枪 · 双枪 · 榴弹按下即释放") },
        { "성장", L("Growth", "成長", "成长") },
        { "레벨업", L("Level Up", "レベルアップ", "升级") },
        { "카드를 클릭해 고르고 {INTERACT}로 확정", L("Click a card and press {INTERACT} to confirm", "カードをクリックして選び、{INTERACT}で決定", "点击卡牌选择，按{INTERACT}确认") },
        { "상점 제단", L("Shop Altar", "ショップの祭壇", "商店祭坛") },
        { "적 35마리마다 나타남 · 다가가서 {INTERACT}로 열기", L("Appears every 35 kills · walk up and press {INTERACT}", "敵35体ごとに出現・近づいて{INTERACT}で開く", "每击杀35个敌人出现 · 靠近后按{INTERACT}打开") },
        { "능력치 · 무기 강화 · 스킬 강화", L("Stats · Weapon upgrades · Skill upgrades", "ステータス・武器強化・スキル強化", "属性 · 武器强化 · 技能强化") },
        { "코인", L("Coins", "コイン", "金币") },
        { "적이 떨어뜨림 · 코인 자석 능력으로 끌어올 수 있음", L("Dropped by enemies · pull them in with Coin Magnet", "敵が落とす・コインマグネットで引き寄せられる", "敌人掉落 · 可用金币磁铁吸引") },
        { "특수 능력", L("Special Abilities", "特殊能力", "特殊能力") },
        { "1장 보스를 쓰러뜨리고 문에 들어가면 특수 능력 3개를 고릅니다", L("Beat the chapter 1 boss and enter the gate to pick 3 special abilities", "第1章のボスを倒して門に入ると特殊能力を3つ選びます", "击败第1章首领并进入大门后，选择3项特殊能力") },
        { "무기 · 스킬 · 패시브", L("Weapons · Skills · Passives", "武器・スキル・パッシブ", "武器 · 技能 · 被动") },
        { "무기는 {SWAP}로 교체, 스킬은 {SKILL1} · {SKILL2} · {SKILL3}", L("Swap weapons with {SWAP}; skills on {SKILL1} · {SKILL2} · {SKILL3}", "武器は{SWAP}で切替、スキルは{SKILL1}・{SKILL2}・{SKILL3}", "武器用{SWAP}切换，技能用{SKILL1} · {SKILL2} · {SKILL3}") },
        { "특수 강화 ({UPGRADE})", L("Special Upgrade ({UPGRADE})", "特殊強化 ({UPGRADE})", "特殊强化 ({UPGRADE})") },
        { "중간 보스를 잡으면 포인트 · 새 능력을 배우거나 가진 능력을 진화", L("Mid-bosses give points · learn new abilities or evolve yours", "中ボスを倒すとポイント・新しい能力を覚えるか持っている能力を進化", "击败中头目获得点数 · 学习新能力或进化已有能力") },
        { "적과 보스", L("Enemies & Bosses", "敵とボス", "敌人与首领") },
        { "경고 표시", L("Warnings", "警告表示", "警告标记") },
        { "붉은 원 · 선 · 머리 위 ! 가 보이면 그 자리를 피하세요", L("Red circles, lines and a ! above heads mean: get out of the way", "赤い円・線・頭上の！が見えたらその場から離れましょう", "看到红圈、红线或头顶的！就快躲开") },
        { "중간 보스", L("Mid-bosses", "中ボス", "中头目") },
        { "2장부터 단계가 오를 때마다 등장 · 특수 능력 포인트를 줌", L("From chapter 2, one appears each time the phase rises · gives a special point", "第2章から段階が上がるたびに出現・特殊能力ポイントをくれる", "从第2章起每次阶段提升时出现 · 给予特殊能力点数") },
        { "보스", L("Bosses", "ボス", "首领") },
        { "리치 왕 → 지옥의 군주 → 킹 슬라임", L("Lich King → Demon Lord → King Slime", "リッチ王 → 地獄の君主 → キングスライム", "巫妖王 → 地狱领主 → 史莱姆王") },
        { "특수 스킬", L("Special Skills", "特殊スキル", "特殊技能") },
        { "보스는 체력이 절반 아래로 떨어지면 특수 스킬을 씁니다", L("Bosses use a special skill below half HP", "ボスは体力が半分を切ると特殊スキルを使います", "首领生命低于一半时会使用特殊技能") },
        { "목표", L("Goal", "目標", "目标") },
        { "3개의 스테이지", L("Three Stages", "3つのステージ", "三个关卡") },
        { "지하 묘역 → 불타는 지옥 → 초원", L("Catacombs → Burning Hell → Meadow", "地下墓所 → 燃える地獄 → 草原", "地下墓穴 → 燃烧地狱 → 草原") },
        { "문", L("Gates", "門", "大门") },
        { "보스를 쓰러뜨리면 30초 안에 문으로 들어가세요", L("After beating a boss, enter the gate within 30 seconds", "ボスを倒したら30秒以内に門に入りましょう", "击败首领后请在30秒内进入大门") },
        { "행운을 빌어요!", L("Good luck!", "幸運を祈ります！", "祝你好运！") },
        { "모든 보스를 쓰러뜨리면 승리합니다", L("Defeat every boss to win", "全てのボスを倒せば勝利です", "击败所有首领即可获胜") },
        // 도감 · 보스 이름
        { "도감", L("Codex", "図鑑", "图鉴") },
        { "적", L("Enemies", "敵", "敌人") },
        { "무기", L("Weapons", "武器", "武器") },
        { "진화", L("Evolution", "進化", "进化") },
        { "스테이지마다 나오는 적과 스킬 · 붉은 경고가 보이면 피하세요", L("Enemies of each stage and their skills · dodge when you see a red warning", "ステージごとの敵とスキル・赤い警告が見えたら避けよう", "各关卡的敌人与技能 · 看到红色警告就躲开") },
        { "각 스테이지의 마지막 적 · 체력이 절반 아래로 떨어지면 특수 스킬을 씁니다", L("The final foe of each stage · uses a special skill below half health", "各ステージ最後の敵・体力が半分を切ると特殊スキルを使う", "每关的最终敌人 · 生命低于一半时使用特殊技能") },
        { "{SWAP}로 교체 · 우클릭 필살기는 무기마다 다릅니다", L("Swap with {SWAP} · each weapon has its own right-click ultimate", "{SWAP}で切り替え・右クリックの必殺技は武器ごとに違う", "按{SWAP}切换 · 每把武器的右键必杀技都不同") },
        { "{SKILL1} · {SKILL2} · {SKILL3} 순서로 배정 (최대 3개)", L("Bound to {SKILL1} · {SKILL2} · {SKILL3} in order (up to 3)", "{SKILL1}・{SKILL2}・{SKILL3}の順に割り当て（最大3つ）", "依次绑定到 {SKILL1} · {SKILL2} · {SKILL3}（最多3个）") },
        { "고르면 항상 적용되는 능력", L("Always active once chosen", "選ぶと常に効果がある能力", "选择后始终生效的能力") },
        { "특수 강화({UPGRADE})에서 이미 가진 능력을 한 번 더 고르면 진화합니다", L("Pick an ability you already own again in Special Upgrade ({UPGRADE}) to evolve it", "特殊強化({UPGRADE})で持っている能力をもう一度選ぶと進化する", "在特殊强化({UPGRADE})中再次选择已拥有的能力即可进化") },
        { "레벨이 오를 때 세 장의 카드 중 하나를 고릅니다", L("Choose one of three cards when you level up", "レベルアップ時に3枚のカードから1枚選ぶ", "升级时从三张卡中选择一张") },
        { "상점 제단(적 35마리마다)에서 코인으로 강화합니다", L("Upgrade with coins at the shop altar (every 35 kills)", "ショップの祭壇（敵35体ごと）でコインを使って強化", "在商店祭坛（每击杀35个敌人）用金币强化") },
        { "지하 묘역", L("Catacombs", "地下墓所", "地下墓穴") },
        { "불타는 지옥", L("Burning Hell", "燃える地獄", "燃烧地狱") },
        { "초원", L("Meadow", "草原", "草原") },
        { "해골", L("Skeleton", "スケルトン", "骷髅") },
        { "지하 묘역의 기본 적. 스킬 없이 곧장 달려듭니다.", L("The basic foe of the Catacombs. Charges straight at you, no skills.", "地下墓所の基本の敵。スキルなしでまっすぐ突っ込んでくる。", "地下墓穴的基本敌人。没有技能，直接冲过来。") },
        { "구울", L("Ghoul", "グール", "食尸鬼") },
        { "떨어질 곳에 원을 띄운 뒤 높이 뛰어 내려찍습니다.", L("Marks a circle where it will land, then leaps high and slams down.", "着地点に円を表示してから高く跳び、叩きつける。", "先在落点显示圆圈，再高高跃起砸下。") },
        { "망령", L("Wraith", "亡霊", "怨灵") },
        { "사라졌다가 표시한 곳에 나타나며 영혼 폭발을 일으킵니다.", L("Vanishes, reappears at a marked spot and unleashes a soul burst.", "消えてから印の場所に現れ、魂の爆発を起こす。", "消失后在标记处出现，引发灵魂爆炸。") },
        { "임프", L("Imp", "インプ", "小恶魔") },
        { "지그재그로 움직이며 플레이어 자리에 X자 레이저를 쏩니다.", L("Zigzags around and fires an X-shaped laser at your position.", "ジグザグに動き、プレイヤーの位置にX字レーザーを撃つ。", "之字形移动，向玩家位置发射X形激光。") },
        { "불꽃 해골", L("Flame Skull", "炎のドクロ", "火焰骷髅") },
        { "가까이 오면 부풀어 오르다 폭발합니다.", L("Swells up when close, then explodes.", "近づくと膨らんで爆発する。", "靠近后膨胀并爆炸。") },
        { "지옥견", L("Hellhound", "ヘルハウンド", "地狱犬") },
        { "경로를 보여준 뒤 일직선으로 돌진합니다.", L("Shows its path, then dashes in a straight line.", "進路を示してから一直線に突進する。", "显示路线后直线冲刺。") },
        { "용암 골렘", L("Lava Golem", "溶岩ゴーレム", "熔岩魔像") },
        { "점점 넓어지는 세 번의 지면 파동을 일으킵니다.", L("Sends out three ever-widening ground shockwaves.", "だんだん広がる3回の地面の波動を起こす。", "释放三次逐渐扩大的地面冲击波。") },
        { "악마 기사", L("Demon Knight", "悪魔の騎士", "恶魔骑士") },
        { "칼날을 휘감고 회전하며 플레이어 쪽으로 미끄러집니다.", L("Spins wrapped in blades and slides toward you.", "刃をまとって回転し、プレイヤーの方へ滑り込む。", "裹挟刀刃旋转，向玩家滑行。") },
        { "초원 슬라임", L("Meadow Slime", "草原スライム", "草原史莱姆") },
        { "밟으면 아픈 산성 웅덩이를 남깁니다.", L("Leaves acid puddles that hurt to step on.", "踏むと痛い酸の水たまりを残す。", "留下踩到会受伤的酸液水洼。") },
        { "거대 벌", L("Giant Bee", "巨大バチ", "巨型蜜蜂") },
        { "플레이어 주변에 꽃가루 구름을 뿌립니다. 안에 있으면 느려지고 조금씩 아픕니다.", L("Spreads pollen clouds around you. Inside, you slow down and take small damage.", "プレイヤーの周りに花粉の雲をまく。中にいると遅くなり少しずつダメージ。", "在玩家周围散布花粉云。身处其中会减速并持续受伤。") },
        { "버섯 거인", L("Mushroom Brute", "キノコの巨人", "蘑菇巨人") },
        { "주변에 버섯 지뢰를 심고 잠시 뒤 차례로 터뜨립니다.", L("Plants mushroom mines nearby that burst one after another.", "周りにキノコ地雷を植え、しばらくして順に爆発させる。", "在周围种下蘑菇地雷，片刻后依次引爆。") },
        { "다이어울프", L("Dire Wolf", "ダイアウルフ", "恐狼") },
        { "울부짖어 주변 적을 잠시 빠르게 만듭니다.", L("Howls to briefly speed up nearby enemies.", "遠吠えで周りの敵を一時的に速くする。", "嚎叫让周围的敌人暂时加速。") },
        { "트렌트", L("Treant", "トレント", "树人") },
        { "플레이어 쪽으로 뿌리 가시를 차례로 솟게 합니다.", L("Raises a line of root spikes toward you.", "プレイヤーの方へ根のトゲを次々と突き出す。", "朝玩家方向依次升起根刺。") },
        { "2장부터", L("From Stage 2", "第2章から", "第2章起") },
        { "단계가 오를 때마다 크고 단단한 적이 나타납니다. 체력 12배 · 피해 1.5배. 쓰러뜨리면 특수 능력 포인트를 줍니다.", L("A big, tough enemy appears at each new phase. 12× health · 1.5× damage. Drops a special ability point.", "段階が上がるたびに大きく硬い敵が現れる。体力12倍・ダメージ1.5倍。倒すと特殊能力ポイントがもらえる。", "每进入新阶段都会出现高大坚硬的敌人。生命×12 · 伤害×1.5。击败后获得特殊能力点。") },
        { "리치 왕", L("Lich King", "リッチ王", "巫妖王") },
        { "지옥의 군주", L("Demon Lord", "地獄の君主", "地狱领主") },
        { "킹 슬라임", L("King Slime", "キングスライム", "史莱姆王") },
        { "지하 묘역의 주인", L("Master of the Catacombs", "地下墓所の主", "地下墓穴之主") },
        { "불타는 지옥의 왕", L("King of the Burning Hell", "燃える地獄の王", "燃烧地狱之王") },
        { "초원의 폭군", L("Tyrant of the Meadow", "草原の暴君", "草原暴君") },
        { "감히 내 잠든 묘역을 깨우다니...", L("How dare you wake my sleeping catacombs...", "よくも眠れる墓所を目覚めさせたな……", "竟敢惊醒我沉睡的墓穴……") },
        { "네 영혼도 내 망자의 군대에 더해 주마!", L("Your soul shall join my army of the dead!", "貴様の魂も死者の軍勢に加えてやろう！", "你的灵魂也将加入我的亡者大军！") },
        { "하찮은 인간이 지옥의 문턱을 넘었군.", L("A worthless human has crossed the threshold of Hell.", "取るに足らぬ人間が地獄の門をくぐったか。", "卑微的人类竟跨过了地狱的门槛。") },
        { "불길 속에서 재가 되어라!", L("Burn to ashes in my flames!", "炎の中で灰となれ！", "在烈焰中化为灰烬吧！") },
        { "뿌요... 이 초원은 이 몸의 식탁이다!", L("Puyo... This meadow is my dinner table!", "ぷよ……この草原はわしの食卓だ！", "噗哟……这片草原是本大王的餐桌！") },
        { "납작하게 짓눌러 주마, 뿌요요옹!", L("I'll squash you flat, puyoyoooong!", "ぺしゃんこにしてやる、ぷよよ〜ん！", "把你压成肉饼，噗哟哟哟！") },
        { "부하를 부르며 망령의 손아귀 · 저주 표식 · 뼈 가시 격자를 씁니다.\n특수: 망자의 의식 - 영혼 등불이 돌며 나선 탄막을 쏜 뒤 대폭발", L("Summons minions and uses Wraith Grasp · Curse Mark · Bone Spike Grid.\nSpecial: Rite of the Dead - soul lanterns fire spiral barrages, then a huge blast", "手下を呼び、亡霊の手・呪いの印・骨のトゲ格子を使う。\n特殊：死者の儀式 - 魂の灯籠が回って螺旋弾幕を撃ち、大爆発", "召唤手下，使用怨灵之握 · 诅咒印记 · 骨刺网格。\n特殊：亡者仪式 - 灵魂灯笼旋转发射螺旋弹幕，随后大爆炸") },
        { "화염 돌진 · 운석 낙하 · 화염 파동(틈으로 피하세요)을 씁니다.\n특수: 십자 불길 - 네 줄기 불기둥이 천천히 회전", L("Uses Flame Charge · Meteor Fall · Fire Wave (escape through the gap).\nSpecial: Cross Inferno - four pillars of fire slowly rotate", "炎の突進・隕石落下・炎の波動（隙間から避けよう）を使う。\n特殊：十字の業火 - 4本の火柱がゆっくり回転", "使用火焰冲锋 · 陨石坠落 · 火焰波（从缺口躲避）。\n特殊：十字烈焰 - 四道火柱缓慢旋转") },
        { "대점프 · 산성 비 · 구르기 돌진을 씁니다. 쓰러질 때마다 작고 빠르게 분열합니다 (1 → 2 → 3마리).\n특수: 슬라임 폭우 - 빠른 대점프 3연속", L("Uses Big Jump · Acid Rain · Rolling Charge. Splits into smaller, faster slimes each time it falls (1 → 2 → 3).\nSpecial: Slime Storm - three quick big jumps in a row", "大ジャンプ・酸の雨・転がり突進を使う。倒れるたびに小さく速く分裂する（1 → 2 → 3体）。\n特殊：スライム豪雨 - 素早い大ジャンプ3連続", "使用大跳跃 · 酸雨 · 翻滚冲锋。每次倒下都会分裂成更小更快的史莱姆（1 → 2 → 3只）。\n特殊：史莱姆暴雨 - 连续三次快速大跳跃") },
        { "마우스 쪽으로 거대한 부채꼴 폭발을 3번 연달아 일으킵니다.", L("Unleashes three huge cone-shaped blasts toward the mouse.", "マウスの方へ巨大な扇形の爆発を3連続で起こす。", "向鼠标方向连续引发三次巨大扇形爆炸。") },
        { "우클릭을 누른 채 방향을 정하면 충전 뒤 화면을 가로지르는 굵은 광선을 쏩니다. 광선 위의 적이 많을수록 강합니다.", L("Hold right-click to aim; after charging, fires a thick beam across the screen. Stronger the more enemies it hits.", "右クリックを押したまま方向を決めると、チャージ後に画面を横切る太い光線を撃つ。光線上の敵が多いほど強い。", "按住右键决定方向，充能后发射横贯屏幕的粗光束。光束上的敌人越多越强。") },
        { "두 줄기 나선으로 사방에 총알을 난사합니다. 움직이며 쓸 수 있습니다.", L("Sprays bullets everywhere in a double spiral. You can move while using it.", "2本の螺旋で四方に弾を乱射する。動きながら使える。", "以双螺旋向四周扫射子弹。可以边移动边使用。") },
        { "우클릭을 누른 채 자리를 정하면 불기둥이 생겨 적을 빨아들이고 태웁니다.", L("Hold right-click to pick a spot; a fire tornado appears, pulling in and burning enemies.", "右クリックを押したまま場所を決めると、火柱が現れて敵を吸い込み燃やす。", "按住右键选择位置，生成火焰龙卷吸入并焚烧敌人。") },
        { "영혼 구슬들이 주위를 돌다 조준한 적에게 번갈아 달려듭니다.", L("Soul orbs circle you, then take turns rushing the targeted enemies.", "魂の玉が周りを回り、狙った敵に交互に飛びかかる。", "灵魂球环绕身边，轮流冲向锁定的敌人。") },
        { "먹구름이 따라다니며 조준한 적들에게 번개를 연달아 떨어뜨립니다.", L("A storm cloud follows you, dropping lightning on the targeted enemies.", "黒雲がついてきて、狙った敵に雷を次々と落とす。", "乌云跟随你，向锁定的敌人接连降下雷电。") },
        { "무적 상태로 조준한 적들 사이를 순간이동하며 벤 뒤 제자리로 돌아옵니다.", L("Invincible, you teleport between targeted enemies slashing them, then return to where you started.", "無敵状態で狙った敵の間を瞬間移動して斬り、元の場所に戻る。", "无敌状态下在锁定的敌人之间瞬移斩击，然后回到原位。") },
        { "플레이어에서 마우스 쪽으로 줄지어 운석이 떨어집니다.", L("Rows of meteors rain down from you toward the mouse.", "プレイヤーからマウスの方へ隕石が列になって落ちる。", "陨石从玩家向鼠标方向成排落下。") },
        { "총알이 적을 1마리 더 관통합니다.", L("Bullets pierce one more enemy.", "弾が敵をもう1体貫通する。", "子弹多穿透1个敌人。") },
        { "적이 코인을 1개 더 떨어뜨립니다.", L("Enemies drop one more coin.", "敵がコインをもう1枚落とす。", "敌人多掉落1枚金币。") },
        { "스킬 게이지가 20% 줄어 필살기를 더 자주 씁니다.", L("Skill gauge is 20% shorter, so you ult more often.", "スキルゲージが20%短くなり、必殺技をより頻繁に使える。", "技能槽缩短20%，更频繁地使用必杀技。") },
        { "필살기를 조준하는 동안 타겟이 된 적이 20% 더 느려집니다.", L("Targeted enemies are 20% slower while you aim your ultimate.", "必殺技の照準中、狙われた敵が20%さらに遅くなる。", "瞄准必杀技时，被锁定的敌人额外减速20%。") },
        { "처치 경험치가 10% 늘어납니다.", L("Kill EXP +10%.", "撃破経験値が10%増える。", "击杀经验+10%。") },
        { "주변의 코인을 끌어옵니다. 범위 +4 (최대 4번)", L("Pulls in nearby coins. Range +4 (up to 4 times)", "周りのコインを引き寄せる。範囲+4（最大4回）", "吸引附近的金币。范围+4（最多4次）") },
        { "한 번에 쏘는 총알이 1발 늘지만 한 발당 피해는 줄어듭니다.", L("Fire one more bullet per shot, but each deals less damage.", "一度に撃つ弾が1発増えるが、1発あたりのダメージは減る。", "每次多发射1颗子弹，但单发伤害降低。") },
        { "총알이 적을 밀어내는 힘 +25% (최대 3번)", L("Bullet knockback +25% (up to 3 times)", "弾のノックバック+25%（最大3回）", "子弹击退+25%（最多3次）") },
        { "체력을 모두 회복하고 최대 체력이 12% 늘어납니다.", L("Fully heals and raises max health by 12%.", "体力を全回復し、最大体力が12%増える。", "完全恢复生命，最大生命+12%。") },
        { "받는 피해 -12% (최대 3번)", L("Damage taken -12% (up to 3 times)", "受けるダメージ-12%（最大3回）", "受到伤害-12%（最多3次）") },
        { "시간이 지나면 체력이 회복됩니다. 초당 +0.5 (최대 4번)", L("Regenerate health over time. +0.5 per second (up to 4 times)", "時間とともに体力が回復する。毎秒+0.5（最大4回）", "随时间恢复生命。每秒+0.5（最多4次）") },
        { "적을 처치할 때마다 체력 +1 회복 (최대 3번)", L("Heal +1 health per kill (up to 3 times)", "敵を倒すたびに体力+1回復（最大3回）", "每击杀一个敌人恢复1点生命（最多3次）") },
        { "능력치 상점", L("Stat Shop", "ステータスショップ", "属性商店") },
        { "공격력 · 공격 속도 · 재장전 속도 · 탄창 · 이동 속도를 올립니다. 살수록 값이 오릅니다.", L("Raise attack · fire rate · reload speed · magazine · move speed. Prices rise as you buy.", "攻撃力・攻撃速度・リロード速度・弾倉・移動速度を上げる。買うほど値段が上がる。", "提升攻击力 · 攻击速度 · 装填速度 · 弹匣 · 移动速度。买得越多越贵。") },
        { "2장부터. 특수 무기마다 피해 · 연사 · 탄창 · 고유 특성을 올립니다.", L("From Stage 2. Raise damage · fire rate · magazine · a unique trait for each special weapon.", "第2章から。特殊武器ごとにダメージ・連射・弾倉・固有特性を上げる。", "第2章起。为每把特殊武器提升伤害 · 射速 · 弹匣 · 专属特性。") },
        { "필살기의 위력과 무기마다 다른 특성(타겟 수 · 지속 시간 등)을 올립니다.", L("Raise your ultimate's power and a per-weapon trait (targets · duration, etc.).", "必殺技の威力と武器ごとの特性（ターゲット数・持続時間など）を上げる。", "提升必杀技威力和各武器的特性（目标数 · 持续时间等）。") },
        { "특수 능력 포인트", L("Special Ability Points", "特殊能力ポイント", "特殊能力点") },
        { "중간 보스를 잡으면 얻습니다. T를 눌러 새 능력을 배우거나 가진 능력을 진화합니다.", L("Earned from mid-bosses. Press T to learn a new ability or evolve one you own.", "中ボスを倒すと手に入る。Tで新しい能力を覚えるか、持っている能力を進化させる。", "击败精英首领获得。按T学习新能力或进化已有能力。") },
        { "처음부터 가진 무기", L("Your starting weapon", "最初から持っている武器", "初始武器") },
        { "좌클릭으로 사격, R로 재장전.", L("Left-click to shoot, R to reload.", "左クリックで射撃、Rでリロード。", "左键射击，R键装填。") },
        { "우클릭을 누른 채 적을 조준하고, 떼면 조준한 적들에게 한꺼번에 쏩니다.", L("Hold right-click to target enemies, release to fire at all of them at once.", "右クリックを押したまま敵を狙い、離すと狙った敵に一斉に撃つ。", "按住右键锁定敌人，松开后向所有锁定的敌人齐射。") },
        { "특수 무기", L("Special Weapon", "特殊武器", "特殊武器") },
        { "강화 특성", L("Upgrade Trait", "強化特性", "强化特性") },
        { "즉발", L("Instant", "即発", "瞬发") },
        { "조준", L("Aimed", "照準", "瞄准") },
        { "체력", L("HP", "体力", "生命") },
        { "속도", L("Speed", "速度", "速度") },
        { "접촉 피해", L("Contact Dmg", "接触ダメージ", "接触伤害") },
        // v3.1 캐릭터 이야기 · 검사 베기 · 도적 출혈 돌진
        { "떠돌이 기사는 녹슨 장검 한 자루를 등에 메고 무너진 신전 앞에 섰다.", L("The wandering knight stood before the ruined temple, a rusty longsword on his back.", "流浪の騎士は錆びた長剣を背負い、崩れた神殿の前に立った。", "流浪骑士背着一把生锈的长剑，站在了倒塌的神殿前。") },
        { "총알은 떨어져도, 칼날은 떨어지지 않는다.", L("Bullets run out. A blade never does.", "弾は尽きても、刃は尽きない。", "子弹会打光，剑刃却不会。") },
        { "기사는 망설임 없이 어둠 속으로 뛰어내렸다.", L("Without hesitation, the knight leapt into the dark.", "騎士はためらうことなく闇の中へ飛び降りた。", "骑士毫不犹豫地跳入了黑暗之中。") },
        { "그림자 칼날이라 불리는 도적은 신전 지하에 잠든 보물 이야기를 들었다.", L("The rogue called the Shadow Blade had heard of treasure sleeping beneath the temple.", "影の刃と呼ばれる盗賊は、神殿の地下に眠る宝の噂を聞いた。", "人称暗影之刃的盗贼，听说了沉睡在神殿地下的宝藏。") },
        { "망자든 악마든, 등을 보인 놈부터 쓰러진다.", L("Undead or demon, whoever turns their back falls first.", "亡者でも悪魔でも、背中を見せた奴から倒れる。", "无论亡者还是恶魔，先露出后背的先倒下。") },
        { "도적은 소리 없이 구멍 아래로 몸을 날렸다.", L("Without a sound, the rogue dropped into the hole.", "盗賊は音もなく穴の底へ身を躍らせた。", "盗贼悄无声息地跃入了洞中。") },
        { "숲의 사냥꾼은 죽은 짐승들이 숲을 떠나 신전으로 향하는 것을 보았다.", L("The forest hunter watched dead beasts leave the woods and head for the temple.", "森の狩人は、死んだ獣たちが森を離れ神殿へ向かうのを見た。", "森林猎人看见死去的野兽离开森林，走向神殿。") },
        { "흔적을 따라가자, 무너진 신전의 구멍이 나타났다.", L("Following the tracks, the hunter found a hole in the ruined temple.", "足跡を追うと、崩れた神殿の穴が現れた。", "循着踪迹，倒塌神殿的洞口出现在眼前。") },
        { "화살통은 가득하다. 이번 사냥감은 리치 왕이다.", L("The quiver is full. Today's quarry is the Lich King.", "矢筒は満杯だ。今回の獲物はリッチ王だ。", "箭筒已满。这次的猎物是巫妖王。") },
        { "미친 학자는 오히려 기뻤다. 되살아난 시체라니, 이렇게 좋은 재료가 또 있을까.", L("The mad scholar was delighted. Walking corpses — what finer ingredients could there be?", "狂った学者はむしろ喜んだ。蘇った屍なんて、これ以上の素材があるだろうか。", "疯狂学者反而很高兴。复活的尸体——还有比这更好的材料吗？") },
        { "플라스크를 허리춤에 가득 채우고, 학자는 신전의 구멍으로 뛰어들었다.", L("Belt packed with flasks, the scholar jumped into the temple's hole.", "腰にフラスコを詰め込み、学者は神殿の穴へ飛び込んだ。", "腰间挂满烧瓶，学者跳进了神殿的洞口。") },
        { "“자, 실험을 시작하지.”", L("\"Now then, let the experiment begin.\"", "「さて、実験を始めよう。」", "“那么，实验开始吧。”") },
        { "기사는 이 빠진 장검을 닦아 칼집에 꽂았다.", L("The knight wiped the notched longsword and sheathed it.", "騎士は刃こぼれした長剣を拭い、鞘に収めた。", "骑士擦净了满是缺口的长剑，收入鞘中。") },
        { "사람들은 총 한 자루 없이 세상을 구한 기사를 신기한 듯 바라보았다.", L("People stared in wonder at the knight who saved the world without a single gun.", "人々は銃ひとつ持たずに世界を救った騎士を不思議そうに見つめた。", "人们惊奇地望着这位没用一把枪就拯救了世界的骑士。") },
        { "“총이 아니어도 괜찮다. 지킬 수만 있다면.”", L("\"It needn't be a gun. So long as I can protect them.\"", "「銃でなくてもいい。守れさえすれば。」", "“不是枪也无妨。只要能守护就好。”") },
        { "도적은 리치 왕의 왕관을 슬쩍 품에 넣었다.", L("The rogue quietly slipped the Lich King's crown inside their coat.", "盗賊はリッチ王の王冠をこっそり懐に入れた。", "盗贼悄悄把巫妖王的王冠揣进了怀里。") },
        { "영웅의 이름을 물었을 때, 도적은 이미 그림자 속으로 사라진 뒤였다.", L("When people asked the hero's name, the rogue had already vanished into the shadows.", "英雄の名を尋ねたとき、盗賊はすでに影の中へ消えていた。", "当人们询问英雄的名字时，盗贼早已消失在阴影之中。") },
        { "다음 날, 왕궁의 보물 창고가 텅 비었다는 소문이 돌았다.", L("The next day, rumors spread that the royal treasury was empty.", "翌日、王宮の宝物庫が空っぽになったという噂が流れた。", "第二天，传出了王宫宝库被洗劫一空的传闻。") },
        { "사냥꾼은 마지막 화살을 거두어 화살통에 꽂았다.", L("The hunter gathered the last arrow and slid it back into the quiver.", "狩人は最後の矢を拾い、矢筒に収めた。", "猎人收回最后一支箭，插回箭筒。") },
        { "숲에는 다시 새소리가 돌아왔다.", L("Birdsong returned to the forest.", "森には再び鳥のさえずりが戻ってきた。", "森林里再次响起了鸟鸣。") },
        { "사람들은 숲의 사냥꾼에게 깊이 고개를 숙였다.", L("The people bowed deeply to the forest hunter.", "人々は森の狩人に深く頭を下げた。", "人们向森林猎人深深鞠躬。") },
        { "학자는 킹 슬라임의 점액을 플라스크에 담으며 킬킬 웃었다.", L("The scholar giggled while bottling the King Slime's goo.", "学者はキングスライムの粘液をフラスコに詰めながらクスクス笑った。", "学者一边把史莱姆王的黏液装进烧瓶，一边嘿嘿直笑。") },
        { "“이걸로 논문 세 편은 쓰겠군.”", L("\"That's three papers' worth of material, at least.\"", "「これで論文が三本は書けるな。」", "“这些够我写三篇论文了。”") },
        { "세상은 구해졌다. 대부분은 우연이었지만.", L("The world was saved. Mostly by accident.", "世界は救われた。ほとんどは偶然だったが。", "世界得救了。虽然大部分是出于偶然。") },
        { "검을 크게 휘둘러 앞쪽 부채꼴의 적을 직접 벱니다", L("Swing the sword wide to cut every enemy in a cone ahead", "剣を大きく振るい、前方の扇形の敵を直接斬ります", "大幅挥剑，直接斩击前方扇形范围内的敌人") },
        { "약하지만 빠른 표창 세례와 그림자 돌진으로 싸우는 암살자.", L("A frail assassin who fights with a hail of fast throwing stars and shadow dashes.", "非力だが素早い手裏剣の雨と影の突進で戦う暗殺者。", "虽然柔弱，却以飞快的飞镖和暗影突进作战的刺客。") },
        { "출혈 돌진", L("Bleeding Dash", "出血突進", "出血突进") },
        { "무적 상태로 마우스 방향으로 돌진해, 지나간 적에게 출혈 피해를 입힙니다 (즉발)", L("Dash toward the mouse while invincible, making every enemy you pass bleed (instant)", "無敵状態でマウスの方向へ突進し、通り過ぎた敵に出血ダメージを与えます（即発動）", "在无敌状态下朝鼠标方向突进，使途经的敌人流血（瞬发）") },
        { "높을수록 늦게 참", L("Higher = fills slower", "高いほど遅く溜まる", "越高积累越慢") },
        // v3.9 통일된 설명 · 적 스킬 이름
        { "평타를 휘두르면 적을 꿰뚫는 검기가 날아갑니다.", L("Each swing sends out a piercing sword wave.", "通常攻撃で敵を貫く剣気が飛びます。", "普攻挥剑时射出穿透剑气。") },
        { "평타로 벤 적 하나당 체력을 회복합니다. (한 번에 최대 3마리)", L("Heal for each enemy your swing hits. (up to 3 per swing)", "通常攻撃で斬った敵1体ごとに体力を回復します。(1回につき最大3体)", "普攻每命中一个敌人回复生命。（每次最多3个）") },
        { "우클릭 회전 베기를 모으는 동안 받는 피해가 줄어듭니다.", L("Take less damage while charging the right-click Spin Slash.", "右クリックの回転斬りを溜めている間、受けるダメージが減ります。", "蓄力右键回旋斩时受到的伤害降低。") },
        { "몇 번 벨 때마다 한 번은 더 멀리, 두 배로 벱니다.", L("Every few swings, one reaches farther and hits twice as hard.", "何回か斬るごとに1回、より遠くまで2倍の威力で斬ります。", "每挥砍几次，就有一次范围更远、伤害翻倍。") },
        { "회전 베기 뒤 칼바람이 몸을 감싸고 돌며 주변을 벱니다.", L("After Spin Slash, a storm of blades circles you and cuts nearby foes.", "回転斬りの後、刃の嵐が体を包み周囲を斬ります。", "回旋斩后刀刃风暴环绕自身斩击周围。") },
        { "표창이 적에 맞으면 가까운 다른 적에게 튕겨 날아갑니다.", L("Throwing stars bounce to another nearby enemy on hit.", "手裏剣が敵に当たると近くの別の敵へ跳ね返ります。", "飞镖命中后弹向附近另一个敌人。") },
        { "표창에 맞은 적이 3초 동안 출혈을 입습니다.", L("Enemies hit by throwing stars bleed for 3s.", "手裏剣が当たった敵が3秒間出血します。", "被飞镖命中的敌人流血3秒。") },
        { "출혈 돌진을 시작한 자리에 분신이 남아 표창을 던집니다.", L("A clone stays where Bleeding Dash began and throws stars.", "出血突進を始めた場所に分身が残り、手裏剣を投げます。", "在出血突进起点留下投掷飞镖的分身。") },
        { "출혈 중인 적에게 주는 피해가 늘어납니다.", L("Deal more damage to bleeding enemies.", "出血中の敵に与えるダメージが増えます。", "对流血中的敌人造成更多伤害。") },
        { "탄창이 비면 확률로 재장전 없이 절반을 되찾습니다.", L("When your magazine empties, you may recover half of it without reloading.", "弾倉が空になると、確率でリロードなしで半分を取り戻します。", "弹匣打空时有几率无需装填直接找回一半。") },
        { "적을 처치할 때마다 스킬 게이지가 찹니다. 공격력이 오를수록 더 많이 찹니다. (최대 4배)", L("Each kill fills the skill gauge. It fills more as your attack rises. (up to 4x)", "敵を倒すたびにスキルゲージが溜まります。攻撃力が上がるほど多く溜まります。(最大4倍)", "每次击杀都会充能技能槽，攻击力越高充得越多。（最多4倍）") },
        { "출혈 돌진이 끝나는 자리에서 표창이 사방으로 퍼집니다.", L("Throwing stars burst in all directions where Bleeding Dash ends.", "出血突進の終点で手裏剣が四方に飛び散ります。", "出血突进终点向四周射出飞镖。") },
        { "가득 당긴 화살이 처음 맞힌 적에게서 여러 갈래로 갈라집니다. (갈래마다 피해 40%)", L("Fully drawn arrows split on their first hit. (40% damage each)", "引き絞った矢が最初に当たった敵から複数に分かれます。(1本ごとにダメージ40%)", "满弓之箭在首次命中时分裂。（每支伤害40%）") },
        { "화살을 쏘면 잠시 뒤 유령 화살이 같은 방향으로 한 발 더 날아갑니다.", L("A ghost arrow follows each shot a moment later.", "矢を放つと少し遅れて幽霊の矢がもう一本飛びます。", "射箭后片刻，一支幽灵箭沿同一方向再射出。") },
        { "가만히 서서 당기면 시위를 더 빨리 가득 당깁니다.", L("Draw to full faster while standing still.", "立ち止まって引くと、より早く引き絞れます。", "站立不动时拉满弓更快。") },
        { "가득 당긴 화살에 맞은 적은 4초 동안 피해를 더 받습니다.", L("Enemies hit by a fully drawn arrow take more damage for 4s.", "引き絞った矢が当たった敵は4秒間、受けるダメージが増えます。", "被满弓之箭命中的敌人4秒内受到更多伤害。") },
        { "화살비가 떨어진 자리에 가시 덤불이 남아 적을 느리게 하고 찌릅니다.", L("Arrow Rain leaves thorns that slow and prick enemies.", "矢の雨の跡にいばらが残り、敵を遅くして刺します。", "箭雨落处留下荆棘，减速并刺伤敌人。") },
        { "빙결 시약이 적을 느리게 하는 대신 꽁꽁 얼립니다.", L("Frost reagent freezes enemies solid instead of slowing them.", "氷結試薬が敵を遅くする代わりに凍らせます。", "冰冻试剂不再减速，而是直接冻结敌人。") },
        { "작은 조수가 머리 위를 맴돌며 적에게 플라스크를 던집니다.", L("A tiny helper circles overhead and throws flasks at enemies.", "小さな助手が頭上を回り、敵にフラスコを投げます。", "小助手在头顶盘旋并向敌人投掷烧瓶。") },
        { "불타는 적에게 빙결 시약이 닿으면 증기 폭발이 일어납니다.", L("Frost reagent hitting a burning enemy causes a steam explosion.", "燃えている敵に氷結試薬が当たると蒸気爆発が起きます。", "冰冻试剂命中燃烧中的敌人会引发蒸汽爆炸。") },
        { "산성 웅덩이가 적을 40% 느리게 하고 더 오래 남습니다.", L("Acid puddles slow enemies by 40% and last longer.", "酸の水たまりが敵を40%遅くし、より長く残ります。", "酸液水洼使敌人减速40%并持续更久。") },
        { "대폭발 플라스크가 터지며 작은 플라스크들이 흩어져 다시 터집니다.", L("Big Blast Flask scatters small flasks that explode again.", "大爆発フラスコが弾け、小さなフラスコが散らばって再び爆発します。", "大爆炸烧瓶炸开后散出小烧瓶再次爆炸。") },
        { "검기 피해", L("Wave damage", "剣気ダメージ", "剑气伤害") },
        { "적 하나당 회복", L("Heal per enemy", "敵1体ごとの回復", "每个敌人回复") },
        { "투사체 베기", L("Cut projectiles", "弾斬り", "斩弹") },
        { "받는 피해", L("Damage taken", "受けるダメージ", "受到伤害") },
        { "강한 일격", L("Power strike", "強撃", "强力一击") },
        { "튕기는 횟수", L("Bounces", "跳ね返り回数", "弹射次数") },
        { "출혈 (초당)", L("Bleed (per sec)", "出血 (毎秒)", "流血（每秒）") },
        { "분신 지속", L("Clone duration", "分身の持続", "分身持续") },
        { "추가 피해", L("Bonus damage", "追加ダメージ", "额外伤害") },
        { "회수 확률", L("Recall chance", "回収確率", "回收几率") },
        { "처치당 게이지", L("Gauge per kill", "撃破ごとのゲージ", "每次击杀充能") },
        { "표창 수", L("Stars", "手裏剣の数", "飞镖数") },
        { "갈래 수", L("Splits", "分裂数", "分裂数") },
        { "유령 화살 피해", L("Ghost arrow damage", "幽霊の矢のダメージ", "幽灵箭伤害") },
        { "물러나는 거리", L("Leap distance", "下がる距離", "后撤距离") },
        { "당기는 속도", L("Draw speed", "引く速さ", "拉弓速度") },
        { "연쇄 폭발 피해", L("Chain blast damage", "連鎖爆発ダメージ", "连锁爆炸伤害") },
        { "얼리는 시간", L("Freeze time", "凍結時間", "冻结时间") },
        { "던지는 간격", L("Throw interval", "投げる間隔", "投掷间隔") },
        { "증기 폭발", L("Steam blast", "蒸気爆発", "蒸汽爆炸") },
        { "웅덩이 지속", L("Puddle duration", "水たまりの持続", "水洼持续") },
        { "파편 수", L("Shards", "破片の数", "碎片数") },
        { "코인 1개당 획득량", L("Coins per pickup", "コイン1枚あたりの獲得量", "每枚金币获得量") },
        { "게이지가 가득 차는 시간", L("Time to fill gauge", "ゲージが満タンになる時間", "技能槽充满时间") },
        { "스킬 중 시간 속도", L("Time speed during skill", "スキル中の時間の速さ", "技能期间时间速度") },
        { "경험치 배율", L("XP multiplier", "経験値倍率", "经验倍率") },
        { "끌어오는 범위", L("Pull range", "引き寄せ範囲", "吸引范围") },
        { "발사 수 · 한 발당 피해", L("Shots · damage per shot", "発射数 · 1発あたりのダメージ", "发射数 · 每发伤害") },
        { "넉백", L("Knockback", "ノックバック", "击退") },
        { "최대 체력", L("Max health", "最大体力", "最大生命") },
        { "받는 피해 감소", L("Damage reduction", "被ダメージ軽減", "伤害减免") },
        { "초당 회복", L("Regen per sec", "毎秒回復", "每秒回复") },
        { "처치당 회복", L("Heal per kill", "撃破ごとの回復", "每次击杀回复") },
        { "보급", L("Supplies", "補給", "补给") },
        { "체력 +30% · 코인 +10", L("Health +30% · Coins +10", "体力 +30% · コイン +10", "生命 +30% · 金币 +10") },
        { "고를 능력을 모두 배웠습니다.", L("You've learned every ability.", "選べる能力をすべて覚えました。", "已学会所有能力。") },
        { "공격력 ", L("Attack ", "攻撃力 ", "攻击力 ") },
        { "회", L("x", "回", "次") },
        { "개", L("", "個", "个") },
        { "갈래", L("", "本", "支") },
        { "번째마다", L("th swing", "回目ごと", "次一击") },
        { "번째마다 + 충격파", L("th swing + shockwave", "回目ごと + 衝撃波", "次一击 + 冲击波") },
        { "없음", L("None", "なし", "无") },
        { "한 번 더 고르면 진화합니다.", L("Pick it again to evolve it.", "もう一度選ぶと進化します。", "再选一次即可进化。") },
        { "뼈 가시", L("Bone Spikes", "骨の棘", "骨刺") },
        { "도약", L("Leap", "跳躍", "跳跃") },
        { "순간이동", L("Blink", "瞬間移動", "瞬移") },
        { "십자 광선", L("Cross Beam", "十字光線", "十字光线") },
        { "자폭", L("Self-Destruct", "自爆", "自爆") },
        { "덮치기", L("Pounce", "飛びかかり", "扑击") },
        { "지면 강타", L("Ground Slam", "地面強打", "重击地面") },
        { "회전 칼날", L("Blade Spin", "回転刃", "回旋刀刃") },
        { "산성 웅덩이", L("Acid Pool", "酸の水たまり", "酸液池") },
        { "꽃가루", L("Pollen", "花粉", "花粉") },
        { "버섯 지뢰", L("Mushroom Mines", "キノコ地雷", "蘑菇地雷") },
        { "울부짖음", L("Howl", "遠吠え", "嚎叫") },
        { "뿌리 가시", L("Root Spikes", "根の棘", "根刺") },
        // v3.8 패시브 · 레벨업 카드 · HUD
        { "기사의 맹세", L("Knight's Oath", "騎士の誓い", "骑士誓言") },
        { "체력이 가득 차 있는 동안 공격력이 20% 오릅니다.\n진화: +35%", L("+20% attack while at full health.\nEvolved: +35%", "体力が満タンの間、攻撃力が20%上がります。\n進化: +35%", "生命值满时攻击力提高20%。\n进化：+35%") },
        { "강철 갑옷", L("Plate Armor", "鋼の鎧", "钢铁铠甲") },
        { "받는 피해가 15% 줄지만 이동 속도가 5% 느려집니다.\n진화: 피해 -25%, 느려지지 않음", L("Take 15% less damage but move 5% slower.\nEvolved: -25% damage, no slowdown", "受けるダメージが15%減りますが、移動速度が5%遅くなります。\n進化: ダメージ-25%、遅くならない", "受到的伤害减少15%，但移动速度降低5%。\n进化：伤害-25%，不再减速") },
        { "그림자 은신", L("Shadow Veil", "影隠れ", "暗影隐匿") },
        { "3초 동안 맞지 않으면 다음 평타가 두 배로 아픕니다.\n진화: 2초, 2.5배", L("If you go 3s without being hit, your next basic attack deals double damage.\nEvolved: 2s, 2.5x", "3秒間攻撃を受けないと、次の通常攻撃が2倍のダメージになります。\n進化: 2秒、2.5倍", "3秒内未受伤，下一次普攻伤害翻倍。\n进化：2秒，2.5倍") },
        { "도망자의 발걸음", L("Fugitive's Stride", "逃亡者の足取り", "逃亡者之步") },
        { "맞으면 1.5초 동안 이동 속도가 40% 빨라집니다.\n진화: +60%", L("Getting hit grants +40% move speed for 1.5s.\nEvolved: +60%", "攻撃を受けると1.5秒間移動速度が40%上がります。\n進化: +60%", "受伤后1.5秒内移动速度提高40%。\n进化：+60%") },
        { "약점 간파", L("Weak Spot", "弱点看破", "看破弱点") },
        { "체력이 가득한 적에게 주는 피해가 50% 늘어납니다.\n진화: +100%", L("Deal 50% more damage to enemies at full health.\nEvolved: +100%", "体力が満タンの敵に与えるダメージが50%増えます。\n進化: +100%", "对满血敌人造成的伤害提高50%。\n进化：+100%") },
        { "사냥 본능", L("Hunting Instinct", "狩猟本能", "狩猎本能") },
        { "적을 20마리 처치할 때마다 다음 화살 3발이 저절로 가득 당겨집니다.\n진화: 12마리마다", L("Every 20 kills, your next 3 arrows are drawn to full instantly.\nEvolved: every 12 kills", "敵を20体倒すたびに、次の矢3本が自動で引き絞られます。\n進化: 12体ごと", "每击杀20个敌人，接下来3支箭自动拉满。\n进化：每12个") },
        { "비상 물약", L("Emergency Potion", "非常用ポーション", "应急药水") },
        { "체력이 25% 아래로 떨어지면 체력 30%를 곧바로 회복합니다. (쿨타임 45초)\n진화: 쿨타임 30초", L("When health drops below 25%, instantly heal 30%. (45s cooldown)\nEvolved: 30s cooldown", "体力が25%を下回ると、すぐに体力を30%回復します。(クールタイム45秒)\n進化: クールタイム30秒", "生命值低于25%时立即恢复30%生命。（冷却45秒）\n进化：冷却30秒") },
        { "금속 변환", L("Transmute Gold", "金属変換", "点石成金") },
        { "적을 처치하면 10% 확률로 적이 금으로 변해 코인 3개를 줍니다.\n진화: 20%", L("Kills have a 10% chance to turn the enemy into gold worth 3 coins.\nEvolved: 20%", "敵を倒すと10%の確率で敵が金に変わり、コイン3枚を得ます。\n進化: 20%", "击杀时有10%几率将敌人变成黄金，获得3枚金币。\n进化：20%") },
        { "굳건한 자세", L("Steadfast Stance", "不動の構え", "坚定架势") },
        { "연속 베기", L("Combo Slash", "連続斬り", "连斩") },
        { "급소 노리기", L("Go for the Vitals", "急所狙い", "直取要害") },
        { "표창 회수", L("Star Recall", "手裏剣回収", "回收飞镖") },
        { "정조준", L("Steady Aim", "精密照準", "稳定瞄准") },
        { "사냥감 표식", L("Quarry Mark", "獲物の印", "猎物标记") },
        { "원소 융합", L("Elemental Fusion", "元素融合", "元素融合") },
        { "끈적한 산성", L("Sticky Acid", "粘つく酸", "黏稠酸液") },
        { "비상 보급", L("Emergency Supplies", "非常補給", "紧急补给") },
        { "고를 능력을 모두 배웠습니다.\n체력 30%를 회복하고 코인 10개를 얻습니다.", L("You've learned every ability.\nHeal 30% health and gain 10 coins.", "選べる能力をすべて覚えました。\n体力30%を回復し、コイン10枚を得ます。", "已学会所有能力。\n恢复30%生命并获得10枚金币。") },
        { "장전", L("Reload", "装填", "装填") },
        { "회수", L("Return", "回収", "回收") },
        { "사용 중", L("In use", "使用中", "使用中") },
        { "[{SWAP}]로 꺼내기", L("[{SWAP}] to equip", "[{SWAP}]で持ち替え", "按[{SWAP}]切换") },
        { "쿨타임 ", L("Cooldown ", "クールタイム ", "冷却 ") },
        { "사용 가능", L("Ready", "使用可能", "可以使用") },
        { "번 남음", L(" left", "回残り", "次剩余") },
        { "이번 판에 다 씀", L("Used up this run", "今回は使い切った", "本局已用完") },
        { "수호 영혼 ", L("Guardian souls ", "守護の魂 ", "守护灵魂 ") },
        { " (진화)", L(" (Evolved)", " (進化)", "（进化）") },
        { "지금 공격력 +", L("Attack now +", "現在の攻撃力 +", "当前攻击力 +") },
        { "중첩 ", L("Stacks ", "スタック ", "叠层 ") },
        { " · 공격 속도 +", L(" · Attack speed +", " · 攻撃速度 +", " · 攻击速度 +") },
        { "질주 중", L("Sprinting", "疾走中", "疾驰中") },
        { "최대 체력 +", L("Max health +", "最大体力 +", "最大生命 +") },
        { "발동 중 (주변에 적 없음)", L("Active (no enemies nearby)", "発動中 (周囲に敵なし)", "生效中（附近没有敌人）") },
        { "꺼짐 (5칸 안에 적)", L("Off (enemy within 5 tiles)", "オフ (5マス以内に敵)", "未生效（5格内有敌人）") },
        { "발동 중 (체력 가득)", L("Active (full health)", "発動中 (体力満タン)", "生效中（满血）") },
        { "꺼짐 (체력이 가득해야 함)", L("Off (needs full health)", "オフ (体力満タンが必要)", "未生效（需要满血）") },
        { "준비됨 · 다음 평타 강화", L("Ready · next attack empowered", "準備完了 · 次の通常攻撃強化", "已就绪 · 下次普攻强化") },
        { "빨라짐", L("Hasted", "加速中", "加速中") },
        { "자동 만궁 ", L("Auto full draw ", "自動フルドロー ", "自动满弓 ") },
        { "발 남음", L(" left", "本残り", "支剩余") },
        { "초 뒤 준비", L("s until ready", "秒後に準備", "秒后就绪") },
        { "준비됨", L("Ready", "準備完了", "已就绪") },
        { "사냥 본능!", L("Hunting Instinct!", "狩猟本能！", "狩猎本能！") },
        { "비상 물약!", L("Emergency Potion!", "非常用ポーション！", "应急药水！") },
        // v3.5 캐릭터 특수 능력 (검사 · 도적 · 궁수 · 연금술사)
        { "전쟁 망치", L("War Hammer", "ウォーハンマー", "战锤") },
        { "가까운 땅을 내리찍어 주변 적에게 피해를 주고 잠깐 기절시킵니다. (공격력 250%)\n진화: 범위 증가, 기절 두 배", L("Smash the ground nearby, damaging and briefly stunning enemies. (250% attack)\nEvolved: larger area, double stun", "近くの地面を叩きつけ、周囲の敵にダメージを与えて少し気絶させます。(攻撃力250%)\n進化: 範囲拡大、気絶2倍", "猛砸附近地面，伤害并短暂击晕周围敌人。（攻击力250%）\n进化：范围扩大，击晕翻倍") },
        { "채찍검", L("Whip Sword", "蛇腹剣", "鞭剑") },
        { "길게 휘어지는 칼날 채찍. 끝부분에 맞은 적은 두 배 가까운 피해를 받습니다.\n진화: 더 길고, 끝 피해 증가", L("A long, bending blade whip. Enemies hit by the tip take nearly double damage.\nEvolved: longer, stronger tip", "長くしなる刃の鞭。先端に当たった敵は約2倍のダメージを受けます。\n進化: より長く、先端ダメージ増加", "修长弯曲的刃鞭，鞭梢命中的敌人受到近两倍伤害。\n进化：更长，鞭梢伤害提高") },
        { "기창", L("Knight's Lance", "騎槍", "骑枪") },
        { "창을 앞세워 짧게 돌격하며 지나간 적을 찌르고 밀쳐냅니다. (공격력 180%)\n진화: 더 멀리, 돌격 중 무적", L("Charge a short distance lance-first, piercing and shoving enemies aside. (180% attack)\nEvolved: farther, invincible while charging", "槍を構えて短く突進し、通り道の敵を突いて押しのけます。(攻撃力180%)\n進化: より遠く、突進中無敵", "持枪短距冲锋，刺穿并推开沿途敌人。（攻击力180%）\n进化：更远，冲锋时无敌") },
        { "전투 함성", L("War Cry", "雄叫び", "战吼") },
        { "크게 외쳐 주변 적을 밀쳐내고 6초 동안 공격력이 40% 오릅니다.\n진화: 공격력 +60%", L("Roar to push nearby enemies away and gain +40% attack for 6s.\nEvolved: +60% attack", "雄叫びで周囲の敵を押しのけ、6秒間攻撃力が40%上がります。\n進化: 攻撃力+60%", "怒吼震退周围敌人，6秒内攻击力提高40%。\n进化：攻击力+60%") },
        { "심판의 대검", L("Judgment Blade", "審判の大剣", "审判巨剑") },
        { "마우스 위치에 하늘에서 거대한 검이 떨어져 크게 베고 기절시킵니다. (공격력 800%)\n진화: 대검 세 자루", L("A giant sword falls from the sky at the cursor, cleaving and stunning. (800% attack)\nEvolved: three swords", "マウス位置に空から巨大な剣が落ち、大きく斬って気絶させます。(攻撃力800%)\n進化: 大剣3本", "巨剑从天而降落在鼠标位置，重斩并击晕。（攻击力800%）\n进化：三把巨剑") },
        { "마우스 쪽으로 땅을 길게 갈라 한 줄의 적에게 피해를 주고 느리게 만듭니다. (공격력 300%)\n진화: 세 갈래로 갈라짐", L("Split the earth toward the cursor, damaging and slowing a line of enemies. (300% attack)\nEvolved: splits three ways", "マウス方向に大地を長く裂き、一列の敵にダメージを与えて遅くします。(攻撃力300%)\n進化: 3方向に裂ける", "朝鼠标方向劈开大地，伤害并减速一列敌人。（攻击力300%）\n进化：分裂成三道") },
        { "불굴", L("Unyielding", "不屈", "不屈") },
        { "잃은 체력이 많을수록 공격력이 오릅니다. (최대 +50%)\n진화: 최대 +80%", L("The more health you've lost, the higher your attack. (up to +50%)\nEvolved: up to +80%", "失った体力が多いほど攻撃力が上がります。(最大+50%)\n進化: 最大+80%", "损失的生命越多，攻击力越高。（最多+50%）\n进化：最多+80%") },
        { "전투 열기", L("Battle Fervor", "戦いの熱気", "战斗狂热") },
        { "적을 처치할 때마다 4초 동안 공격 속도 +6% (최대 5중첩).\n진화: +8%, 최대 8중첩", L("Each kill grants +6% attack speed for 4s (up to 5 stacks).\nEvolved: +8%, up to 8 stacks", "敵を倒すたびに4秒間攻撃速度+6%(最大5重)。\n進化: +8%、最大8重", "每次击杀4秒内攻击速度+6%（最多叠5层）。\n进化：+8%，最多8层") },
        { "독침 대롱", L("Blowgun", "吹き矢", "吹箭筒") },
        { "누르고 있으면 독침을 빠르게 붑니다. 맞은 적은 중독이 쌓입니다. (최대 5중첩)\n진화: 최대 10중첩", L("Hold to rapidly blow poison darts. Hits stack poison. (up to 5)\nEvolved: up to 10 stacks", "押し続けると毒針を素早く吹きます。当たった敵に毒が蓄積します。(最大5重)\n進化: 最大10重", "按住快速吹出毒针，命中叠加中毒。（最多5层）\n进化：最多10层") },
        { "도박 카드", L("Trick Cards", "ギャンブルカード", "赌徒卡牌") },
        { "카드 세 장을 던집니다. 카드마다 피해가 제각각이고, 가끔 조커가 터집니다.\n진화: 다섯 장, 조커 확률 두 배", L("Throw three cards with random damage. Sometimes a Joker explodes.\nEvolved: five cards, double Joker chance", "カードを3枚投げます。ダメージはカードごとにばらばらで、たまにジョーカーが爆発します。\n進化: 5枚、ジョーカー確率2倍", "掷出三张伤害随机的卡牌，偶尔会有爆炸的小丑牌。\n进化：五张，小丑牌几率翻倍") },
        { "살상 와이어", L("Razor Wire", "殺傷ワイヤー", "杀伤钢丝") },
        { "클릭한 곳에 와이어 고리를 박습니다. 고리를 잇는 줄에 닿은 적은 계속 베입니다. (고리 3개)\n진화: 고리 5개", L("Click to plant wire anchors. Enemies touching the wires between them keep getting cut. (3 anchors)\nEvolved: 5 anchors", "クリックした場所にワイヤーの杭を打ちます。杭をつなぐ糸に触れた敵は斬られ続けます。(杭3本)\n進化: 杭5本", "在点击处钉下钢丝锚点，碰到锚点间钢丝的敌人会被持续切割。（3个锚点）\n进化：5个锚点") },
        { "죽음의 표식", L("Death Mark", "死の刻印", "死亡印记") },
        { "마우스 근처의 적에게 표식. 3초 뒤 큰 피해로 터집니다. 그 전에 쓰러지면 쿨타임 초기화. (공격력 1000%)\n진화: 표식 세 개", L("Mark the enemy near the cursor; it bursts for huge damage after 3s. If it dies first, the cooldown resets. (1000% attack)\nEvolved: three marks", "マウス近くの敵に刻印。3秒後に大ダメージで弾けます。先に倒れるとクールタイムがリセット。(攻撃力1000%)\n進化: 刻印3つ", "给鼠标附近的敌人打上印记，3秒后爆发巨额伤害；若目标提前倒下则重置冷却。（攻击力1000%）\n进化：三个印记") },
        { "마름쇠", L("Caltrops", "撒菱", "铁蒺藜") },
        { "주변에 마름쇠를 흩뿌립니다. 밟은 적은 피해를 입고 느려집니다.\n진화: 마름쇠 두 배", L("Scatter caltrops around you. Enemies that step on them are hurt and slowed.\nEvolved: double caltrops", "周囲に撒菱をばらまきます。踏んだ敵はダメージを受けて遅くなります。\n進化: 撒菱2倍", "在周围撒下铁蒺藜，踩中的敌人受伤并减速。\n进化：铁蒺藜翻倍") },
        { "소매치기", L("Pickpocket", "スリ", "扒窃") },
        { "순식간에 주변 적들 사이를 누비며 벱니다. 털린 적은 쓰러질 때 코인을 더 떨어뜨립니다.\n진화: 더 많은 적, 코인 두 배", L("Dart between nearby enemies in an instant, cutting each. Robbed enemies drop extra coins when they fall.\nEvolved: more enemies, double coins", "一瞬で周囲の敵の間を駆け抜けて斬ります。盗まれた敵は倒れるとコインを多く落とします。\n進化: より多くの敵、コイン2倍", "瞬间穿梭于周围敌人之间逐一斩击，被扒窃的敌人倒下时掉落更多金币。\n进化：更多敌人，金币翻倍") },
        { "회피 본능", L("Evasion", "回避本能", "闪避本能") },
        { "받는 공격을 20% 확률로 피합니다.\n진화: 30%", L("20% chance to dodge incoming attacks.\nEvolved: 30%", "受ける攻撃を20%の確率で回避します。\n進化: 30%", "有20%几率闪避受到的攻击。\n进化：30%") },
        { "연쇄 처치", L("Killing Spree", "連続キル", "连杀") },
        { "적을 처치하면 2초 동안 이동 속도 +20%, 모든 스킬 쿨타임 0.3초 감소.\n진화: 쿨타임 0.6초 감소", L("Kills grant +20% move speed for 2s and cut all skill cooldowns by 0.3s.\nEvolved: 0.6s", "敵を倒すと2秒間移動速度+20%、全スキルのクールタイム0.3秒短縮。\n進化: 0.6秒短縮", "击杀后2秒内移动速度+20%，所有技能冷却减少0.3秒。\n进化：减少0.6秒") },
        { "그물 활", L("Net Bow", "網弓", "网弓") },
        { "맞은 자리에 그물이 펼쳐져 주변 적을 묶습니다.\n진화: 그물이 더 넓고 오래", L("A net bursts open where the arrow hits, binding nearby enemies.\nEvolved: wider, longer net", "当たった場所に網が広がり、周囲の敵を縛ります。\n進化: 網がより広く長く", "命中处张开大网，束缚周围敌人。\n进化：网更大更久") },
        { "투창", L("Javelin", "投げ槍", "标枪") },
        { "모든 적을 꿰뚫는 무거운 창. 멀리 날아갈수록 피해가 커집니다. (최대 공격력 300%)\n진화: 최대 400%", L("A heavy javelin that pierces everything. Deals more damage the farther it flies. (up to 300% attack)\nEvolved: up to 400%", "すべての敵を貫く重い槍。遠くへ飛ぶほどダメージが増えます。(最大攻撃力300%)\n進化: 最大400%", "贯穿所有敌人的重标枪，飞得越远伤害越高。（最高攻击力300%）\n进化：最高400%") },
        { "속사 활", L("Burst Bow", "速射弓", "速射弓") },
        { "한 번 누르면 화살 세 발을 눈 깜짝할 새 연달아 쏩니다. (발당 공격력 70%)\n진화: 다섯 발", L("Each click fires three arrows in a lightning-fast burst. (70% attack each)\nEvolved: five arrows", "一度押すと矢を3本、瞬く間に連射します。(1本あたり攻撃力70%)\n進化: 5本", "每次点击瞬间连射三箭。（每箭攻击力70%）\n进化：五箭") },
        { "매의 급습", L("Falcon Dive", "鷹の急襲", "猎鹰突袭") },
        { "사냥 매를 날려 마우스 근처의 적을 차례로 덮칩니다. (적마다 공격력 250%)\n진화: 더 많은 적", L("Send your falcon to swoop on enemies near the cursor one after another. (250% attack each)\nEvolved: more enemies", "狩りの鷹を放ち、マウス近くの敵を次々に襲います。(敵ごとに攻撃力250%)\n進化: より多くの敵", "放出猎鹰依次扑击鼠标附近的敌人。（每个敌人攻击力250%）\n进化：更多敌人") },
        { "돌풍 화살", L("Gale Arrow", "突風の矢", "疾风之箭") },
        { "거센 바람을 두른 거대한 화살. 한 줄을 꿰뚫고 적을 멀리 날려 버립니다. (공격력 300%)\n진화: 화살이 두 배 커짐", L("A giant arrow wrapped in gale winds that pierces a line and blasts enemies away. (300% attack)\nEvolved: arrow twice as big", "強風をまとった巨大な矢。一列を貫き、敵を遠くへ吹き飛ばします。(攻撃力300%)\n進化: 矢が2倍に", "裹挟狂风的巨箭，贯穿一列并把敌人吹飞。（攻击力300%）\n进化：箭矢变为两倍大") },
        { "사냥꾼의 집중", L("Hunter's Focus", "狩人の集中", "猎人专注") },
        { "5초 동안 활시위를 순식간에 가득 당깁니다.\n진화: 8초", L("For 5s, your bow draws to full instantly.\nEvolved: 8s", "5秒間、弓を一瞬で引き絞ります。\n進化: 8秒", "5秒内瞬间拉满弓弦。\n进化：8秒") },
        { "전리품 사냥", L("Trophy Hunter", "戦利品狩り", "战利品猎人") },
        { "적을 처치할 때마다 최대 체력 +0.5 (최대 +40).\n진화: +1 (최대 +80)", L("Each kill grants +0.5 max health (up to +40).\nEvolved: +1 (up to +80)", "敵を倒すたびに最大体力+0.5(最大+40)。\n進化: +1(最大+80)", "每次击杀最大生命+0.5（最多+40）。\n进化：+1（最多+80）") },
        { "거리 유지", L("Keep Distance", "間合い", "保持距离") },
        { "5칸 안에 적이 없으면 공격력이 30% 오릅니다.\n진화: +50%", L("+30% attack while no enemy is within 5 tiles.\nEvolved: +50%", "5マス以内に敵がいないと攻撃力が30%上がります。\n進化: +50%", "5格内没有敌人时攻击力提高30%。\n进化：+50%") },
        { "수은 구슬", L("Quicksilver Orb", "水銀玉", "水银珠") },
        { "벽과 적에게 튕겨 다니는 수은 구슬. 네 번 튕기면 터집니다.\n진화: 일곱 번 튕김", L("A quicksilver orb that bounces off walls and enemies, bursting after four bounces.\nEvolved: seven bounces", "壁と敵に跳ね返る水銀の玉。4回跳ねると弾けます。\n進化: 7回跳ねる", "在墙壁与敌人间弹跳的水银珠，弹跳四次后爆裂。\n进化：弹跳七次") },
        { "자석 폭탄", L("Magnet Bomb", "磁石爆弾", "磁力炸弹") },
        { "떨어진 자리로 주변 적을 끌어모은 뒤 폭발합니다. (공격력 220%)\n진화: 더 넓게 끌어당기고 두 번 폭발", L("Pulls nearby enemies to where it lands, then explodes. (220% attack)\nEvolved: wider pull, explodes twice", "落ちた場所に周囲の敵を引き寄せてから爆発します。(攻撃力220%)\n進化: より広く引き寄せ2回爆発", "把周围敌人吸到落点后爆炸。（攻击力220%）\n进化：吸引范围更大，爆炸两次") },
        { "폭죽 발사기", L("Firework Launcher", "花火ランチャー", "烟花发射器") },
        { "마우스 위치로 폭죽을 쏘아 올려 색색의 불꽃으로 터뜨립니다.\n진화: 불꽃 다섯 → 여덟 갈래", L("Launch a firework at the cursor that bursts into colorful sparks.\nEvolved: 5 → 8 bursts", "マウス位置に花火を打ち上げ、色とりどりの火花で弾けさせます。\n進化: 火花5 → 8つ", "向鼠标位置发射烟花，绽放成五彩火花。\n进化：火花五道 → 八道") },
        { "현자의 돌", L("Philosopher's Stone", "賢者の石", "贤者之石") },
        { "6초 동안 던지는 플라스크가 모두 불안정해져 크게 폭발합니다.\n진화: 9초", L("For 6s, every flask you throw is unstable and explodes big.\nEvolved: 9s", "6秒間、投げるフラスコがすべて不安定になり大爆発します。\n進化: 9秒", "6秒内投掷的烧瓶全部变得不稳定并猛烈爆炸。\n进化：9秒") },
        { "시간 역행 물약", L("Rewind Elixir", "時間逆行の薬", "时光倒流药剂") },
        { "3초 전의 자리로 되돌아가고, 그때 체력이 더 많았다면 되찾습니다.\n진화: 쿨타임 감소", L("Return to where you were 3s ago, and regain your health from then if it was higher.\nEvolved: shorter cooldown", "3秒前の場所に戻り、そのとき体力が多ければ取り戻します。\n進化: クールタイム短縮", "回到3秒前的位置，若当时生命更多则一并恢复。\n进化：冷却缩短") },
        { "거대화 물약", L("Giant Potion", "巨大化の薬", "巨大化药剂") },
        { "5초 동안 몸이 커져 받는 피해가 절반, 닿는 적을 밀쳐내며 피해를 줍니다.\n진화: 8초", L("Grow huge for 5s: take half damage and shove and hurt enemies you touch.\nEvolved: 8s", "5秒間体が大きくなり、受けるダメージが半分、触れた敵を押しのけてダメージを与えます。\n進化: 8秒", "5秒内体型变大，受到伤害减半，并推开、伤害接触的敌人。\n进化：8秒") },
        { "연금 순환", L("Alchemic Cycle", "錬金循環", "炼金循环") },
        { "스킬을 쓸 때마다 체력 5% 회복, 다른 스킬 쿨타임 1초 감소.\n진화: 체력 8%, 2초 감소", L("Each skill use heals 5% health and cuts other skill cooldowns by 1s.\nEvolved: 8% health, 2s", "スキルを使うたびに体力5%回復、他のスキルのクールタイム1秒短縮。\n進化: 体力8%、2秒短縮", "每次使用技能恢复5%生命，其他技能冷却减少1秒。\n进化：生命8%，减少2秒") },
        { "불안정 연구", L("Volatile Research", "不安定研究", "不稳定研究") },
        { "불안정한 플라스크가 나올 확률이 15% → 35%, 불안정 폭발이 불을 붙입니다.\n진화: 50%", L("Unstable flask chance 15% → 35%, and unstable blasts set enemies on fire.\nEvolved: 50%", "不安定なフラスコが出る確率が15% → 35%、不安定な爆発が炎上させます。\n進化: 50%", "不稳定烧瓶出现几率15% → 35%，不稳定爆炸会点燃敌人。\n进化：50%") },
        { "대지 진동", L("Earthquake", "大地震動", "大地震荡") },
        { "망치로 땅을 연달아 내리쳐 앞으로 나아가는 충격파 여섯 번을 일으킵니다. (공격력 300%씩, 기절)", L("Pound the ground again and again, sending six shockwaves marching forward. (300% attack each, stun)", "槌で地面を連打し、前へ進む衝撃波を6回起こします。(攻撃力300%ずつ、気絶)", "连续锤击地面，向前推进六道冲击波。（每道攻击力300%，击晕）") },
        { "뱀의 춤", L("Serpent Dance", "蛇の舞", "蛇之舞") },
        { "채찍검을 사방 열두 방향으로 휘몰아칩니다. (공격력 200%씩)", L("Lash the whip sword in twelve directions. (200% attack each)", "蛇腹剣を四方12方向に振り回します。(攻撃力200%ずつ)", "向十二个方向狂舞鞭剑。（每道攻击力200%）") },
        { "기사 돌격", L("Knight's Charge", "騎士突撃", "骑士冲锋") },
        { "무적 상태로 멀리 돌격해 지나간 적을 모두 날려 버립니다. (공격력 700%)", L("Charge far while invincible, sending everything in your path flying. (700% attack)", "無敵状態で遠くまで突撃し、通り道の敵をすべて吹き飛ばします。(攻撃力700%)", "无敌状态下远距离冲锋，撞飞沿途所有敌人。（攻击力700%）") },
        { "독안개", L("Toxic Fog", "毒霧", "毒雾") },
        { "마우스 위치에 5초 동안 독안개를 퍼뜨려 안의 적에게 중독을 계속 쌓습니다.", L("Spread toxic fog at the cursor for 5s, stacking poison on enemies inside.", "マウス位置に5秒間毒霧を広げ、中の敵に毒を蓄積し続けます。", "在鼠标位置散布毒雾5秒，持续为其中敌人叠加中毒。") },
        { "잭팟", L("Jackpot", "ジャックポット", "头奖") },
        { "카드 52장을 소용돌이치듯 사방으로 뿌립니다. 조커도 잔뜩 섞여 있습니다.", L("Spiral 52 cards out in every direction, with plenty of Jokers mixed in.", "カード52枚を渦巻くように四方へばらまきます。ジョーカーもたっぷり。", "螺旋般向四周撒出52张卡牌，其中混着大量小丑牌。") },
        { "거미줄 감옥", L("Web Prison", "蜘蛛の檻", "蛛网牢笼") },
        { "주변을 와이어로 둘러싼 뒤 조여 들어가며 닿는 적을 벱니다.", L("Surround yourself with wire, then tighten it, cutting every enemy it touches.", "周囲をワイヤーで囲み、締め上げながら触れた敵を斬ります。", "用钢丝环绕四周，再收紧切割触及的敌人。") },
        { "대형 그물", L("Great Net", "大網", "巨网") },
        { "마우스 위치에 거대한 그물을 던져 3초 동안 모두 묶고 피해를 줍니다. (공격력 300%)", L("Throw a huge net at the cursor, binding and damaging everything for 3s. (300% attack)", "マウス位置に巨大な網を投げ、3秒間すべてを縛ってダメージを与えます。(攻撃力300%)", "向鼠标位置抛出巨网，束缚并伤害所有敌人3秒。（攻击力300%）") },
        { "창의 벽", L("Wall of Spears", "槍の壁", "枪之墙") },
        { "투창 아홉 자루를 한 줄로 늘어세워 한꺼번에 던집니다. (공격력 400%씩)", L("Line up nine javelins and hurl them all at once. (400% attack each)", "投げ槍9本を一列に並べて一斉に投げます。(攻撃力400%ずつ)", "将九支标枪排成一列同时掷出。（每支攻击力400%）") },
        { "천 개의 화살", L("Thousand Arrows", "千本の矢", "千箭") },
        { "3초 동안 가까운 적들을 자동으로 겨눠 화살을 퍼붓습니다.", L("For 3s, automatically aim at nearby enemies and unleash a torrent of arrows.", "3秒間、近くの敵を自動で狙って矢を浴びせます。", "3秒内自动瞄准附近敌人倾泻箭雨。") },
        { "수은 폭풍", L("Quicksilver Storm", "水銀の嵐", "水银风暴") },
        { "수은 구슬 열여섯 개를 사방으로 튕겨 보냅니다.", L("Send sixteen quicksilver orbs bouncing in every direction.", "水銀玉16個を四方へ跳ね飛ばします。", "向四周弹射十六颗水银珠。") },
        { "블랙홀 플라스크", L("Black Hole Flask", "ブラックホールフラスコ", "黑洞烧瓶") },
        { "마우스 위치에 3초 동안 모든 것을 빨아들이는 소용돌이를 만든 뒤 크게 폭발합니다. (공격력 800%)", L("Create a vortex at the cursor that sucks everything in for 3s, then detonates. (800% attack)", "マウス位置に3秒間すべてを吸い込む渦を作り、大爆発します。(攻撃力800%)", "在鼠标位置制造吞噬一切的漩涡3秒，然后猛烈爆炸。（攻击力800%）") },
        { "불꽃 축제", L("Firework Festival", "花火大会", "烟花盛典") },
        { "3초 동안 적들 머리 위로 폭죽 스무 발을 터뜨립니다.", L("Burst twenty fireworks over enemies' heads for 3s.", "3秒間、敵の頭上で花火を20発打ち上げます。", "3秒内在敌人头顶绽放二十发烟花。") },
        { "와이어", L("Wire", "ワイヤー", "钢丝") },
        { "전투 함성!", L("War Cry!", "雄叫び！", "战吼！") },
        { "집중!", L("Focus!", "集中！", "专注！") },
        { "현자의 돌!", L("Philosopher's Stone!", "賢者の石！", "贤者之石！") },
        { "시간 역행!", L("Rewind!", "時間逆行！", "时光倒流！") },
        { "표식 초기화!", L("Mark reset!", "刻印リセット！", "印记重置！") },
        { "회피!", L("Dodge!", "回避！", "闪避！") },
        // v3.5 캐릭터 전용 레벨업 카드 (특수 능력)
        { "사냥의 기세", L("Hunter's Momentum", "狩りの勢い", "狩猎气势") },
        { "날아가는 검기", L("Flying Slash", "飛ぶ剣気", "飞行剑气") },
        { "흡혈 베기", L("Vampiric Slash", "吸血斬り", "吸血斩") },
        { "쳐내기", L("Deflect", "弾き返し", "格挡") },
        { "평타를 휘두르면 범위 안의 적 투사체를 베어 없앱니다.", L("Your swing cuts down enemy projectiles in its arc.", "通常攻撃の範囲内の敵の弾を斬り払います。", "普攻挥剑时斩灭范围内的敌方弹幕。") },
        { "칼바람", L("Blade Storm", "刃の嵐", "刀刃风暴") },
        { "도탄 표창", L("Ricochet Stars", "跳弾手裏剣", "弹射飞镖") },
        { "갈고리 표창", L("Barbed Stars", "かぎ爪手裏剣", "倒钩飞镖") },
        { "그림자 분신", L("Shadow Clone", "影分身", "影分身") },
        { "표창 폭풍", L("Star Storm", "手裏剣の嵐", "飞镖风暴") },
        { "분열 화살", L("Splitting Arrow", "分裂の矢", "分裂箭") },
        { "메아리 화살", L("Echo Arrow", "こだまの矢", "回响之箭") },
        { "바람 걸음", L("Wind Step", "風の歩み", "风之步") },
        { "가득 당긴 화살을 쏘면 반동으로 뒤로 휙 물러납니다.", L("Firing a fully drawn arrow springs you backward.", "引き絞った矢を放つと反動で後ろへ跳びます。", "射出满弓之箭时借反冲向后跃开。") },
        { "가시 덤불", L("Thorn Thicket", "いばらの茂み", "荆棘丛") },
        { "연쇄 반응", L("Chain Reaction", "連鎖反応", "连锁反应") },
        { "플라스크 폭발로 쓰러진 적이 그 자리에서 한 번 더 터집니다.", L("Enemies killed by flask blasts explode once more.", "フラスコの爆発で倒れた敵がその場でもう一度爆発します。", "被烧瓶爆炸击杀的敌人会再次爆炸。") },
        { "급속 냉동", L("Flash Freeze", "急速冷凍", "急速冷冻") },
        { "호문쿨루스", L("Homunculus", "ホムンクルス", "人造小人") },
        { "파편 플라스크", L("Shrapnel Flask", "破片フラスコ", "碎片烧瓶") },
        { "현재 ", L("Current ", "現在 ", "当前 ") },
        { "영혼을 지켜 세상을 구한 자 — Soul Saver.", L("The one who saved the world's souls — Soul Saver.", "魂を守り世界を救った者 — Soul Saver。", "守护灵魂、拯救世界之人 — Soul Saver。") },
        // v3.3 캐릭터별 상점 업그레이드
        { "총알 공격력", L("Bullet Damage", "弾の攻撃力", "子弹攻击力") },
        { "장검 공격력", L("Longsword Damage", "長剣の攻撃力", "长剑攻击力") },
        { "표창 공격력", L("Throwing Star Damage", "手裏剣の攻撃力", "飞镖攻击力") },
        { "화살 공격력", L("Arrow Damage", "矢の攻撃力", "箭矢攻击力") },
        { "플라스크 공격력", L("Flask Damage", "フラスコの攻撃力", "烧瓶攻击力") },
        { "베기 사거리", L("Slash Reach", "斬撃の射程", "斩击射程") },
        { "베기 각도", L("Slash Angle", "斬撃の角度", "斩击角度") },
        { "회전 베기 위력", L("Spin Slash Power", "回転斬りの威力", "回旋斩威力") },
        { "관통력", L("Piercing", "貫通力", "穿透力") },
        { "화살비 위력", L("Arrow Rain Power", "矢の雨の威力", "箭雨威力") },
        { "대폭발 위력", L("Mega Blast Power", "大爆発の威力", "大爆炸威力") },
        { "투척 속도", L("Throw Speed", "投擲速度", "投掷速度") },
        { "연사 속도", L("Fire Rate", "連射速度", "连射速度") },
        { "표창 회수 속도", L("Star Recovery Speed", "手裏剣の回収速度", "飞镖回收速度") },
        { "표창 주머니", L("Star Pouch", "手裏剣袋", "飞镖袋") },
        { "적 ", L("", "敵 ", "敌人 ") },
        // v3.3 도감 캐릭터 · 전용 무기 궁극기
        { "메인 메뉴의 캐릭터에서 고릅니다 · 잠긴 캐릭터는 포인트로 해금하면 정보가 보입니다", L("Choose in Characters on the main menu · Locked characters are revealed once unlocked with points", "メインメニューのキャラクターで選択 · ロック中のキャラクターはポイントで解放すると情報が表示されます", "在主菜单的角色中选择 · 未解锁角色用点数解锁后才会显示信息") },
        { "모든 캐릭터", L("All characters", "全キャラクター", "所有角色") },
        { "전용", L("only", "専用", "专属") },
        { "전용 무기", L("Exclusive weapons", "専用武器", "专属武器") },
        { "효과 범위", L("Area", "効果範囲", "效果范围") },
        { "공격 속도 · 재장전 · 탄창 대신 무기에 맞는 강화가 나옵니다.", L("Weapon-specific upgrades replace attack speed, reload and magazine.", "攻撃速度・リロード・弾倉の代わりに、武器に合った強化が並びます。", "以适合武器的强化取代攻击速度、装填与弹匣。") },
        { "대지 가르기", L("Earth Splitter", "大地裂き", "裂地斩") },
        // v3.3 궁수 활 시위 · 연금술사 시약
        { "누르고 있으면 시위를 당기고, 떼면 발사. 오래 당길수록 강하고 빠른 화살", L("Hold to draw the bowstring, release to fire. The longer you draw, the stronger and faster the arrow", "押し続けると弦を引き、離すと発射。長く引くほど強く速い矢", "按住拉弓，松开射出。拉得越久，箭越强越快") },
        { "화염 · 빙결 · 산성 시약을 번갈아 채운 플라스크. 가끔 불안정한 플라스크가 크게 폭발", L("Flasks filled with fire, frost and acid reagents in turn. Now and then an unstable flask blows up big", "火炎・氷結・酸の試薬を交互に詰めたフラスコ。時々、不安定なフラスコが大爆発", "轮流装入火焰、冰冻、酸性试剂的烧瓶。偶尔会有不稳定的烧瓶大爆炸") },
        { "시위 당기는 속도", L("Draw Speed", "弦を引く速度", "拉弓速度") },
    };
}
