using System.Collections.Generic;

// 번역표: 한국어 → { 한국어(고쳐 쓸 때만), 영어, 일본어, 중국어 }
public static class LocTable
{
    static string[] E(string ko, string en, string ja, string zh) => new[] { ko, en, ja, zh };
    static string[] L(string en, string ja, string zh) => new[] { "", en, ja, zh };

    public static readonly Dictionary<string, string[]> Entries = new Dictionary<string, string[]>
    {
        // ================================================================= 메뉴 · 설정 · 튜토리얼
        { "게임 시작", L("Start Game", "ゲーム開始", "开始游戏") },
        { "게임 종료", L("Quit Game", "ゲーム終了", "退出游戏") },
        { "튜토리얼", L("Tutorial", "チュートリアル", "教程") },
        { "설정", L("Settings", "設定", "设置") },
        { "언어", L("Language", "言語", "语言") },
        { "볼륨", L("Volume", "音量", "音量") },
        { "일반", L("General", "一般", "常规") },
        { "화면", L("Display", "画面", "显示") },
        { "조작", L("Controls", "操作", "操作") },
        { "전체 볼륨", L("Master Volume", "全体音量", "总音量") },
        { "음악", L("Music", "音楽", "音乐") },
        { "효과음", L("Sound Effects", "効果音", "音效") },
        { "화면 모드", L("Display Mode", "画面モード", "显示模式") },
        { "전체 화면", L("Fullscreen", "フルスクリーン", "全屏") },
        { "창 모드", L("Windowed", "ウィンドウ", "窗口") },
        { "해상도", L("Resolution", "解像度", "分辨率") },
        { "수직 동기화", L("VSync", "垂直同期", "垂直同步") },
        { "화면 흔들림", L("Screen Shake", "画面の揺れ", "屏幕震动") },
        { "번쩍임 효과", L("Flash Effects", "フラッシュ効果", "闪光效果") },
        { "켜짐", L("On", "オン", "开") },
        { "꺼짐", L("Off", "オフ", "关") },
        { "위로 이동", L("Move Up", "上に移動", "向上移动") },
        { "아래로 이동", L("Move Down", "下に移動", "向下移动") },
        { "왼쪽 이동", L("Move Left", "左に移動", "向左移动") },
        { "오른쪽 이동", L("Move Right", "右に移動", "向右移动") },
        { "무기 교체", L("Swap Weapon", "武器切替", "切换武器") },
        { "스킬 1", L("Skill 1", "スキル1", "技能1") },
        { "스킬 2", L("Skill 2", "スキル2", "技能2") },
        { "스킬 3", L("Skill 3", "スキル3", "技能3") },
        { "상호작용 (상점 · 확정)", L("Interact (Shop · Confirm)", "決定・ショップ", "互动（商店 · 确认）") },
        { "특수 강화", L("Special Upgrade", "特殊強化", "特殊强化") },
        { "키를 누르세요", L("Press a key", "キーを押す", "请按键") },
        { "버튼을 누른 뒤 바꿀 키를 누르세요 (ESC: 취소)", L("Click a button, then press the new key (ESC: cancel)", "ボタンを押してから新しいキーを押してください（ESC：キャンセル）", "点击按钮后按下新按键（ESC：取消）") },
        { "기본값으로", L("Reset to Default", "初期設定に戻す", "恢复默认") },
        { "거너", L("Gunner", "ガンナー", "枪手") },
        { "검사", L("Swordsman", "剣士", "剑士") },
        { "도적", L("Rogue", "盗賊", "盗贼") },
        { "궁수", L("Archer", "弓使い", "弓箭手") },
        { "연금술사", L("Alchemist", "錬金術師", "炼金术士") },
        { "마지막 총잡이", L("The Last Gunslinger", "最後のガンマン", "最后的枪手") },
        { "떠돌이 기사", L("Wandering Knight", "さすらいの騎士", "流浪骑士") },
        { "그림자 칼날", L("Shadow Blade", "影の刃", "暗影之刃") },
        { "숲의 사냥꾼", L("Hunter of the Woods", "森の狩人", "森林猎手") },
        { "미친 학자", L("Mad Scholar", "狂った学者", "疯狂学者") },
        { "준비 중", L("Coming Soon", "準備中", "敬请期待") },
        { "리볼버와 여러 특수 총기를 다루는 총잡이. 모든 캐릭터의 기준.", L("A gunslinger who handles a revolver and many special guns. The baseline for every character.", "リボルバーと様々な特殊銃を扱うガンマン。全キャラクターの基準。", "使用左轮手枪和各种特殊枪械的枪手。所有角色的基准。") },
        { "무겁고 느리지만 한 번에 여럿을 베는 장검의 달인.", L("A longsword master—heavy and slow, but cuts through many at once.", "重く遅いが、一度に多くを斬り伏せる長剣の達人。", "沉重缓慢，却能一次斩倒众敌的长剑大师。") },
        { "적을 꿰뚫는 화살과 하늘을 덮는 화살비의 명사수.", L("A marksman of piercing arrows and sky-darkening arrow rain.", "敵を貫く矢と空を覆う矢の雨の名手。", "擅长穿透之箭与遮天箭雨的神射手。") },
        { "터지는 플라스크로 적 무리를 한꺼번에 녹이는 괴짜 학자.", L("An eccentric scholar who melts whole crowds with exploding flasks.", "爆発するフラスコで敵の群れをまとめて溶かす変わり者の学者。", "用爆炸烧瓶一口气融化敌群的怪胎学者。") },
        { "아직 준비 중인 캐릭터입니다.", L("This character is still in development.", "まだ準備中のキャラクターです。", "该角色仍在制作中。") },
        { "리볼버", L("Revolver", "リボルバー", "左轮手枪") },
        { "장검", L("Longsword", "長剣", "长剑") },
        { "표창", L("Throwing Star", "手裏剣", "飞镖") },
        { "사냥 활", L("Hunting Bow", "狩猟弓", "猎弓") },
        { "플라스크", L("Flask", "フラスコ", "烧瓶") },
        { "마우스 방향으로 총알 발사", L("Fires bullets toward the cursor", "マウスの方向に弾を発射", "朝鼠标方向射击") },
        { "끝없이 날아가는 표창", L("Throwing stars that fly forever", "どこまでも飛ぶ手裏剣", "无限飞行的飞镖") },
        { "적을 하나 더 꿰뚫는 화살", L("Arrows that pierce one extra enemy", "敵をもう一体貫く矢", "多穿透一个敌人的箭") },
        { "던진 자리에서 터지는 플라스크 (범위 피해)", L("Flasks that burst where they land (area damage)", "投げた場所で弾けるフラスコ（範囲ダメージ）", "落地即爆的烧瓶（范围伤害）") },
        { "타겟팅 필살기", L("Targeting Ultimate", "ターゲティング必殺技", "锁定必杀技") },
        { "회전 베기", L("Spin Slash", "回転斬り", "回旋斩") },
        { "은신", L("Stealth", "隠密", "隐身") },
        { "화살비", L("Arrow Rain", "矢の雨", "箭雨") },
        { "대폭발 플라스크", L("Great Blast Flask", "大爆発フラスコ", "大爆炸烧瓶") },
        { "누르고 있으면 시간이 느려지며 적을 조준, 떼면 조준한 적 모두에게 사격", L("Hold to slow time and mark enemies; release to fire at every marked target", "押し続けると時間が遅くなり敵を照準、離すと照準した敵全員を撃つ", "按住时时间变慢并瞄准敌人，松开后向所有目标射击") },
        { "검을 사방으로 휘둘러 주변을 벱니다. 오래 누를수록 피해가 커집니다", L("Swings your sword in every direction. The longer you hold, the more damage", "剣を四方に振るい周囲を斬ります。長く押すほどダメージ増加", "向四周挥剑斩击，按得越久伤害越高") },
        { "마우스 위치에 화살비를 쏟아붓습니다 (즉발)", L("Pours a rain of arrows at the cursor (instant)", "マウス位置に矢の雨を降らせます（即発動）", "在鼠标位置倾泻箭雨（瞬发）") },
        { "누를수록 커지는 플라스크를 던져 크게 폭발하고 산성 웅덩이를 남깁니다", L("Throws a flask that grows as you hold, exploding hugely and leaving an acid pool", "押すほど大きくなるフラスコを投げて大爆発し、酸の水たまりを残します", "按住时烧瓶越来越大，投出后大爆炸并留下酸液池") },
        { "캐릭터", L("Characters", "キャラクター", "角色") },
        { "보유 포인트: ", L("Points: ", "所持ポイント: ", "持有点数：") },
        { "선택됨", L("Selected", "選択中", "已选择") },
        { "잠김", L("Locked", "ロック", "未解锁") },
        { "잠긴 캐릭터", L("Locked Character", "ロック中のキャラクター", "未解锁角色") },
        { "취소", L("Cancel", "キャンセル", "取消") },
        { "선택", L("Select", "選択", "选择") },
        { "구매", L("Buy", "購入", "购买") },
        { "포인트로 잠금을 풀면 이 캐릭터의 모습과 능력을 볼 수 있습니다.", L("Unlock with points to see this character and their abilities.", "ポイントで解放すると、このキャラクターの姿と能力が見られます。", "用点数解锁后即可查看该角色的外观和能力。") },
        { "포인트가 부족합니다. 게임에서 적을 처치하면 포인트가 쌓입니다.", L("Not enough points. Defeat enemies in-game to earn points.", "ポイントが足りません。ゲームで敵を倒すとポイントが貯まります。", "点数不足。在游戏中击败敌人即可累积点数。") },
        { "약 ", L("about ", "約", "约") },
        { "칸", L(" tiles", "マス", "格") },
        { "기본 무기", L("Weapon", "基本武器", "基础武器") },
        { "획득 포인트 ", L("Points earned ", "獲得ポイント ", "获得点数 ") },
        { "보유 ", L("Total ", "所持 ", "持有 ") },
        { "원반 준비", L("Chakram ready", "チャクラム準備", "圆刃就绪") },
        { "원반 회수 중", L("Chakram returning", "チャクラム回収中", "圆刃回收中") },
        { "대상 없음", L("No target", "対象なし", "没有目标") },
        { "회복!", L("Healed!", "回復！", "恢复！") },
        { "대검", L("Greatsword", "大剣", "巨剑") },
        { "쌍검", L("Twin Blades", "双剣", "双剑") },
        { "창", L("Spear", "槍", "长枪") },
        { "돌진 베기", L("Dash Slash", "突進斬り", "突进斩") },
        { "회오리 베기", L("Whirlwind", "旋風斬り", "旋风斩") },
        { "검기", L("Sword Wave", "剣気", "剑气") },
        { "강철 의지", L("Iron Will", "鋼の意志", "钢铁意志") },
        { "흡혈의 검", L("Vampiric Blade", "吸血の剣", "吸血之剑") },
        { "단검 부채", L("Knife Fan", "短剣の扇", "扇形飞刀") },
        { "불꽃 표창", L("Blaze Star", "炎の手裏剣", "烈焰飞镖") },
        { "차크람", L("Chakram", "チャクラム", "圆刃") },
        { "그림자 이동", L("Shadow Step", "影移動", "影步") },
        { "연막탄", L("Smoke Bomb", "煙幕弾", "烟雾弹") },
        { "암살", L("Assassinate", "暗殺", "暗杀") },
        { "급소 찌르기", L("Vital Strike", "急所突き", "要害突刺") },
        { "잔상", L("Afterimage", "残像", "残影") },
        { "장궁", L("Longbow", "長弓", "长弓") },
        { "연사 석궁", L("Repeating Crossbow", "連射クロスボウ", "连发弩") },
        { "폭발 화살", L("Blast Arrow", "爆発矢", "爆炸箭") },
        { "후퇴 사격", L("Backstep Volley", "後退射撃", "后撤射击") },
        { "사냥 덫", L("Hunter's Trap", "狩猟の罠", "狩猎陷阱") },
        { "관통 사격", L("Piercing Volley", "貫通射撃", "贯穿射击") },
        { "매의 눈", L("Eagle Eye", "鷹の目", "鹰眼") },
        { "순풍", L("Tailwind", "追い風", "顺风") },
        { "화염 플라스크", L("Fire Flask", "火炎フラスコ", "火焰烧瓶") },
        { "빙결 플라스크", L("Frost Flask", "氷結フラスコ", "冰冻烧瓶") },
        { "번개 플라스크", L("Shock Flask", "雷フラスコ", "闪电烧瓶") },
        { "치유 물약", L("Healing Potion", "回復薬", "治疗药水") },
        { "변이 폭탄", L("Transmutation Bomb", "変異爆弾", "变异炸弹") },
        { "산성 비", L("Acid Rain", "酸の雨", "酸雨") },
        { "촉매", L("Catalyst", "触媒", "催化剂") },
        { "황금 손", L("Golden Touch", "黄金の手", "点金手") },
        { "앞쪽을 크게 휩쓰는 느리고 무거운 베기. (공격력 220%)\n진화: 공격력 300%, 범위 증가", L("A slow, heavy sweep in front of you. (220% attack)\nEvolved: 300% attack, larger area", "前方を大きく薙ぎ払う遅く重い斬撃。(攻撃力220%)\n進化: 攻撃力300%、範囲拡大", "向前方大范围横扫的缓慢重斩。（攻击力220%）\n进化：攻击力300%，范围扩大") },
        { "누르고 있으면 양손 검으로 빠르게 연속 베기. (공격력 80%)\n진화: 한 번에 두 번씩 벱니다", L("Hold to slash rapidly with both blades. (80% attack)\nEvolved: slashes twice each time", "押し続けると両手の剣で素早く連続斬り。(攻撃力80%)\n進化: 一度に2回斬る", "按住时双剑快速连斩。（攻击力80%）\n进化：每次斩两下") },
        { "앞으로 길게 찔러 한 줄의 적을 모두 꿰뚫습니다. (공격력 160%)\n진화: 사거리와 피해 증가", L("A long thrust that pierces every enemy in a line. (160% attack)\nEvolved: more range and damage", "前へ長く突き、一列の敵をすべて貫きます。(攻撃力160%)\n進化: 射程とダメージ増加", "向前长刺，贯穿一整列敌人。（攻击力160%）\n进化：射程与伤害提升") },
        { "마우스 쪽으로 빠르게 돌진하며 지나간 적을 벱니다. (공격력 300%)\n진화: 쿨타임 감소, 더 멀리", L("Dash toward the cursor, cutting everything in your path. (300% attack)\nEvolved: shorter cooldown, longer dash", "マウス方向へ素早く突進し、通り道の敵を斬ります。(攻撃力300%)\n進化: クールタイム減少、より遠くへ", "向鼠标方向快速突进，斩击路径上的敌人。（攻击力300%）\n进化：冷却缩短，距离更远") },
        { "잠시 동안 검을 휘돌려 주변 적을 계속 벱니다.\n진화: 지속 시간과 범위 증가", L("Spin your sword for a while, cutting everything around you.\nEvolved: longer and wider", "しばらく剣を振り回し、周囲の敵を斬り続けます。\n進化: 持続時間と範囲増加", "持续回旋挥剑，不断斩击周围敌人。\n进化：持续时间与范围提升") },
        { "거대한 초승달 검기를 날려 한 줄을 벱니다. (공격력 400%)\n진화: 검기 3개", L("Launch a giant crescent sword wave that cuts a line. (400% attack)\nEvolved: 3 waves", "巨大な三日月の剣気を飛ばし一列を斬ります。(攻撃力400%)\n進化: 剣気3つ", "发出巨大的新月剑气斩开一整列。（攻击力400%）\n进化：3道剑气") },
        { "받는 피해가 20% 줄어듭니다.\n진화: 30%", L("Take 20% less damage.\nEvolved: 30%", "受けるダメージが20%減ります。\n進化: 30%", "受到的伤害降低20%。\n进化：30%") },
        { "적을 벨 때마다 체력을 조금 회복합니다.\n진화: 회복량 두 배", L("Heal a little each time you cut an enemy.\nEvolved: double healing", "敵を斬るたびに体力を少し回復します。\n進化: 回復量2倍", "每次斩击敌人时恢复少量生命。\n进化：恢复量翻倍") },
        { "단검 다섯 자루를 부채꼴로 던집니다. (자루당 공격력 60%)\n진화: 일곱 자루", L("Throw five knives in a fan. (60% attack each)\nEvolved: seven knives", "短剣5本を扇状に投げます。(1本あたり攻撃力60%)\n進化: 7本", "扇形投出五把飞刀。（每把攻击力60%）\n进化：七把") },
        { "누르고 있으면 맞은 적을 불태우는 표창을 연사합니다.\n진화: 불타는 피해 두 배", L("Hold to rapid-throw stars that set enemies ablaze.\nEvolved: double burn damage", "押し続けると当たった敵を燃やす手裏剣を連射します。\n進化: 燃焼ダメージ2倍", "按住时连发能点燃敌人的飞镖。\n进化：燃烧伤害翻倍") },
        { "날아갔다 돌아오는 원반. 갈 때 한 번, 올 때 한 번 벱니다.\n진화: 더 크고 멀리", L("A disc that flies out and back, cutting once each way.\nEvolved: bigger and farther", "飛んで戻ってくる円盤。行きに1回、帰りに1回斬ります。\n進化: より大きく遠くへ", "飞出后返回的圆刃，去程和回程各斩一次。\n进化：更大更远") },
        { "마우스 위치로 순간 이동합니다. 잠깐 무적.\n진화: 쿨타임 감소, 도착 자리에서 폭발", L("Teleport to the cursor, briefly invincible.\nEvolved: shorter cooldown, explodes on arrival", "マウス位置へ瞬間移動します。一瞬無敵。\n進化: クールタイム減少、到着地点で爆発", "瞬移到鼠标位置，短暂无敌。\n进化：冷却缩短，落点爆炸") },
        { "연막을 터뜨려 안에 든 적을 크게 느리게 합니다.\n진화: 연막이 적에게 피해", L("Burst a smoke cloud that greatly slows enemies inside.\nEvolved: the smoke damages enemies", "煙幕を炸裂させ、中の敵を大きく遅くします。\n進化: 煙幕が敵にダメージ", "引爆烟雾，大幅减速其中的敌人。\n进化：烟雾会造成伤害") },
        { "가장 가까운 적에게 순간 이동해 치명적인 일격. (공격력 600%)\n진화: 두 번 연속", L("Blink to the nearest enemy for a lethal strike. (600% attack)\nEvolved: strikes twice", "最も近い敵に瞬間移動して致命の一撃。(攻撃力600%)\n進化: 2回連続", "瞬移到最近的敌人身边发动致命一击。（攻击力600%）\n进化：连续两次") },
        { "공격력이 25% 오릅니다.\n진화: 45%", L("Attack +25%.\nEvolved: 45%", "攻撃力が25%上がります。\n進化: 45%", "攻击力提升25%。\n进化：45%") },
        { "이동 속도 +15%, 맞은 뒤 무적 시간이 길어집니다.\n진화: 이동 속도 +30%", L("Move speed +15%, longer invincibility after getting hit.\nEvolved: move speed +30%", "移動速度+15%、被弾後の無敵時間が延びます。\n進化: 移動速度+30%", "移动速度+15%，受击后无敌时间延长。\n进化：移动速度+30%") },
        { "무거운 화살로 적 여섯을 꿰뚫습니다. (공격력 240%)\n진화: 무한 관통", L("A heavy arrow that pierces six enemies. (240% attack)\nEvolved: pierces everything", "重い矢で敵6体を貫きます。(攻撃力240%)\n進化: 無限貫通", "沉重的箭矢贯穿六个敌人。（攻击力240%）\n进化：无限穿透") },
        { "누르고 있으면 작은 화살을 빠르게 연사합니다. (공격력 45%)\n진화: 두 발씩", L("Hold to rapid-fire small bolts. (45% attack)\nEvolved: two at a time", "押し続けると小さな矢を素早く連射します。(攻撃力45%)\n進化: 2発ずつ", "按住时快速连射小箭。（攻击力45%）\n进化：每次两发") },
        { "맞은 자리에서 터지는 화살. (공격력 140% + 폭발)\n진화: 폭발 범위 증가", L("An arrow that explodes on impact. (140% attack + blast)\nEvolved: larger blast", "当たった場所で爆発する矢。(攻撃力140%＋爆発)\n進化: 爆発範囲拡大", "命中即爆的箭。（攻击力140%＋爆炸）\n进化：爆炸范围扩大") },
        { "뒤로 뛰어 물러나며 화살 다섯 발을 부채꼴로 쏩니다.\n진화: 화살 아홉 발", L("Leap backward and fire five arrows in a fan.\nEvolved: nine arrows", "後ろへ跳び退きながら矢5本を扇状に撃ちます。\n進化: 矢9本", "向后跃开并扇形射出五箭。\n进化：九箭") },
        { "마우스 위치에 덫을 놓습니다. 밟은 적은 묶이고 큰 피해를 받습니다.\n진화: 덫 세 개", L("Place a trap at the cursor. Enemies that step on it are rooted and take heavy damage.\nEvolved: three traps", "マウス位置に罠を仕掛けます。踏んだ敵は拘束され大ダメージ。\n進化: 罠3つ", "在鼠标位置放置陷阱。踩中的敌人被束缚并受到重创。\n进化：三个陷阱") },
        { "거대한 화살 세 발을 한 줄로 쏘아 모두 꿰뚫습니다. (공격력 300%)\n진화: 다섯 발", L("Fire three giant arrows in a line that pierce everything. (300% attack)\nEvolved: five arrows", "巨大な矢3本を一列に撃ち、すべてを貫きます。(攻撃力300%)\n進化: 5本", "连射三支巨箭贯穿一切。（攻击力300%）\n进化：五支") },
        { "공격력 +15%, 모든 화살이 적을 하나 더 꿰뚫습니다.\n진화: 공격력 +30%", L("Attack +15%, and every arrow pierces one more enemy.\nEvolved: attack +30%", "攻撃力+15%、すべての矢が敵をもう一体貫きます。\n進化: 攻撃力+30%", "攻击力+15%，所有箭多穿透一个敌人。\n进化：攻击力+30%") },
        { "공격 속도 +15%, 이동 속도 +10%.\n진화: 공격 속도 +30%", L("Attack speed +15%, move speed +10%.\nEvolved: attack speed +30%", "攻撃速度+15%、移動速度+10%。\n進化: 攻撃速度+30%", "攻击速度+15%，移动速度+10%。\n进化：攻击速度+30%") },
        { "터진 자리에 불타는 장판을 남깁니다.\n진화: 장판이 더 크고 오래", L("Leaves a burning patch where it bursts.\nEvolved: bigger, longer-lasting patch", "弾けた場所に燃える床を残します。\n進化: 床がより大きく長く", "在爆炸处留下燃烧区域。\n进化：区域更大更持久") },
        { "터진 자리의 적을 크게 느리게 만듭니다.\n진화: 느려지는 시간 증가", L("Greatly slows enemies caught in the burst.\nEvolved: longer slow", "弾けた場所の敵を大きく遅くします。\n進化: 減速時間増加", "大幅减速爆炸范围内的敌人。\n进化：减速时间延长") },
        { "터지며 주변 적에게 번개가 튑니다.\n진화: 번개가 더 많이 튐", L("Bursts and arcs lightning to nearby enemies.\nEvolved: more chains", "弾けて周囲の敵に稲妻が走ります。\n進化: 稲妻がより多く跳ねる", "爆炸时向周围敌人弹射闪电。\n进化：弹射更多次") },
        { "체력을 25% 회복합니다.\n진화: 40%", L("Restore 25% health.\nEvolved: 40%", "体力を25%回復します。\n進化: 40%", "恢复25%生命。\n进化：40%") },
        { "폭발 안의 약해진 적을 금으로 바꿉니다 (보스 제외, 체력 40% 이하).\n진화: 범위 증가", L("Turns weakened enemies in the blast into gold (not bosses, 40% HP or less).\nEvolved: larger area", "爆発内の弱った敵を金に変えます（ボス除く、体力40%以下）。\n進化: 範囲拡大", "将爆炸范围内虚弱的敌人变成黄金（首领除外，生命40%以下）。\n进化：范围扩大") },
        { "마우스 둘레에 산성 웅덩이가 쏟아집니다.\n진화: 웅덩이 두 배", L("Acid pools rain down around the cursor.\nEvolved: twice as many pools", "マウスの周りに酸の水たまりが降り注ぎます。\n進化: 水たまり2倍", "鼠标周围降下酸液池。\n进化：数量翻倍") },
        { "모든 폭발 범위가 30% 커집니다.\n진화: 50%", L("All explosions are 30% larger.\nEvolved: 50%", "すべての爆発範囲が30%広がります。\n進化: 50%", "所有爆炸范围扩大30%。\n进化：50%") },
        { "코인을 더 얻고, 적을 처치하면 체력을 조금 회복합니다.\n진화: 두 배", L("Earn more coins, and heal a little on each kill.\nEvolved: doubled", "コインを多く得て、敵を倒すと体力を少し回復します。\n進化: 2倍", "获得更多金币，击败敌人时恢复少量生命。\n进化：翻倍") },
        { "쉬움", L("Easy", "イージー", "简单") },
        { "보통", L("Normal", "ノーマル", "普通") },
        { "어려움", L("Hard", "ハード", "困难") },
        { "무한", L("Endless", "エンドレス", "无尽") },
        { "보통 · 어려움", L("Normal · Hard", "ノーマル · ハード", "普通 · 困难") },
        { "쉬움을 클리어하면 보통 · 어려움이 열립니다", L("Clear Easy to unlock Normal · Hard", "イージーをクリアするとノーマル · ハードが解放されます", "通关简单难度后解锁普通 · 困难") },
        { "어려움을 클리어하면 무한 모드가 열립니다", L("Clear Hard to unlock Endless mode", "ハードをクリアするとエンドレスモードが解放されます", "通关困难难度后解锁无尽模式") },
        { "Space 대사 넘기기 · ESC 건너뛰기", L("Space Next line · ESC Skip", "Space セリフ送り · ESC スキップ", "Space 下一句 · ESC 跳过") },
        { "건너뛰기", L("Skip", "スキップ", "跳过") },
        { "클리어!", L("Clear!", "クリア！", "通关！") },
        { "새 난이도 해금: ", L("New difficulty unlocked: ", "新しい難易度解放: ", "解锁新难度：") },
        { "플레이해 주셔서 고맙습니다!", L("Thank you for playing!", "遊んでくれてありがとう！", "感谢游玩！") },
        { "리치 왕이 지하 묘역을 깨우자, 죽은 자들이 땅 위로 기어 나왔다.", L("When the Lich King woke the catacombs, the dead crawled up to the surface.", "リッチ王が地下墓所を目覚めさせると、死者たちが地上へ這い出してきた。", "巫妖王唤醒了地下墓穴，亡者纷纷爬上了地面。") },
        { "마을에 남은 마지막 총잡이는 무너진 신전의 구멍으로 몸을 던졌다.", L("The last gunslinger left in town leapt into the hole of the ruined temple.", "町に残った最後のガンマンは、崩れた神殿の穴へ身を投げた。", "镇上最后一名枪手，纵身跳进了倒塌神殿的洞口。") },
        { "리치 왕을 쓰러뜨리면 그 너머 지옥의 문도 열릴 것이다.", L("Defeat the Lich King, and the gate to Hell beyond will open.", "リッチ王を倒せば、その先の地獄の門も開くだろう。", "击败巫妖王，彼方的地狱之门也将开启。") },
        { "탄창은 가득하다. 이제 세상을 구할 차례다.", L("The magazine is full. Time to save the world.", "弾倉は満タンだ。世界を救う番だ。", "弹匣已满。该去拯救世界了。") },
        { "지옥 너머, 모든 괴물이 모여드는 불타는 사막.", L("Beyond Hell lies a burning desert where every monster gathers.", "地獄の先、あらゆる怪物が集まる燃える砂漠。", "地狱彼方，是群魔聚集的燃烧沙漠。") },
        { "쓰러뜨린 왕들이 몇 번이고 다시 일어선다.", L("The fallen kings rise again, and again.", "倒した王たちが何度でも立ち上がる。", "被击倒的王者们一次又一次地站起。") },
        { "끝은 없다. 얼마나 버틸 수 있을까?", L("There is no end. How long can you last?", "終わりはない。どこまで耐えられるか？", "没有尽头。你能坚持多久？") },
        { "킹 슬라임이 녹아내리자, 초원에 오랜만에 바람이 불었다.", L("As the King Slime melted away, the wind finally blew across the meadow again.", "キングスライムが溶け落ちると、草原に久しぶりの風が吹いた。", "史莱姆王融化殆尽，草原上久违地吹起了风。") },
        { "리치 왕의 저주도, 지옥 군주의 불길도 모두 꺼졌다.", L("The Lich King's curse and the Demon Lord's flames were gone.", "リッチ王の呪いも、地獄の君主の炎も、すべて消えた。", "巫妖王的诅咒与地狱领主的烈焰，都已熄灭。") },
        { "총잡이는 마지막 탄피를 주워 모자 띠에 꽂았다.", L("The gunslinger picked up the last shell casing and tucked it into his hatband.", "ガンマンは最後の薬莢を拾い、帽子のバンドに差した。", "枪手捡起最后一枚弹壳，插在了帽带上。") },
        { "살아남은 사람들은 그를 이렇게 불렀다.", L("The survivors gave him a name.", "生き残った人々は、彼をこう呼んだ。", "幸存的人们这样称呼他。") },
        { "총으로 세상을 구한 자 — Gun Saver.", L("The one who saved the world with a gun — Gun Saver.", "銃で世界を救った者 — Gun Saver。", "用枪拯救世界之人 — Gun Saver。") },
        { "하지만 지평선 너머, 붉게 타오르는 사막에서 무언가 꿈틀거리고 있었다...", L("But beyond the horizon, something stirred in a desert burning red...", "だが地平線の彼方、赤く燃える砂漠で何かが蠢いていた……", "然而在地平线彼方，赤红燃烧的沙漠中，有什么正在蠢动……") },
        { "무한 모드", L("Endless", "エンドレス", "无尽模式") },
        { "보스 처치 ", L("Bosses ", "ボス撃破 ", "击败首领 ") },
        { "최고 ", L("Best ", "最高 ", "最佳 ") },
        { "사막의 모래 폭풍 속에서 보스가 나타났다!", L("A boss emerges from the desert sandstorm!", "砂漠の砂嵐の中からボスが現れた！", "首领从沙漠风暴中现身！") },
        { "보스 처치!  특수 능력 포인트 +1", L("Boss defeated!  Special point +1", "ボス撃破！  特殊能力ポイント+1", "击败首领！  特殊能力点数+1") },
        { "무한 모드 · 불타는 사막", L("Endless · Burning Desert", "エンドレス · 燃える砂漠", "无尽模式 · 燃烧沙漠") },
        { "얼마나 버틸 수 있을까?", L("How long can you last?", "どこまで耐えられるか？", "你能坚持多久？") },
        { "생존 시간 ", L("Survived ", "生存時間 ", "生存时间 ") },
        { "최고 기록 ", L("Best ", "最高記録 ", "最佳纪录 ") },
        { "닫기", L("Close", "閉じる", "关闭") },
        { "이전", L("Prev", "前へ", "上一页") },
        { "다음", L("Next", "次へ", "下一页") },
        { "시작하기", L("Let's Go", "始める", "开始") },
        { "지하 묘역에서 살아남아라", L("Survive the Catacombs", "地下墓所を生き延びろ", "在地下墓穴中活下去") },
        { "나의 첫 유니티 게임", L("My First Unity Game", "初めてのUnityゲーム", "我的第一款Unity游戏") },
        { "다시 시작", L("Restart", "リスタート", "重新开始") },
        { "메인 메뉴로", L("Main Menu", "メインメニューへ", "返回主菜单") },
        { "다시 하기", L("Try Again", "もう一度", "再来一次") },
        { "사망하셨습니다...", L("You Died...", "あなたは死んだ…", "你死了……") },
        { "일시정지", L("Paused", "一時停止", "暂停") },
        { "[ESC] 계속하기", L("[ESC] Resume", "[ESC] 再開", "[ESC] 继续") },
        { "[P] 상점    [ESC] 메뉴", E("[ESC] 메뉴 · 설정", "[ESC] Menu · Settings", "[ESC] メニュー・設定", "[ESC] 菜单 · 设置") },
        { "[P] 또는 [ESC] 로 닫기", E("[ESC] 로 닫기", "[ESC] to close", "[ESC] で閉じる", "按 [ESC] 关闭") },
        { "일시정지 1초", L("Paused 1s", "一時停止 1秒", "暂停 1秒") },
        { "일시정지 ", L("Paused ", "一時停止 ", "暂停 ") },
        { "레벨 업!", L("Level Up!", "レベルアップ！", "升级！") },
        { "좀 쎈 보스", L("A Tough Boss", "ちょっと強いボス", "有点强的首领") },
        { "능력을 하나 선택하세요", L("Choose an ability", "能力を一つ選んでください", "请选择一项能力") },
        { "카드를 눌러 선택", L("Click a card to choose", "カードを押して選択", "点击卡牌选择") },
        { "상점", L("Shop", "ショップ", "商店") },
        { "코인 : 0", L("Coins : 0", "コイン : 0", "金币 : 0") },
        { "신전 문이 열렸다!", L("The temple gate is open!", "神殿の扉が開いた！", "神殿之门开启了！") },
        { "지옥의 문", L("Gate of Hell", "地獄の門", "地狱之门") },
        { "포인트 3개로 세 갈래에서 특수 능력 3개를 고르세요", L("Spend 3 points to pick 3 special abilities from the three branches", "3ポイントで3系統から特殊能力を3つ選んでください", "用3点在三个分支中选择3项特殊能力") },
        { "현재 / 최대", L("Now / Max", "現在 / 最大", "当前 / 最大") },

        // ================================================================= 툴팁
        { "타겟팅 스킬", L("Targeting Skill", "ターゲティングスキル", "锁定技能") },
        { "게이지가 가득 차면 우클릭을 누르고 있는 동안 시간이 느려지며 주변 적을 차례로 조준합니다.\n버튼을 떼면 조준한 모든 적에게 일제 사격!\n\n일반 사격으로 적을 맞히면 게이지가 찹니다.",
          E("게이지가 가득 차면 우클릭으로 필살기를 씁니다. 들고 있는 무기마다 조준 화면과 필살기가 다릅니다.\n\n게이지는 시간이 지나면 차고, 적을 처치하면 잠깐 더 빨리 찹니다.",
            "When the gauge is full, right-click to use your ultimate. Each weapon has its own aiming screen and ultimate.\n\nThe gauge fills over time, and faster for a moment after each kill.",
            "ゲージが満タンになったら右クリックで必殺技。武器ごとに照準画面と必殺技が違います。\n\nゲージは時間で溜まり、敵を倒すと少しの間速く溜まります。",
            "能量满时右键释放必杀技。每种武器的瞄准画面和必杀技都不同。\n\n能量随时间积累，击杀敌人后短时间内积累更快。") },

        // ================================================================= 특수 능력 (이름 · 설명)
        { "지옥불 산탄총", L("Hellfire Shotgun", "獄炎ショットガン", "狱火霰弹枪") },
        { "영혼 저격총", L("Soul Sniper", "ソウルスナイパー", "灵魂狙击枪") },
        { "저주받은 쌍권총", L("Cursed Twin Pistols", "呪われた二丁拳銃", "被诅咒的双枪") },
        { "화염 방사기", L("Flamethrower", "火炎放射器", "火焰喷射器") },
        { "영혼 인도 지팡이", L("Soulguide Staff", "魂導きの杖", "引魂法杖") },
        { "번개 사슬총", L("Chain Lightning Gun", "連鎖雷撃銃", "连锁闪电枪") },
        { "부메랑 낫", L("Boomerang Scythe", "ブーメラン鎌", "回旋镰刀") },
        { "용암 유탄 발사기", L("Lava Grenade Launcher", "溶岩グレネードランチャー", "熔岩榴弹发射器") },
        { "그림자 대시", L("Shadow Dash", "シャドウダッシュ", "暗影冲刺") },
        { "지옥불 장판", L("Hellfire Field", "獄炎フィールド", "狱火领域") },
        { "시간 왜곡", L("Time Warp", "時間歪曲", "时间扭曲") },
        { "희생의 계약", L("Blood Pact", "犠牲の契約", "牺牲契约") },
        { "영혼 폭발", L("Soul Burst", "ソウルバースト", "灵魂爆发") },
        { "해골 소환", L("Summon Skeletons", "スケルトン召喚", "召唤骷髅") },
        { "거울 분신", L("Mirror Image", "鏡の分身", "镜像分身") },
        { "피의 갈고리", L("Blood Hook", "血のフック", "鲜血钩索") },
        { "수호 영혼", L("Guardian Souls", "守護の魂", "守护之魂") },
        { "복수의 가시", L("Thorns of Vengeance", "復讐の棘", "复仇之刺") },
        { "탄창 저주", L("Cursed Magazine", "弾倉の呪い", "弹匣诅咒") },
        { "불사의 맹세", L("Oath of Undying", "不死の誓い", "不死誓约") },
        { "총알 대신 앞쪽 부채꼴(6칸) 안의 적 모두에게\n즉시 250% 피해와 강한 넉백. 발사 간격 1.4배.", L("Instead of bullets, hits every enemy in a cone ahead (6 tiles)\nfor 250% damage with strong knockback. Fire interval x1.4.", "弾の代わりに前方の扇形(6マス)内の敵全員に\n即座に250%ダメージと強いノックバック。発射間隔1.4倍。", "不发射子弹，直接对前方扇形(6格)内所有敌人\n造成250%伤害并强力击退。射击间隔1.4倍。") },
        { "누르고 있다가 떼면 발사합니다. 모든 적을 관통하고\n충전 정도에 따라 피해 150%~300%.", L("Hold and release to fire. Pierces every enemy;\n150%-300% damage depending on charge.", "押し続けて離すと発射。全ての敵を貫通し\nチャージに応じて150%〜300%ダメージ。", "按住后松开发射。穿透所有敌人，\n根据蓄力造成150%~300%伤害。") },
        { "누르고 있으면 연사합니다. 발사 간격 절반, 발당 피해 55%.\n두 발에 탄 1개만 씁니다.", L("Hold for rapid fire. Half the fire interval, 55% damage per shot.\nOnly 1 ammo per 2 shots.", "押し続けると連射。発射間隔半分、1発55%ダメージ。\n2発で弾1つしか使いません。", "按住连射。射击间隔减半，每发55%伤害。\n每2发只消耗1颗子弹。") },
        { "누르고 있으면 불을 뿜어 적을 관통하고 불태웁니다.\n탄약 대신 과열 게이지를 씁니다.", L("Hold to spew fire that pierces and burns enemies.\nUses an overheat gauge instead of ammo.", "押し続けると火を噴き、敵を貫通して燃やします。\n弾薬の代わりに過熱ゲージを使います。", "按住喷火，穿透并点燃敌人。\n使用过热槽代替弹药。") },
        { "가장 가까운 적을 쫓아가는 유도탄을 쏩니다.\n발당 피해 70%, 조준이 필요 없습니다.", L("Fires homing shots that chase the nearest enemy.\n70% damage per shot, no aiming needed.", "最も近い敵を追う誘導弾を撃ちます。\n1発70%ダメージ、照準不要。", "发射追踪最近敌人的导弹。\n每发70%伤害，无需瞄准。") },
        { "맞은 적에게서 최대 4마리에게 번개가 튑니다.\n튈 때마다 피해가 20%씩 줄어듭니다.", L("Lightning jumps from the target to up to 4 enemies.\nEach jump deals 20% less damage.", "命中した敵から最大4体に雷が飛びます。\n飛ぶたびにダメージが20%ずつ減ります。", "闪电从命中的敌人弹射到最多4个敌人。\n每次弹射伤害降低20%。") },
        { "날아갔다 돌아오며 오가는 길의 적을 모두 벱니다.\n피해 150%, 한 번에 하나만 던질 수 있습니다.", L("Flies out and back, cutting every enemy on the way.\n150% damage, only one at a time.", "飛んで戻ってくる間に道中の敵を全て斬ります。\n150%ダメージ、一度に1つだけ投げられます。", "飞出再飞回，斩击沿途所有敌人。\n150%伤害，一次只能投掷一把。") },
        { "마우스 위치에 떨어져 폭발(피해 200%)하고\n잠깐 용암 웅덩이를 남깁니다. 탄 2개 사용.", L("Lands at the cursor and explodes (200% damage),\nleaving a brief lava pool. Uses 2 ammo.", "マウス位置に落ちて爆発(200%ダメージ)し\n一時的に溶岩溜まりを残します。弾2つ使用。", "落在鼠标位置爆炸(200%伤害)，\n并短暂留下熔岩池。消耗2发弹药。") },
        { "마우스 방향으로 짧게 돌진합니다.\n돌진 중에는 무적. 쿨타임 3초.", L("Dash a short distance toward the cursor.\nInvincible while dashing. Cooldown 3s.", "マウス方向に短く突進します。\n突進中は無敵。クールタイム3秒。", "向鼠标方向短距离冲刺。\n冲刺时无敌。冷却3秒。") },
        { "마우스 위치에 4초 동안 불 장판을 깝니다.\n0.5초마다 공격력 75% 피해. 쿨타임 12초.", L("Creates a fire field at the cursor for 4s.\n75% damage every 0.5s. Cooldown 12s.", "マウス位置に4秒間炎のフィールドを敷きます。\n0.5秒ごとに攻撃力75%ダメージ。クールタイム12秒。", "在鼠标位置生成持续4秒的火焰领域。\n每0.5秒造成75%伤害。冷却12秒。") },
        { "5초 동안 모든 적이 50% 느려집니다.\n플레이어는 정상 속도. 쿨타임 20초.", L("All enemies are 50% slower for 5s.\nYou move at normal speed. Cooldown 20s.", "5秒間、全ての敵が50%遅くなります。\nプレイヤーは通常速度。クールタイム20秒。", "5秒内所有敌人减速50%。\n玩家速度不变。冷却20秒。") },
        { "최대 체력 20%를 바쳐 8초 동안\n공격력 2배, 연사 1.5배. 쿨타임 25초.", L("Sacrifice 20% max HP for 8s of\ndouble damage and x1.5 fire rate. Cooldown 25s.", "最大体力の20%を捧げ8秒間\n攻撃力2倍、連射1.5倍。クールタイム25秒。", "献祭20%最大生命，8秒内\n攻击力2倍、射速1.5倍。冷却25秒。") },
        { "적을 처치하면 영혼이 쌓입니다(최대 40).\n5개 이상일 때 모두 터뜨려 주변에 피해. 쿨타임 5초.", L("Kills store souls (max 40).\nWith 5+, detonate them all to damage nearby enemies. Cooldown 5s.", "敵を倒すと魂が溜まります(最大40)。\n5つ以上で全て炸裂させ周囲にダメージ。クールタイム5秒。", "击杀敌人积累灵魂(最多40)。\n达到5个以上时全部引爆伤害周围。冷却5秒。") },
        { "아군 해골 3기를 10초 동안 부릅니다.\n적에게 달려가 자폭(공격력 300%). 쿨타임 15초.", L("Summons 3 allied skeletons for 10s.\nThey run at enemies and explode (300%). Cooldown 15s.", "味方のスケルトン3体を10秒間呼び出します。\n敵に突っ込んで自爆(攻撃力300%)。クールタイム15秒。", "召唤3具友方骷髅，持续10秒。\n冲向敌人自爆(300%)。冷却15秒。") },
        { "제자리에 분신을 남기고 반투명해집니다.\n3초 동안 적이 분신을 쫓습니다. 쿨타임 12초.", L("Leave a decoy behind and turn translucent.\nEnemies chase the decoy for 3s. Cooldown 12s.", "その場に分身を残して半透明になります。\n3秒間、敵は分身を追います。クールタイム12秒。", "原地留下分身并变为半透明。\n敌人会追击分身3秒。冷却12秒。") },
        { "사슬을 던져 적을 끌어오거나(피해 150%)\n벽 쪽으로 날아갑니다. 쿨타임 4초.", L("Throw a chain to pull an enemy in (150%)\nor fly toward a wall. Cooldown 4s.", "鎖を投げて敵を引き寄せる(150%ダメージ)か\n壁の方へ飛びます。クールタイム4秒。", "投出锁链拉回敌人(150%伤害)\n或飞向墙壁。冷却4秒。") },
        { "영혼 구체 3개가 주위를 돌며\n닿은 적에게 공격력 80% 피해를 줍니다.", L("3 soul orbs circle you,\ndealing 80% damage to enemies they touch.", "魂の球3つが周囲を回り\n触れた敵に攻撃力80%のダメージを与えます。", "3颗灵魂球环绕你，\n对接触的敌人造成80%伤害。") },
        { "피격될 때마다 주변 적에게\n공격력 300% 피해를 주고 밀어냅니다.", L("Each time you are hit, nearby enemies\ntake 300% damage and are pushed away.", "被弾するたびに周囲の敵に\n攻撃力300%のダメージを与え押し返します。", "每次受击时对周围敌人\n造成300%伤害并击退。") },
        { "탄창의 마지막 한 발이 피해 3배가 되고\n맞은 곳에서 폭발합니다.", L("The last bullet in each magazine deals triple damage\nand explodes on impact.", "弾倉の最後の1発がダメージ3倍になり\n命中地点で爆発します。", "弹匣最后一发造成3倍伤害\n并在命中处爆炸。") },
        { "한 판에 한 번, 죽을 피해를 받으면\n체력 1로 버티고 3초 동안 무적이 됩니다.", L("Once per run, survive a lethal hit\nwith 1 HP and become invincible for 3s.", "1プレイに1回、致命ダメージを受けても\n体力1で耐え、3秒間無敵になります。", "每局一次，受到致命伤害时\n以1点生命存活并无敌3秒。") },

        // ================================================================= 보스 · 스테이지
        { "킹 슬라임이 둘로 갈라졌다!", L("The King Slime split in two!", "キングスライムが二つに分裂した！", "史莱姆王分裂成了两只！") },
        { "슬라임이 또 갈라진다!", L("The slimes split again!", "スライムがまた分裂する！", "史莱姆又分裂了！") },
        { "리치 왕이 망자의 의식을 시작한다!", L("The Lich King begins the Rite of the Dead!", "リッチ王が死者の儀式を始める！", "巫妖王开始了亡者仪式！") },
        { "지옥의 군주가 십자 불길을 내뿜는다!", L("The Demon Lord unleashes the Hellfire Cross!", "地獄の君主が十字の業火を放つ！", "地狱领主喷出十字烈焰！") },
        { "킹 슬라임이 미친 듯이 뛰어오른다!", L("The King Slime is leaping wildly!", "キングスライムが狂ったように跳ね回る！", "史莱姆王疯狂地跳跃！") },
        { "특수 강화 [", L("Special Upgrade [", "特殊強化 [", "特殊强化 [") },
        { "]   포인트 ", L("]   Points ", "]   ポイント ", "]   点数 ") },
        { "중간 보스 등장!\n쓰러뜨리면 특수 능력 포인트 +1", L("A mid-boss appears!\nDefeat it for +1 special point", "中ボス出現！\n倒すと特殊能力ポイント+1", "中头目出现！\n击败可获得特殊能力点数+1") },
        { "특수 능력 포인트 +1!\n[", L("Special point +1!\n[", "特殊能力ポイント+1！\n[", "特殊能力点数+1！\n[") },
        { "] 또는 아래 버튼으로 강화", L("] or the button below to upgrade", "] または下のボタンで強化", "] 或下方按钮进行强化") },
        { "신전 문이 열렸다!\n문으로 들어가세요", L("The temple gate is open!\nEnter the gate", "神殿の扉が開いた！\n扉に入ってください", "神殿之门开启了！\n请进入大门") },
        { "지옥의 군주를 쓰러뜨렸다!\n성문 너머로 초원이 보인다", L("The Demon Lord has fallen!\nA meadow lies beyond the gate", "地獄の君主を倒した！\n城門の向こうに草原が見える", "击败了地狱领主！\n城门外是一片草原") },
        { "킹 슬라임을 쓰러뜨렸다!\n모든 스테이지 클리어!", L("The King Slime has fallen!\nAll stages cleared!", "キングスライムを倒した！\n全ステージクリア！", "击败了史莱姆王！\n全部关卡通关！") },
        { "3장 · 초원\n특수 능력 포인트 +2", L("Chapter 3 · Meadow\nSpecial points +2", "第3章・草原\n特殊能力ポイント+2", "第3章 · 草原\n特殊能力点数+2") },
        { "2장 · 불타는 지옥", L("Chapter 2 · Burning Hell", "第2章・燃える地獄", "第2章 · 燃烧地狱") },
        { "지옥의 문이 당신을 끌어당긴다!  ", L("The gate is pulling you in!  ", "門があなたを引き寄せる！  ", "大门正在将你吸入！  ") },
        { "신전 문으로 들어가세요  ", L("Enter the gate  ", "門に入ってください  ", "请进入大门  ") },
        { "초", L("s", "秒", "秒") },
        { "떠돌이 상점이 나타났다!\n10초 안에 다가가 [{INTERACT}]", L("A wandering shop appeared!\nReach it within 10s and press [{INTERACT}]", "さすらいのショップが現れた！\n10秒以内に近づいて [{INTERACT}]", "流浪商店出现了！\n10秒内靠近并按 [{INTERACT}]") },
        { "상점 열기", L("Open Shop", "ショップを開く", "打开商店") },
        { "상점  ", L("Shop  ", "ショップ  ", "商店  ") },

        // ================================================================= 레벨업 능력
        { "관통하는 총알", L("Piercing Bullets", "貫通する弾", "穿透子弹") },
        { "총알의 관통력이 증가합니다 \n( 관통 ", L("Bullets pierce more enemies \n( Pierce ", "弾の貫通力が上がります \n( 貫通 ", "子弹穿透力提升 \n( 穿透 ") },
        { "코인충", L("Coin Hoarder", "コイン好き", "金币狂") },
        { "코인을 더 많이 획득합니다.\n( 코인 획득량 ", L("Gain more coins.\n( Coins per pickup ", "より多くのコインを獲得します。\n( コイン獲得量 ", "获得更多金币。\n( 金币获取量 ") },
        { "재활용 에너지", L("Recycled Energy", "リサイクルエネルギー", "能量回收") },
        { "스킬 게이지가 20% 감소합니다\n( 게이지 -20% )", L("The skill gauge fills 20% faster\n( Gauge -20% )", "スキルゲージが20%早く溜まります\n( ゲージ -20% )", "技能能量积累加快20%\n( 能量 -20% )") },
        { "노려보는 눈빛", L("Piercing Glare", "睨みつける眼光", "凝视之眼") },
        { "스킬을 사용하는 동안 타겟이 된 적이 더 느려집니다. \n( 속도 -20% )", L("Targeted enemies slow down more while aiming. \n( Speed -20% )", "スキル使用中、狙った敵がさらに遅くなります。 \n( 速度 -20% )", "瞄准期间被锁定的敌人更慢。 \n( 速度 -20% )") },
        { "더 많은 경험치", L("More Experience", "経験値アップ", "更多经验") },
        { "킬 경험치 +10%", L("Kill EXP +10%", "撃破経験値 +10%", "击杀经验 +10%") },
        { "코인 자석", L("Coin Magnet", "コインマグネット", "金币磁铁") },
        { "주변의 코인을 끌어옵니다.\n( 범위 ", L("Pulls in nearby coins.\n( Range ", "周囲のコインを引き寄せます。\n( 範囲 ", "吸引附近的金币。\n( 范围 ") },
        { "멀티 샷", L("Multi Shot", "マルチショット", "多重射击") },
        { "한 번에 쏘는 총알이 1발 늘어나지만, 한 발당 피해는 줄어듭니다.\n( ", L("Fire 1 more bullet per shot, but each deals less damage.\n( ", "一度に撃つ弾が1発増えますが、1発あたりのダメージは減ります。\n( ", "每次多射1发子弹，但每发伤害降低。\n( ") },
        { "발 ", L(" shots ", "発 ", "发 ") },
        { "밀어내기", L("Knockback", "押し返し", "击退") },
        { "총알이 적을 밀어내는 효과 +25%\n( 최대 ", L("Bullet knockback +25%\n( Max ", "弾のノックバック +25%\n( 最大 ", "子弹击退效果 +25%\n( 最多 ") },
        { "번 )", L(" times )", "回 )", "次 )") },
        { "강철같은 심장", L("Heart of Steel", "鋼の心臓", "钢铁之心") },
        { "체력을 즉시 모두 회복하며, 최대 체력이 12% 증가합니다.", L("Fully restores HP and increases max HP by 12%.", "体力を即座に全回復し、最大体力が12%増えます。", "立即回满生命，最大生命提高12%。") },
        { "단단한 신체", L("Tough Body", "頑丈な体", "坚韧体魄") },
        { "받는 피해를 12% 감소시킵니다.\n( 최대 ", L("Take 12% less damage.\n( Max ", "受けるダメージを12%減らします。\n( 最大 ", "受到的伤害降低12%。\n( 最多 ") },
        { "생명의 샘", L("Fountain of Life", "生命の泉", "生命之泉") },
        { "시간이 지나면 체력이 조금씩 회복됩니다.\n( 초당 ", L("Slowly regenerate HP over time.\n( Per second ", "時間とともに体力が少しずつ回復します。\n( 毎秒 ", "随时间缓慢恢复生命。\n( 每秒 ") },
        { "피의 굶주림", L("Bloodthirst", "血の飢え", "嗜血") },
        { "적을 처치할 때마다 체력을 회복합니다.\n( 처치당 ", L("Heal each time you kill an enemy.\n( Per kill ", "敵を倒すたびに体力を回復します。\n( 撃破ごと ", "每次击杀恢复生命。\n( 每次击杀 ") },
        { "[{INTERACT}] 확정 : ", L("[{INTERACT}] Confirm : ", "[{INTERACT}] 決定 : ", "[{INTERACT}] 确认 : ") },
        { "카드를 클릭해 고른 뒤 [{INTERACT}]로 확정", L("Click a card, then press [{INTERACT}] to confirm", "カードをクリックして [{INTERACT}] で決定", "点击卡牌后按 [{INTERACT}] 确认") },
        { "총알이 적을 뚫고 지나갑니다.", L("Bullets pass through enemies.", "弾が敵を貫通します。", "子弹会穿透敌人。") },
        { "관통: 적 ", L("Pierce: ", "貫通: 敵 ", "穿透: ") },
        { "마리", L(" enemies", "体", "个敌人") },
        { "코인을 주울 때 더 많이 얻습니다.", L("Get more from each coin you pick up.", "コインを拾うとより多く手に入ります。", "拾取金币时获得更多。") },
        { "코인 1개당 획득량: ", L("Per coin: ", "コイン1枚あたり: ", "每枚金币获得: ") },
        { "스킬 게이지가 더 빨리 가득 찹니다. (적을 처치하면 잠깐 더 빨라짐)", L("The skill gauge fills faster. (Even faster for a moment after kills)", "スキルゲージが早く溜まります。(敵を倒すと少しの間さらに速い)", "技能能量积累更快。(击杀后短时间更快)") },
        { "게이지가 가득 차는 시간: ", L("Time to fill: ", "満タンまでの時間: ", "充满时间: ") },
        { "스킬을 쓰는 동안 적이 더 느려집니다.", L("Enemies are slower while you aim.", "スキル使用中、敵がさらに遅くなります。", "使用技能时敌人更慢。") },
        { "스킬 중 시간 속도: ", L("Time speed while aiming: ", "スキル中の時間速度: ", "技能期间时间速度: ") },
        { "적을 처치할 때 얻는 경험치가 늘어납니다.", L("Gain more EXP from kills.", "敵を倒した時の経験値が増えます。", "击杀获得的经验增加。") },
        { "경험치 배율: ", L("EXP multiplier: ", "経験値倍率: ", "经验倍率: ") },
        { "주변의 코인을 끌어옵니다.", L("Pulls in nearby coins.", "周囲のコインを引き寄せます。", "吸引附近的金币。") },
        { "끌어오는 범위: ", L("Pull range: ", "引き寄せ範囲: ", "吸引范围: ") },
        { "한 번에 여러 발을 부채꼴로 발사합니다. 발사 수가 늘수록 한 발당 피해는 줄어듭니다.", L("Fire several bullets in a fan. More bullets means less damage each.", "一度に複数の弾を扇状に撃ちます。弾数が増えるほど1発のダメージは減ります。", "一次呈扇形发射多发子弹。子弹越多每发伤害越低。") },
        { "발사 수: ", L("Shots: ", "発射数: ", "发射数: ") },
        { "발 (최대 5발)\n현재 한 발당 피해: ", L(" (max 5)\nDamage per shot: ", "発 (最大5発)\n現在の1発あたりダメージ: ", "发 (最多5发)\n当前每发伤害: ") },
        { "총알이 적을 더 멀리 밀어냅니다.", L("Bullets push enemies farther.", "弾が敵をより遠くへ押し返します。", "子弹将敌人击退得更远。") },
        { "넉백: 기본의 ", L("Knockback: base x", "ノックバック: 基本の ", "击退: 基础的 ") },
        { "최대 체력이 늘어나고, 선택하는 순간 체력을 모두 회복합니다.", L("Raises max HP and fully heals you when chosen.", "最大体力が増え、選んだ瞬間に体力が全回復します。", "提高最大生命，选择时回满生命。") },
        { "최대 체력: ", L("Max HP: ", "最大体力: ", "最大生命: ") },
        { "적에게 받는 피해가 줄어듭니다.", L("Take less damage from enemies.", "敵から受けるダメージが減ります。", "受到敌人的伤害降低。") },
        { "받는 피해 감소: ", L("Damage reduction: ", "被ダメージ軽減: ", "减伤: ") },
        { "시간이 지나면 체력이 조금씩 회복됩니다.", L("Slowly regenerate HP over time.", "時間とともに体力が少しずつ回復します。", "随时间缓慢恢复生命。") },
        { "초당 회복: ", L("Regen per second: ", "毎秒回復: ", "每秒恢复: ") },
        { "적을 처치할 때마다 체력을 회복합니다.", L("Heal each time you kill an enemy.", "敵を倒すたびに体力を回復します。", "每次击杀恢复生命。") },
        { "처치당 회복: ", L("Heal per kill: ", "撃破ごとの回復: ", "每次击杀恢复: ") },
        { "\n\n<color=#F5D478>현재 ", L("\n\n<color=#F5D478>Now ", "\n\n<color=#F5D478>現在 ", "\n\n<color=#F5D478>当前 ") },

        // ================================================================= 상점
        { "최대", L("MAX", "最大", "已满") },
        { "구매\n", L("Buy\n", "購入\n", "购买\n") },
        { " 코인", L(" coins", " コイン", " 金币") },
        { "코인 : ", L("Coins : ", "コイン : ", "金币 : ") },
        { "총알 공격력\n", L("Bullet Damage\n", "弾の攻撃力\n", "子弹攻击力\n") },
        { "발, 발당 ", L(" shots, each ", "発、1発 ", "发，每发 ") },
        { "공격 속도\n초당 ", L("Fire Rate\n", "攻撃速度\n毎秒 ", "攻击速度\n每秒 ") },
        { "발 (최대)", L("/s (MAX)", "発 (最大)", "发 (已满)") },
        { "공격 속도 (초당)\n", L("Fire Rate (per sec)\n", "攻撃速度 (毎秒)\n", "攻击速度 (每秒)\n") },
        { "발", L("", "発", "发") },
        { "재장전 속도\n", L("Reload Time\n", "リロード速度\n", "换弹速度\n") },
        { "초 (최대)", L("s (MAX)", "秒 (最大)", "秒 (已满)") },
        { "초 -> ", L("s -> ", "秒 -> ", "秒 -> ") },
        { "최대 탄창\n", L("Magazine Size\n", "最大弾倉\n", "弹匣容量\n") },
        { "이동 속도\n", L("Move Speed\n", "移動速度\n", "移动速度\n") },
        { " (최대)", L(" (MAX)", " (最大)", " (已满)") },
        { "스킬 강화", L("Skill Upgrades", "スキル強化", "技能强化") },
        { "우클릭 필살기를 무기마다 따로 강화합니다 · 위력 +20% · 특성은 무기마다 다름", L("Upgrade each weapon's right-click ultimate · Power +20% · Traits differ per weapon", "右クリック必殺技を武器ごとに強化します・威力+20%・特性は武器ごとに異なる", "分别强化每种武器的右键必杀技 · 威力+20% · 特性因武器而异") },
        { "상점으로", L("Back to Shop", "ショップへ", "返回商店") },
        { "기본 권총", L("Basic Pistol", "基本拳銃", "基础手枪") },
        { "위력", L("Power", "威力", "威力") },
        { "<color=#a39aa8>최대</color>", L("<color=#a39aa8>MAX</color>", "<color=#a39aa8>最大</color>", "<color=#a39aa8>已满</color>") },
        { " 코인</color>", L(" coins</color>", " コイン</color>", " 金币</color>") },
        { "코인이 부족합니다 (", L("Not enough coins (", "コインが足りません (", "金币不足 (") },
        { "무기 강화", L("Weapon Upgrades", "武器強化", "武器强化") },
        { "무기마다 따로 강화됩니다 (권총 강화와 별개) · 피해 +15% · 연사 +10% · 탄창 +25% · 특성은 무기마다 다름", L("Each weapon is upgraded separately (not the pistol) · Damage +15% · Fire rate +10% · Magazine +25% · Traits differ", "武器ごとに個別に強化されます(拳銃とは別) · ダメージ+15% · 連射+10% · 弾倉+25% · 特性は武器ごと", "每种武器单独强化(与手枪无关) · 伤害+15% · 射速+10% · 弹匣+25% · 特性因武器而异") },
        { "피해", L("Damage", "ダメージ", "伤害") },
        { "연사", L("Fire Rate", "連射", "射速") },
        { "탄창", L("Magazine", "弾倉", "弹匣") },
        { "\n<color=#a39aa8>해당 없음</color>", L("\n<color=#a39aa8>N/A</color>", "\n<color=#a39aa8>対象外</color>", "\n<color=#a39aa8>不适用</color>") },

        // ================================================================= 필살기 · 강화 특성
        { "지옥불 포격", L("Hellfire Barrage", "獄炎砲撃", "狱火炮击") },
        { "관통 레일건", L("Piercing Railgun", "貫通レールガン", "穿透电磁炮") },
        { "총알 폭풍", L("Bullet Storm", "弾丸の嵐", "子弹风暴") },
        { "화염 회오리", L("Fire Tornado", "炎の竜巻", "火焰龙卷") },
        { "영혼 떼", L("Soul Swarm", "魂の群れ", "灵魂群") },
        { "뇌운", L("Thunderstorm", "雷雲", "雷云") },
        { "죽음의 춤", L("Dance of Death", "死の舞", "死亡之舞") },
        { "용암 융단폭격", L("Lava Carpet Bombing", "溶岩絨毯爆撃", "熔岩地毯轰炸") },
        { "일제 사격", L("Volley", "一斉射撃", "齐射") },
        { "타겟 수", L("Targets", "ターゲット数", "目标数") },
        { "영혼 구슬", L("Soul Orbs", "魂の球", "灵魂球") },
        { "포격 횟수", L("Blasts", "砲撃回数", "炮击次数") },
        { "광선 굵기", L("Beam Width", "光線の太さ", "光束宽度") },
        { "지속 시간", L("Duration", "持続時間", "持续时间") },
        { "회오리 지속", L("Tornado Time", "竜巻の持続", "龙卷持续") },
        { "뇌운 지속", L("Storm Time", "雷雲の持続", "雷云持续") },
        { "폭격 줄", L("Bomb Rows", "爆撃の列", "轰炸行数") },
        { "특성", L("Trait", "特性", "特性") },
        { "+2마리", L("+2", "+2体", "+2个") },
        { "+1개", L("+1", "+1個", "+1个") },
        { "+1회", L("+1", "+1回", "+1次") },
        { "+0.4초", L("+0.4s", "+0.4秒", "+0.4秒") },
        { "+1.5초", L("+1.5s", "+1.5秒", "+1.5秒") },
        { "+0.8초", L("+0.8s", "+0.8秒", "+0.8秒") },
        { "+2줄", L("+2 rows", "+2列", "+2行") },
        { "사거리", L("Range", "射程", "射程") },
        { "충전 속도", L("Charge Speed", "チャージ速度", "蓄力速度") },
        { "관통", L("Pierce", "貫通", "穿透") },
        { "냉각", L("Cooling", "冷却", "冷却") },
        { "연쇄", L("Chain", "連鎖", "连锁") },
        { "낫 크기", L("Blade Size", "鎌の大きさ", "镰刀大小") },
        { "폭발 범위", L("Blast Radius", "爆発範囲", "爆炸范围") },
        { "사거리 +1", L("Range +1", "射程 +1", "射程 +1") },
        { "충전 시간 -15%", L("Charge time -15%", "チャージ時間 -15%", "蓄力时间 -15%") },
        { "관통 +1", L("Pierce +1", "貫通 +1", "穿透 +1") },
        { "열 발생 -20%", L("Heat -20%", "発熱 -20%", "发热 -20%") },
        { "연쇄 +1", L("Chain +1", "連鎖 +1", "连锁 +1") },
        { "크기·거리 +15%", L("Size·Reach +15%", "大きさ・距離 +15%", "大小·距离 +15%") },
        { "범위 +0.6", L("Radius +0.6", "範囲 +0.6", "范围 +0.6") },

        // ================================================================= 진화
        { " 진화!", L(" evolved!", " 進化！", " 进化！") },
        { "사거리 +2, 부채꼴이 넓어지고 피해 320%. 맞은 적이 불탑니다.", L("Range +2, wider cone, 320% damage. Hit enemies burn.", "射程+2、扇形が広がりダメージ320%。命中した敵が燃えます。", "射程+2，扇形更宽，伤害320%。命中的敌人会燃烧。") },
        { "충전 시간 0.8초. 완충 사격이 맞은 곳에서 폭발합니다.", L("0.8s charge. Fully charged shots explode where they hit.", "チャージ0.8秒。フルチャージ射撃が命中地点で爆発します。", "蓄力0.8秒。满蓄力射击在命中处爆炸。") },
        { "두 총구에서 동시에 발사합니다 (탄약 소모는 그대로).", L("Fires from both barrels at once (same ammo use).", "両方の銃口から同時に発射します(弾薬消費はそのまま)。", "两把枪同时开火(弹药消耗不变)。") },
        { "열이 40% 덜 오르고 불길 화상 피해가 강해집니다.", L("40% less heat and stronger burn damage.", "熱が40%上がりにくくなり、炎の燃焼ダメージが強くなります。", "发热降低40%，燃烧伤害增强。") },
        { "한 번에 유도탄 2발을 쏩니다.", L("Fires 2 homing shots at once.", "一度に誘導弾を2発撃ちます。", "一次发射2发导弹。") },
        { "번개가 7번 튀고, 튈 때 피해가 덜 줄어듭니다.", L("Lightning jumps 7 times and loses less damage per jump.", "雷が7回飛び、飛ぶたびのダメージ減少が小さくなります。", "闪电弹射7次，每次弹射伤害衰减更少。") },
        { "낫이 더 커지고 더 멀리 날아가며 피해 220%.", L("Bigger scythe that flies farther, 220% damage.", "鎌が大きくなり遠くまで飛び、ダメージ220%。", "镰刀更大、飞得更远，伤害220%。") },
        { "폭발 후 작은 용암탄 3개로 흩어집니다.", L("Splits into 3 small lava bombs after exploding.", "爆発後、小さな溶岩弾3つに分かれます。", "爆炸后分裂成3颗小熔岩弹。") },
        { "쿨타임 1.8초. 도착 지점에서 충격파가 터집니다.", L("1.8s cooldown. A shockwave bursts where you land.", "クールタイム1.8秒。到着地点で衝撃波が炸裂します。", "冷却1.8秒。在落点爆发冲击波。") },
        { "장판이 더 넓고 6초 동안 지속됩니다. 쿨타임 9초.", L("Wider field that lasts 6s. 9s cooldown.", "フィールドが広くなり6秒間持続します。クールタイム9秒。", "领域更大，持续6秒。冷却9秒。") },
        { "적이 75% 느려지고 7초 동안 지속됩니다.", L("Enemies are 75% slower for 7s.", "敵が75%遅くなり7秒間持続します。", "敌人减速75%，持续7秒。") },
        { "체력을 잃지 않고 12초 동안 지속됩니다.", L("No HP cost and lasts 12s.", "体力を失わず12秒間持続します。", "不消耗生命，持续12秒。") },
        { "영혼 3개부터 쓸 수 있고 폭발 범위가 넓어집니다.", L("Usable from 3 souls with a larger blast.", "魂3つから使え、爆発範囲が広がります。", "3个灵魂即可使用，爆炸范围更大。") },
        { "해골 5마리를 부르고 쿨타임 10초.", L("Summons 5 skeletons, 10s cooldown.", "スケルトンを5体呼び、クールタイム10秒。", "召唤5具骷髅，冷却10秒。") },
        { "분신이 5초 동안 남고 사라질 때 폭발합니다.", L("The decoy lasts 5s and explodes when it fades.", "分身が5秒間残り、消える時に爆発します。", "分身持续5秒，消失时爆炸。") },
        { "쿨타임 2초, 갈고리 피해 300%.", L("2s cooldown, 300% hook damage.", "クールタイム2秒、フックダメージ300%。", "冷却2秒，钩索伤害300%。") },
        { "영혼이 5개로 늘고 피해가 강해집니다.", L("5 orbs with stronger damage.", "魂が5つに増え、ダメージが強くなります。", "灵魂增至5个，伤害增强。") },
        { "반격 범위와 피해가 크게 늘어납니다.", L("Much larger counterattack radius and damage.", "反撃範囲とダメージが大きく増えます。", "反击范围和伤害大幅提升。") },
        { "탄창의 마지막 두 발이 저주탄이 됩니다.", L("The last two bullets become cursed.", "弾倉の最後の2発が呪い弾になります。", "弹匣最后两发成为诅咒弹。") },
        { "두 번 부활하고, 부활할 때 체력 50%로 일어납니다.", L("Revive twice, getting up with 50% HP.", "2回復活し、復活時は体力50%で起き上がります。", "可复活两次，复活时恢复50%生命。") },

        // ================================================================= 특수 능력 상태 글자
        { "낫 준비", L("Scythe ready", "鎌 準備完了", "镰刀就绪") },
        { "낫 회수 중", L("Scythe returning", "鎌 回収中", "镰刀回收中") },
        { "완충!", L("Full charge!", "フルチャージ！", "蓄满！") },
        { "충전 ", L("Charge ", "チャージ ", "蓄力 ") },
        { "냉각 완료", L("Cooled down", "冷却完了", "冷却完成") },
        { "과열!", L("Overheated!", "オーバーヒート！", "过热！") },
        { "열기 ", L("Heat ", "熱 ", "热量 ") },
        { "시간 왜곡!", L("Time Warp!", "時間歪曲！", "时间扭曲！") },
        { "희생의 계약! 공격력 2배", L("Blood Pact! Double damage", "犠牲の契約！攻撃力2倍", "牺牲契约！攻击力2倍") },
        { "영혼 부족 ", L("Not enough souls ", "魂が足りない ", "灵魂不足 ") },
        { "해골 소환!", L("Skeletons!", "スケルトン召喚！", "召唤骷髅！") },
        { "저주탄 장전!", L("Cursed round loaded!", "呪い弾 装填！", "诅咒弹上膛！") },
        { "계약 종료", L("Pact ended", "契約終了", "契约结束") },
        { "가시 반격!", L("Thorns!", "棘の反撃！", "荆棘反击！") },
        { "불사의 맹세가 발동했다!", L("Oath of Undying activated!", "不死の誓いが発動した！", "不死誓约发动了！") },
        { "영혼 폭발 준비", L("Soul Burst ready", "ソウルバースト準備完了", "灵魂爆发就绪") },
        { "무기  [Q] 교체  [R] 장전", L("Weapons  [Q] Swap  [R] Reload", "武器  [Q] 切替  [R] リロード", "武器  [Q] 切换  [R] 换弹") },
        { "스킬", L("Skills", "スキル", "技能") },
        { "패시브", L("Passives", "パッシブ", "被动") },
        { "사용 중 · ", L("In hand · ", "使用中・", "使用中 · ") },
        { "과열", L("Overheated", "過熱", "过热") },
        { "준비", L("Ready", "準備完了", "就绪") },
        { "회수 중", L("Returning", "回収中", "回收中") },
        { "] 준비", L("] Ready", "] 準備完了", "] 就绪") },
        { " · 영혼 ", L(" · Souls ", "・魂 ", " · 灵魂 ") },
        { "부활 ", L("Revives ", "復活 ", "复活 ") },
        { "사용함", L("Used", "使用済み", "已使用") },
        { "장전 중", L("Reloading", "リロード中", "换弹中") },

        // ================================================================= 스킬 트리
        { "무기  [Q] 교체", L("Weapons  [Q] Swap", "武器  [Q] 切替", "武器  [Q] 切换") },
        { "패시브  항상 적용", L("Passives  Always on", "パッシブ  常時発動", "被动  始终生效") },
        { "스킬  [{SKILL1}] 사용", L("Skills  [{SKILL1}] Use", "スキル  [{SKILL1}] 使用", "技能  [{SKILL1}] 使用") },
        { "선택을 취소했습니다.", L("Selection cancelled.", "選択を取り消しました。", "已取消选择。") },
        { "이미 진화한 능력입니다.", L("Already evolved.", "すでに進化した能力です。", "该能力已进化。") },
        { "스킬 칸({SKILL1} · {SKILL2} · {SKILL3})이 가득 찼습니다. 가진 스킬을 진화시켜 보세요.", L("Skill slots ({SKILL1} · {SKILL2} · {SKILL3}) are full. Try evolving a skill you have.", "スキル枠({SKILL1}・{SKILL2}・{SKILL3})がいっぱいです。持っているスキルを進化させてみましょう。", "技能栏({SKILL1} · {SKILL2} · {SKILL3})已满。试试进化已有的技能。") },
        { "포인트를 모두 썼습니다. 다른 능력을 먼저 취소하세요.", L("No points left. Cancel another ability first.", "ポイントを使い切りました。先に他の能力を取り消してください。", "点数已用完。请先取消其他能力。") },
        { "진화 완료", L("Evolved", "進化完了", "已进化") },
        { "진화!", L("Evolve!", "進化！", "进化！") },
        { "진화 가능", L("Can evolve", "進化可能", "可进化") },
        { "진화: ", L("Evolve: ", "進化: ", "进化: ") },
        { "강화 완료", L("Upgrade", "強化完了", "强化完成") },
        { "포인트 ", L("Points ", "ポイント ", "点数 ") },
        { "선택 완료", L("Confirm", "選択完了", "确认选择") },
        { "남은 포인트 ", L("Points left ", "残りポイント ", "剩余点数 ") },
        { "특수 능력 포인트 ", L("Special points ", "特殊能力ポイント ", "特殊能力点数 ") },
        { "새 능력을 배우거나 가진 능력을 진화", L("Learn a new ability or evolve one you have", "新しい能力を覚えるか、持っている能力を進化", "学习新能力或进化已有能力") },
        { "파란 테두리는 이미 가진 능력입니다. 한 번 더 고르면 진화해서 더 강해집니다. 남은 포인트는 아껴 두었다가 나중에 써도 됩니다.", L("Abilities with a blue frame are ones you own. Pick them again to evolve them. You can save leftover points for later.", "青い枠はすでに持っている能力です。もう一度選ぶと進化して強くなります。残ったポイントは取っておいて後で使えます。", "蓝框表示已拥有的能力。再次选择即可进化变强。剩余点数可以留到以后使用。") },
        { "능력 ", L("Choose ", "能力を ", "请选择 ") },
        { "개를 고르세요", L(" abilities", "つ選んでください", "项能力") },
        { "개 · 노드를 눌러 선택", L(" · click nodes to choose", "つ・ノードを押して選択", "点 · 点击节点选择") },
        { "무기는 {SWAP}로 기본 권총과 번갈아 쓰고, 스킬은 고른 순서대로 {SKILL1} · {SKILL2} · {SKILL3}에 배정됩니다. 다시 누르면 선택이 취소됩니다.", L("Swap weapons with the pistol using {SWAP}; skills go to {SKILL1} · {SKILL2} · {SKILL3} in the order you pick them. Click again to cancel.", "武器は{SWAP}で基本拳銃と切り替え、スキルは選んだ順に{SKILL1}・{SKILL2}・{SKILL3}に割り当てられます。もう一度押すと選択を取り消します。", "武器用{SWAP}与基础手枪切换，技能按选择顺序分配到{SKILL1} · {SKILL2} · {SKILL3}。再次点击取消选择。") },
        { " → 진화", L(" → Evolve", " → 進化", " → 进化") },
        { "  (선택됨)", L("  (selected)", "  (選択中)", "  (已选择)") },
        { "  (진화 완료)", L("  (evolved)", "  (進化済み)", "  (已进化)") },
        { "<color=#9fd8ff>진화</color>  ", L("<color=#9fd8ff>Evolve</color>  ", "<color=#9fd8ff>進化</color>  ", "<color=#9fd8ff>进化</color>  ") },
        { "무기 · {SWAP}로 교체", L("Weapon · Swap with {SWAP}", "武器・{SWAP}で切替", "武器 · {SWAP}切换") },
        { "스킬 · {SKILL1}/{SKILL2}/{SKILL3}", L("Skill · {SKILL1}/{SKILL2}/{SKILL3}", "スキル・{SKILL1}/{SKILL2}/{SKILL3}", "技能 · {SKILL1}/{SKILL2}/{SKILL3}") },
        { "패시브 · 항상 적용", L("Passive · Always on", "パッシブ・常時発動", "被动 · 始终生效") },

        // ================================================================= 능력치 창
        { "공격력", L("Attack", "攻撃力", "攻击力") },
        { "방어력", L("Defense", "防御力", "防御力") },
        { "공격 속도", L("Fire Rate", "攻撃速度", "攻击速度") },
        { "재장전", L("Reload", "リロード", "换弹") },
        { "이동 속도", L("Move Speed", "移動速度", "移动速度") },
        { "능력치", L("Stats", "ステータス", "属性") },
        { "눌러서 능력치 창을 열고 닫습니다.", L("Click to open or close the stats panel.", "押してステータス画面を開閉します。", "点击打开或关闭属性面板。") },
        { "/초", L("/s", "/秒", "/秒") },
        // ================================================================= 튜토리얼
        { "기본 조작", L("Basic Controls", "基本操作", "基本操作") },
        { "이동", L("Move", "移動", "移动") },
        { "좌클릭", L("Left Click", "左クリック", "左键") },
        { "우클릭", L("Right Click", "右クリック", "右键") },
        { "마우스 방향으로 사격", L("Shoot toward the cursor", "マウスの方向に射撃", "朝鼠标方向射击") },
        { "무기 교체 (특수 무기를 얻은 뒤)", L("Swap weapons (after getting special weapons)", "武器切替(特殊武器を手に入れた後)", "切换武器(获得特殊武器后)") },
        { "일시정지 · 설정", L("Pause · Settings", "一時停止・設定", "暂停 · 设置") },
        { "필살기", L("Ultimates", "必殺技", "必杀技") },
        { "스킬 게이지", L("Skill Gauge", "スキルゲージ", "技能能量") },
        { "시간이 지나면 차고, 적을 처치하면 잠깐 더 빨리 찹니다", L("Fills over time, and faster for a moment after each kill", "時間で溜まり、敵を倒すと少しの間速く溜まります", "随时间积累，击杀后短时间积累更快") },
        { "게이지가 가득 차면 필살기를 씁니다", L("Use your ultimate when the gauge is full", "ゲージが満タンになったら必殺技を使います", "能量满时释放必杀技") },
        { "조준형", L("Aimed", "照準型", "瞄准型") },
        { "누르고 있으면 시간이 느려지며 적을 조준, 떼면 발동", L("Hold to slow time and mark enemies, release to fire", "押し続けると時間が遅くなり敵を狙い、離すと発動", "按住时时间变慢并锁定敌人，松开释放") },
        { "즉발형", L("Instant", "即発型", "瞬发型") },
        { "산탄총 · 쌍권총 · 유탄은 누르는 즉시 발동", L("Shotgun · Twin Pistols · Grenade fire instantly", "ショットガン・二丁拳銃・グレネードは押した瞬間に発動", "霰弹枪 · 双枪 · 榴弹按下即释放") },
        { "성장", L("Growth", "成長", "成长") },
        { "레벨업", L("Level Up", "レベルアップ", "升级") },
        { "카드를 클릭해 고르고 {INTERACT}로 확정", L("Click a card and press {INTERACT} to confirm", "カードをクリックして選び、{INTERACT}で決定", "点击卡牌选择，按{INTERACT}确认") },
        { "상점 제단", L("Shop Altar", "ショップの祭壇", "商店祭坛") },
        { "적 35마리마다 나타남 · 다가가서 {INTERACT}로 열기", L("Appears every 35 kills · walk up and press {INTERACT}", "敵35体ごとに出現・近づいて{INTERACT}で開く", "每击杀35个敌人出现 · 靠近后按{INTERACT}打开") },
        { "능력치 · 무기 강화 · 스킬 강화", L("Stats · Weapon upgrades · Skill upgrades", "ステータス・武器強化・スキル強化", "属性 · 武器强化 · 技能强化") },
        { "코인", L("Coins", "コイン", "金币") },
        { "적이 떨어뜨림 · 코인 자석 능력으로 끌어올 수 있음", L("Dropped by enemies · pull them in with Coin Magnet", "敵が落とす・コインマグネットで引き寄せられる", "敌人掉落 · 可用金币磁铁吸引") },
        { "특수 능력", L("Special Abilities", "特殊能力", "特殊能力") },
        { "1장 보스를 쓰러뜨리고 문에 들어가면 특수 능력 3개를 고릅니다", L("Beat the chapter 1 boss and enter the gate to pick 3 special abilities", "第1章のボスを倒して門に入ると特殊能力を3つ選びます", "击败第1章首领并进入大门后，选择3项特殊能力") },
        { "무기 · 스킬 · 패시브", L("Weapons · Skills · Passives", "武器・スキル・パッシブ", "武器 · 技能 · 被动") },
        { "무기는 {SWAP}로 교체, 스킬은 {SKILL1} · {SKILL2} · {SKILL3}", L("Swap weapons with {SWAP}; skills on {SKILL1} · {SKILL2} · {SKILL3}", "武器は{SWAP}で切替、スキルは{SKILL1}・{SKILL2}・{SKILL3}", "武器用{SWAP}切换，技能用{SKILL1} · {SKILL2} · {SKILL3}") },
        { "특수 강화 ({UPGRADE})", L("Special Upgrade ({UPGRADE})", "特殊強化 ({UPGRADE})", "特殊强化 ({UPGRADE})") },
        { "중간 보스를 잡으면 포인트 · 새 능력을 배우거나 가진 능력을 진화", L("Mid-bosses give points · learn new abilities or evolve yours", "中ボスを倒すとポイント・新しい能力を覚えるか持っている能力を進化", "击败中头目获得点数 · 学习新能力或进化已有能力") },
        { "적과 보스", L("Enemies & Bosses", "敵とボス", "敌人与首领") },
        { "경고 표시", L("Warnings", "警告表示", "警告标记") },
        { "붉은 원 · 선 · 머리 위 ! 가 보이면 그 자리를 피하세요", L("Red circles, lines and a ! above heads mean: get out of the way", "赤い円・線・頭上の！が見えたらその場から離れましょう", "看到红圈、红线或头顶的！就快躲开") },
        { "중간 보스", L("Mid-bosses", "中ボス", "中头目") },
        { "2장부터 단계가 오를 때마다 등장 · 특수 능력 포인트를 줌", L("From chapter 2, one appears each time the phase rises · gives a special point", "第2章から段階が上がるたびに出現・特殊能力ポイントをくれる", "从第2章起每次阶段提升时出现 · 给予特殊能力点数") },
        { "보스", L("Bosses", "ボス", "首领") },
        { "리치 왕 → 지옥의 군주 → 킹 슬라임", L("Lich King → Demon Lord → King Slime", "リッチ王 → 地獄の君主 → キングスライム", "巫妖王 → 地狱领主 → 史莱姆王") },
        { "특수 스킬", L("Special Skills", "特殊スキル", "特殊技能") },
        { "보스는 체력이 절반 아래로 떨어지면 특수 스킬을 씁니다", L("Bosses use a special skill below half HP", "ボスは体力が半分を切ると特殊スキルを使います", "首领生命低于一半时会使用特殊技能") },
        { "목표", L("Goal", "目標", "目标") },
        { "3개의 스테이지", L("Three Stages", "3つのステージ", "三个关卡") },
        { "지하 묘역 → 불타는 지옥 → 초원", L("Catacombs → Burning Hell → Meadow", "地下墓所 → 燃える地獄 → 草原", "地下墓穴 → 燃烧地狱 → 草原") },
        { "문", L("Gates", "門", "大门") },
        { "보스를 쓰러뜨리면 30초 안에 문으로 들어가세요", L("After beating a boss, enter the gate within 30 seconds", "ボスを倒したら30秒以内に門に入りましょう", "击败首领后请在30秒内进入大门") },
        { "행운을 빌어요!", L("Good luck!", "幸運を祈ります！", "祝你好运！") },
        { "모든 보스를 쓰러뜨리면 승리합니다", L("Defeat every boss to win", "全てのボスを倒せば勝利です", "击败所有首领即可获胜") },
        // 도감 · 보스 이름
        { "도감", L("Codex", "図鑑", "图鉴") },
        { "적", L("Enemies", "敵", "敌人") },
        { "무기", L("Weapons", "武器", "武器") },
        { "진화", L("Evolution", "進化", "进化") },
        { "스테이지마다 나오는 적과 스킬 · 붉은 경고가 보이면 피하세요", L("Enemies of each stage and their skills · dodge when you see a red warning", "ステージごとの敵とスキル・赤い警告が見えたら避けよう", "各关卡的敌人与技能 · 看到红色警告就躲开") },
        { "각 스테이지의 마지막 적 · 체력이 절반 아래로 떨어지면 특수 스킬을 씁니다", L("The final foe of each stage · uses a special skill below half health", "各ステージ最後の敵・体力が半分を切ると特殊スキルを使う", "每关的最终敌人 · 生命低于一半时使用特殊技能") },
        { "{SWAP}로 교체 · 우클릭 필살기는 무기마다 다릅니다", L("Swap with {SWAP} · each weapon has its own right-click ultimate", "{SWAP}で切り替え・右クリックの必殺技は武器ごとに違う", "按{SWAP}切换 · 每把武器的右键必杀技都不同") },
        { "{SKILL1} · {SKILL2} · {SKILL3} 순서로 배정 (최대 3개)", L("Bound to {SKILL1} · {SKILL2} · {SKILL3} in order (up to 3)", "{SKILL1}・{SKILL2}・{SKILL3}の順に割り当て（最大3つ）", "依次绑定到 {SKILL1} · {SKILL2} · {SKILL3}（最多3个）") },
        { "고르면 항상 적용되는 능력", L("Always active once chosen", "選ぶと常に効果がある能力", "选择后始终生效的能力") },
        { "특수 강화({UPGRADE})에서 이미 가진 능력을 한 번 더 고르면 진화합니다", L("Pick an ability you already own again in Special Upgrade ({UPGRADE}) to evolve it", "特殊強化({UPGRADE})で持っている能力をもう一度選ぶと進化する", "在特殊强化({UPGRADE})中再次选择已拥有的能力即可进化") },
        { "레벨이 오를 때 세 장의 카드 중 하나를 고릅니다", L("Choose one of three cards when you level up", "レベルアップ時に3枚のカードから1枚選ぶ", "升级时从三张卡中选择一张") },
        { "상점 제단(적 35마리마다)에서 코인으로 강화합니다", L("Upgrade with coins at the shop altar (every 35 kills)", "ショップの祭壇（敵35体ごと）でコインを使って強化", "在商店祭坛（每击杀35个敌人）用金币强化") },
        { "지하 묘역", L("Catacombs", "地下墓所", "地下墓穴") },
        { "불타는 지옥", L("Burning Hell", "燃える地獄", "燃烧地狱") },
        { "초원", L("Meadow", "草原", "草原") },
        { "해골", L("Skeleton", "スケルトン", "骷髅") },
        { "지하 묘역의 기본 적. 스킬 없이 곧장 달려듭니다.", L("The basic foe of the Catacombs. Charges straight at you, no skills.", "地下墓所の基本の敵。スキルなしでまっすぐ突っ込んでくる。", "地下墓穴的基本敌人。没有技能，直接冲过来。") },
        { "구울", L("Ghoul", "グール", "食尸鬼") },
        { "떨어질 곳에 원을 띄운 뒤 높이 뛰어 내려찍습니다.", L("Marks a circle where it will land, then leaps high and slams down.", "着地点に円を表示してから高く跳び、叩きつける。", "先在落点显示圆圈，再高高跃起砸下。") },
        { "망령", L("Wraith", "亡霊", "怨灵") },
        { "사라졌다가 표시한 곳에 나타나며 영혼 폭발을 일으킵니다.", L("Vanishes, reappears at a marked spot and unleashes a soul burst.", "消えてから印の場所に現れ、魂の爆発を起こす。", "消失后在标记处出现，引发灵魂爆炸。") },
        { "임프", L("Imp", "インプ", "小恶魔") },
        { "지그재그로 움직이며 플레이어 자리에 X자 레이저를 쏩니다.", L("Zigzags around and fires an X-shaped laser at your position.", "ジグザグに動き、プレイヤーの位置にX字レーザーを撃つ。", "之字形移动，向玩家位置发射X形激光。") },
        { "불꽃 해골", L("Flame Skull", "炎のドクロ", "火焰骷髅") },
        { "가까이 오면 부풀어 오르다 폭발합니다.", L("Swells up when close, then explodes.", "近づくと膨らんで爆発する。", "靠近后膨胀并爆炸。") },
        { "지옥견", L("Hellhound", "ヘルハウンド", "地狱犬") },
        { "경로를 보여준 뒤 일직선으로 돌진합니다.", L("Shows its path, then dashes in a straight line.", "進路を示してから一直線に突進する。", "显示路线后直线冲刺。") },
        { "용암 골렘", L("Lava Golem", "溶岩ゴーレム", "熔岩魔像") },
        { "점점 넓어지는 세 번의 지면 파동을 일으킵니다.", L("Sends out three ever-widening ground shockwaves.", "だんだん広がる3回の地面の波動を起こす。", "释放三次逐渐扩大的地面冲击波。") },
        { "악마 기사", L("Demon Knight", "悪魔の騎士", "恶魔骑士") },
        { "칼날을 휘감고 회전하며 플레이어 쪽으로 미끄러집니다.", L("Spins wrapped in blades and slides toward you.", "刃をまとって回転し、プレイヤーの方へ滑り込む。", "裹挟刀刃旋转，向玩家滑行。") },
        { "초원 슬라임", L("Meadow Slime", "草原スライム", "草原史莱姆") },
        { "밟으면 아픈 산성 웅덩이를 남깁니다.", L("Leaves acid puddles that hurt to step on.", "踏むと痛い酸の水たまりを残す。", "留下踩到会受伤的酸液水洼。") },
        { "거대 벌", L("Giant Bee", "巨大バチ", "巨型蜜蜂") },
        { "플레이어 주변에 꽃가루 구름을 뿌립니다. 안에 있으면 느려지고 조금씩 아픕니다.", L("Spreads pollen clouds around you. Inside, you slow down and take small damage.", "プレイヤーの周りに花粉の雲をまく。中にいると遅くなり少しずつダメージ。", "在玩家周围散布花粉云。身处其中会减速并持续受伤。") },
        { "버섯 거인", L("Mushroom Brute", "キノコの巨人", "蘑菇巨人") },
        { "주변에 버섯 지뢰를 심고 잠시 뒤 차례로 터뜨립니다.", L("Plants mushroom mines nearby that burst one after another.", "周りにキノコ地雷を植え、しばらくして順に爆発させる。", "在周围种下蘑菇地雷，片刻后依次引爆。") },
        { "다이어울프", L("Dire Wolf", "ダイアウルフ", "恐狼") },
        { "울부짖어 주변 적을 잠시 빠르게 만듭니다.", L("Howls to briefly speed up nearby enemies.", "遠吠えで周りの敵を一時的に速くする。", "嚎叫让周围的敌人暂时加速。") },
        { "트렌트", L("Treant", "トレント", "树人") },
        { "플레이어 쪽으로 뿌리 가시를 차례로 솟게 합니다.", L("Raises a line of root spikes toward you.", "プレイヤーの方へ根のトゲを次々と突き出す。", "朝玩家方向依次升起根刺。") },
        { "2장부터", L("From Stage 2", "第2章から", "第2章起") },
        { "단계가 오를 때마다 크고 단단한 적이 나타납니다. 체력 12배 · 피해 1.5배. 쓰러뜨리면 특수 능력 포인트를 줍니다.", L("A big, tough enemy appears at each new phase. 12× health · 1.5× damage. Drops a special ability point.", "段階が上がるたびに大きく硬い敵が現れる。体力12倍・ダメージ1.5倍。倒すと特殊能力ポイントがもらえる。", "每进入新阶段都会出现高大坚硬的敌人。生命×12 · 伤害×1.5。击败后获得特殊能力点。") },
        { "리치 왕", L("Lich King", "リッチ王", "巫妖王") },
        { "지옥의 군주", L("Demon Lord", "地獄の君主", "地狱领主") },
        { "킹 슬라임", L("King Slime", "キングスライム", "史莱姆王") },
        { "지하 묘역의 주인", L("Master of the Catacombs", "地下墓所の主", "地下墓穴之主") },
        { "불타는 지옥의 왕", L("King of the Burning Hell", "燃える地獄の王", "燃烧地狱之王") },
        { "초원의 폭군", L("Tyrant of the Meadow", "草原の暴君", "草原暴君") },
        { "감히 내 잠든 묘역을 깨우다니...", L("How dare you wake my sleeping catacombs...", "よくも眠れる墓所を目覚めさせたな……", "竟敢惊醒我沉睡的墓穴……") },
        { "네 영혼도 내 망자의 군대에 더해 주마!", L("Your soul shall join my army of the dead!", "貴様の魂も死者の軍勢に加えてやろう！", "你的灵魂也将加入我的亡者大军！") },
        { "하찮은 인간이 지옥의 문턱을 넘었군.", L("A worthless human has crossed the threshold of Hell.", "取るに足らぬ人間が地獄の門をくぐったか。", "卑微的人类竟跨过了地狱的门槛。") },
        { "불길 속에서 재가 되어라!", L("Burn to ashes in my flames!", "炎の中で灰となれ！", "在烈焰中化为灰烬吧！") },
        { "뿌요... 이 초원은 이 몸의 식탁이다!", L("Puyo... This meadow is my dinner table!", "ぷよ……この草原はわしの食卓だ！", "噗哟……这片草原是本大王的餐桌！") },
        { "납작하게 짓눌러 주마, 뿌요요옹!", L("I'll squash you flat, puyoyoooong!", "ぺしゃんこにしてやる、ぷよよ〜ん！", "把你压成肉饼，噗哟哟哟！") },
        { "부하를 부르며 망령의 손아귀 · 저주 표식 · 뼈 가시 격자를 씁니다.\n특수: 망자의 의식 - 영혼 등불이 돌며 나선 탄막을 쏜 뒤 대폭발", L("Summons minions and uses Wraith Grasp · Curse Mark · Bone Spike Grid.\nSpecial: Rite of the Dead - soul lanterns fire spiral barrages, then a huge blast", "手下を呼び、亡霊の手・呪いの印・骨のトゲ格子を使う。\n特殊：死者の儀式 - 魂の灯籠が回って螺旋弾幕を撃ち、大爆発", "召唤手下，使用怨灵之握 · 诅咒印记 · 骨刺网格。\n特殊：亡者仪式 - 灵魂灯笼旋转发射螺旋弹幕，随后大爆炸") },
        { "화염 돌진 · 운석 낙하 · 화염 파동(틈으로 피하세요)을 씁니다.\n특수: 십자 불길 - 네 줄기 불기둥이 천천히 회전", L("Uses Flame Charge · Meteor Fall · Fire Wave (escape through the gap).\nSpecial: Cross Inferno - four pillars of fire slowly rotate", "炎の突進・隕石落下・炎の波動（隙間から避けよう）を使う。\n特殊：十字の業火 - 4本の火柱がゆっくり回転", "使用火焰冲锋 · 陨石坠落 · 火焰波（从缺口躲避）。\n特殊：十字烈焰 - 四道火柱缓慢旋转") },
        { "대점프 · 산성 비 · 구르기 돌진을 씁니다. 쓰러질 때마다 작고 빠르게 분열합니다 (1 → 2 → 3마리).\n특수: 슬라임 폭우 - 빠른 대점프 3연속", L("Uses Big Jump · Acid Rain · Rolling Charge. Splits into smaller, faster slimes each time it falls (1 → 2 → 3).\nSpecial: Slime Storm - three quick big jumps in a row", "大ジャンプ・酸の雨・転がり突進を使う。倒れるたびに小さく速く分裂する（1 → 2 → 3体）。\n特殊：スライム豪雨 - 素早い大ジャンプ3連続", "使用大跳跃 · 酸雨 · 翻滚冲锋。每次倒下都会分裂成更小更快的史莱姆（1 → 2 → 3只）。\n特殊：史莱姆暴雨 - 连续三次快速大跳跃") },
        { "마우스 쪽으로 거대한 부채꼴 폭발을 3번 연달아 일으킵니다.", L("Unleashes three huge cone-shaped blasts toward the mouse.", "マウスの方へ巨大な扇形の爆発を3連続で起こす。", "向鼠标方向连续引发三次巨大扇形爆炸。") },
        { "우클릭을 누른 채 방향을 정하면 충전 뒤 화면을 가로지르는 굵은 광선을 쏩니다. 광선 위의 적이 많을수록 강합니다.", L("Hold right-click to aim; after charging, fires a thick beam across the screen. Stronger the more enemies it hits.", "右クリックを押したまま方向を決めると、チャージ後に画面を横切る太い光線を撃つ。光線上の敵が多いほど強い。", "按住右键决定方向，充能后发射横贯屏幕的粗光束。光束上的敌人越多越强。") },
        { "두 줄기 나선으로 사방에 총알을 난사합니다. 움직이며 쓸 수 있습니다.", L("Sprays bullets everywhere in a double spiral. You can move while using it.", "2本の螺旋で四方に弾を乱射する。動きながら使える。", "以双螺旋向四周扫射子弹。可以边移动边使用。") },
        { "우클릭을 누른 채 자리를 정하면 불기둥이 생겨 적을 빨아들이고 태웁니다.", L("Hold right-click to pick a spot; a fire tornado appears, pulling in and burning enemies.", "右クリックを押したまま場所を決めると、火柱が現れて敵を吸い込み燃やす。", "按住右键选择位置，生成火焰龙卷吸入并焚烧敌人。") },
        { "영혼 구슬들이 주위를 돌다 조준한 적에게 번갈아 달려듭니다.", L("Soul orbs circle you, then take turns rushing the targeted enemies.", "魂の玉が周りを回り、狙った敵に交互に飛びかかる。", "灵魂球环绕身边，轮流冲向锁定的敌人。") },
        { "먹구름이 따라다니며 조준한 적들에게 번개를 연달아 떨어뜨립니다.", L("A storm cloud follows you, dropping lightning on the targeted enemies.", "黒雲がついてきて、狙った敵に雷を次々と落とす。", "乌云跟随你，向锁定的敌人接连降下雷电。") },
        { "무적 상태로 조준한 적들 사이를 순간이동하며 벤 뒤 제자리로 돌아옵니다.", L("Invincible, you teleport between targeted enemies slashing them, then return to where you started.", "無敵状態で狙った敵の間を瞬間移動して斬り、元の場所に戻る。", "无敌状态下在锁定的敌人之间瞬移斩击，然后回到原位。") },
        { "플레이어에서 마우스 쪽으로 줄지어 운석이 떨어집니다.", L("Rows of meteors rain down from you toward the mouse.", "プレイヤーからマウスの方へ隕石が列になって落ちる。", "陨石从玩家向鼠标方向成排落下。") },
        { "총알이 적을 1마리 더 관통합니다.", L("Bullets pierce one more enemy.", "弾が敵をもう1体貫通する。", "子弹多穿透1个敌人。") },
        { "적이 코인을 1개 더 떨어뜨립니다.", L("Enemies drop one more coin.", "敵がコインをもう1枚落とす。", "敌人多掉落1枚金币。") },
        { "스킬 게이지가 20% 줄어 필살기를 더 자주 씁니다.", L("Skill gauge is 20% shorter, so you ult more often.", "スキルゲージが20%短くなり、必殺技をより頻繁に使える。", "技能槽缩短20%，更频繁地使用必杀技。") },
        { "필살기를 조준하는 동안 타겟이 된 적이 20% 더 느려집니다.", L("Targeted enemies are 20% slower while you aim your ultimate.", "必殺技の照準中、狙われた敵が20%さらに遅くなる。", "瞄准必杀技时，被锁定的敌人额外减速20%。") },
        { "처치 경험치가 10% 늘어납니다.", L("Kill EXP +10%.", "撃破経験値が10%増える。", "击杀经验+10%。") },
        { "주변의 코인을 끌어옵니다. 범위 +4 (최대 4번)", L("Pulls in nearby coins. Range +4 (up to 4 times)", "周りのコインを引き寄せる。範囲+4（最大4回）", "吸引附近的金币。范围+4（最多4次）") },
        { "한 번에 쏘는 총알이 1발 늘지만 한 발당 피해는 줄어듭니다.", L("Fire one more bullet per shot, but each deals less damage.", "一度に撃つ弾が1発増えるが、1発あたりのダメージは減る。", "每次多发射1颗子弹，但单发伤害降低。") },
        { "총알이 적을 밀어내는 힘 +25% (최대 3번)", L("Bullet knockback +25% (up to 3 times)", "弾のノックバック+25%（最大3回）", "子弹击退+25%（最多3次）") },
        { "체력을 모두 회복하고 최대 체력이 12% 늘어납니다.", L("Fully heals and raises max health by 12%.", "体力を全回復し、最大体力が12%増える。", "完全恢复生命，最大生命+12%。") },
        { "받는 피해 -12% (최대 3번)", L("Damage taken -12% (up to 3 times)", "受けるダメージ-12%（最大3回）", "受到伤害-12%（最多3次）") },
        { "시간이 지나면 체력이 회복됩니다. 초당 +0.5 (최대 4번)", L("Regenerate health over time. +0.5 per second (up to 4 times)", "時間とともに体力が回復する。毎秒+0.5（最大4回）", "随时间恢复生命。每秒+0.5（最多4次）") },
        { "적을 처치할 때마다 체력 +1 회복 (최대 3번)", L("Heal +1 health per kill (up to 3 times)", "敵を倒すたびに体力+1回復（最大3回）", "每击杀一个敌人恢复1点生命（最多3次）") },
        { "능력치 상점", L("Stat Shop", "ステータスショップ", "属性商店") },
        { "공격력 · 공격 속도 · 재장전 속도 · 탄창 · 이동 속도를 올립니다. 살수록 값이 오릅니다.", L("Raise attack · fire rate · reload speed · magazine · move speed. Prices rise as you buy.", "攻撃力・攻撃速度・リロード速度・弾倉・移動速度を上げる。買うほど値段が上がる。", "提升攻击力 · 攻击速度 · 装填速度 · 弹匣 · 移动速度。买得越多越贵。") },
        { "2장부터. 특수 무기마다 피해 · 연사 · 탄창 · 고유 특성을 올립니다.", L("From Stage 2. Raise damage · fire rate · magazine · a unique trait for each special weapon.", "第2章から。特殊武器ごとにダメージ・連射・弾倉・固有特性を上げる。", "第2章起。为每把特殊武器提升伤害 · 射速 · 弹匣 · 专属特性。") },
        { "필살기의 위력과 무기마다 다른 특성(타겟 수 · 지속 시간 등)을 올립니다.", L("Raise your ultimate's power and a per-weapon trait (targets · duration, etc.).", "必殺技の威力と武器ごとの特性（ターゲット数・持続時間など）を上げる。", "提升必杀技威力和各武器的特性（目标数 · 持续时间等）。") },
        { "특수 능력 포인트", L("Special Ability Points", "特殊能力ポイント", "特殊能力点") },
        { "중간 보스를 잡으면 얻습니다. T를 눌러 새 능력을 배우거나 가진 능력을 진화합니다.", L("Earned from mid-bosses. Press T to learn a new ability or evolve one you own.", "中ボスを倒すと手に入る。Tで新しい能力を覚えるか、持っている能力を進化させる。", "击败精英首领获得。按T学习新能力或进化已有能力。") },
        { "처음부터 가진 무기", L("Your starting weapon", "最初から持っている武器", "初始武器") },
        { "좌클릭으로 사격, R로 재장전.", L("Left-click to shoot, R to reload.", "左クリックで射撃、Rでリロード。", "左键射击，R键装填。") },
        { "우클릭을 누른 채 적을 조준하고, 떼면 조준한 적들에게 한꺼번에 쏩니다.", L("Hold right-click to target enemies, release to fire at all of them at once.", "右クリックを押したまま敵を狙い、離すと狙った敵に一斉に撃つ。", "按住右键锁定敌人，松开后向所有锁定的敌人齐射。") },
        { "특수 무기", L("Special Weapon", "特殊武器", "特殊武器") },
        { "강화 특성", L("Upgrade Trait", "強化特性", "强化特性") },
        { "즉발", L("Instant", "即発", "瞬发") },
        { "조준", L("Aimed", "照準", "瞄准") },
        { "체력", L("HP", "体力", "生命") },
        { "속도", L("Speed", "速度", "速度") },
        { "접촉 피해", L("Contact Dmg", "接触ダメージ", "接触伤害") },
        // v3.1 캐릭터 이야기 · 검사 베기 · 도적 출혈 돌진
        { "떠돌이 기사는 녹슨 장검 한 자루를 등에 메고 무너진 신전 앞에 섰다.", L("The wandering knight stood before the ruined temple, a rusty longsword on his back.", "流浪の騎士は錆びた長剣を背負い、崩れた神殿の前に立った。", "流浪骑士背着一把生锈的长剑，站在了倒塌的神殿前。") },
        { "총알은 떨어져도, 칼날은 떨어지지 않는다.", L("Bullets run out. A blade never does.", "弾は尽きても、刃は尽きない。", "子弹会打光，剑刃却不会。") },
        { "기사는 망설임 없이 어둠 속으로 뛰어내렸다.", L("Without hesitation, the knight leapt into the dark.", "騎士はためらうことなく闇の中へ飛び降りた。", "骑士毫不犹豫地跳入了黑暗之中。") },
        { "그림자 칼날이라 불리는 도적은 신전 지하에 잠든 보물 이야기를 들었다.", L("The rogue called the Shadow Blade had heard of treasure sleeping beneath the temple.", "影の刃と呼ばれる盗賊は、神殿の地下に眠る宝の噂を聞いた。", "人称暗影之刃的盗贼，听说了沉睡在神殿地下的宝藏。") },
        { "망자든 악마든, 등을 보인 놈부터 쓰러진다.", L("Undead or demon, whoever turns their back falls first.", "亡者でも悪魔でも、背中を見せた奴から倒れる。", "无论亡者还是恶魔，先露出后背的先倒下。") },
        { "도적은 소리 없이 구멍 아래로 몸을 날렸다.", L("Without a sound, the rogue dropped into the hole.", "盗賊は音もなく穴の底へ身を躍らせた。", "盗贼悄无声息地跃入了洞中。") },
        { "숲의 사냥꾼은 죽은 짐승들이 숲을 떠나 신전으로 향하는 것을 보았다.", L("The forest hunter watched dead beasts leave the woods and head for the temple.", "森の狩人は、死んだ獣たちが森を離れ神殿へ向かうのを見た。", "森林猎人看见死去的野兽离开森林，走向神殿。") },
        { "흔적을 따라가자, 무너진 신전의 구멍이 나타났다.", L("Following the tracks, the hunter found a hole in the ruined temple.", "足跡を追うと、崩れた神殿の穴が現れた。", "循着踪迹，倒塌神殿的洞口出现在眼前。") },
        { "화살통은 가득하다. 이번 사냥감은 리치 왕이다.", L("The quiver is full. Today's quarry is the Lich King.", "矢筒は満杯だ。今回の獲物はリッチ王だ。", "箭筒已满。这次的猎物是巫妖王。") },
        { "미친 학자는 오히려 기뻤다. 되살아난 시체라니, 이렇게 좋은 재료가 또 있을까.", L("The mad scholar was delighted. Walking corpses — what finer ingredients could there be?", "狂った学者はむしろ喜んだ。蘇った屍なんて、これ以上の素材があるだろうか。", "疯狂学者反而很高兴。复活的尸体——还有比这更好的材料吗？") },
        { "플라스크를 허리춤에 가득 채우고, 학자는 신전의 구멍으로 뛰어들었다.", L("Belt packed with flasks, the scholar jumped into the temple's hole.", "腰にフラスコを詰め込み、学者は神殿の穴へ飛び込んだ。", "腰间挂满烧瓶，学者跳进了神殿的洞口。") },
        { "“자, 실험을 시작하지.”", L("\"Now then, let the experiment begin.\"", "「さて、実験を始めよう。」", "“那么，实验开始吧。”") },
        { "기사는 이 빠진 장검을 닦아 칼집에 꽂았다.", L("The knight wiped the notched longsword and sheathed it.", "騎士は刃こぼれした長剣を拭い、鞘に収めた。", "骑士擦净了满是缺口的长剑，收入鞘中。") },
        { "사람들은 총 한 자루 없이 세상을 구한 기사를 신기한 듯 바라보았다.", L("People stared in wonder at the knight who saved the world without a single gun.", "人々は銃ひとつ持たずに世界を救った騎士を不思議そうに見つめた。", "人们惊奇地望着这位没用一把枪就拯救了世界的骑士。") },
        { "“총이 아니어도 괜찮다. 지킬 수만 있다면.”", L("\"It needn't be a gun. So long as I can protect them.\"", "「銃でなくてもいい。守れさえすれば。」", "“不是枪也无妨。只要能守护就好。”") },
        { "도적은 리치 왕의 왕관을 슬쩍 품에 넣었다.", L("The rogue quietly slipped the Lich King's crown inside their coat.", "盗賊はリッチ王の王冠をこっそり懐に入れた。", "盗贼悄悄把巫妖王的王冠揣进了怀里。") },
        { "영웅의 이름을 물었을 때, 도적은 이미 그림자 속으로 사라진 뒤였다.", L("When people asked the hero's name, the rogue had already vanished into the shadows.", "英雄の名を尋ねたとき、盗賊はすでに影の中へ消えていた。", "当人们询问英雄的名字时，盗贼早已消失在阴影之中。") },
        { "다음 날, 왕궁의 보물 창고가 텅 비었다는 소문이 돌았다.", L("The next day, rumors spread that the royal treasury was empty.", "翌日、王宮の宝物庫が空っぽになったという噂が流れた。", "第二天，传出了王宫宝库被洗劫一空的传闻。") },
        { "사냥꾼은 마지막 화살을 거두어 화살통에 꽂았다.", L("The hunter gathered the last arrow and slid it back into the quiver.", "狩人は最後の矢を拾い、矢筒に収めた。", "猎人收回最后一支箭，插回箭筒。") },
        { "숲에는 다시 새소리가 돌아왔다.", L("Birdsong returned to the forest.", "森には再び鳥のさえずりが戻ってきた。", "森林里再次响起了鸟鸣。") },
        { "사람들은 숲의 사냥꾼에게 깊이 고개를 숙였다.", L("The people bowed deeply to the forest hunter.", "人々は森の狩人に深く頭を下げた。", "人们向森林猎人深深鞠躬。") },
        { "학자는 킹 슬라임의 점액을 플라스크에 담으며 킬킬 웃었다.", L("The scholar giggled while bottling the King Slime's goo.", "学者はキングスライムの粘液をフラスコに詰めながらクスクス笑った。", "学者一边把史莱姆王的黏液装进烧瓶，一边嘿嘿直笑。") },
        { "“이걸로 논문 세 편은 쓰겠군.”", L("\"That's three papers' worth of material, at least.\"", "「これで論文が三本は書けるな。」", "“这些够我写三篇论文了。”") },
        { "세상은 구해졌다. 대부분은 우연이었지만.", L("The world was saved. Mostly by accident.", "世界は救われた。ほとんどは偶然だったが。", "世界得救了。虽然大部分是出于偶然。") },
        { "검을 크게 휘둘러 앞쪽 부채꼴의 적을 직접 벱니다", L("Swing the sword wide to cut every enemy in a cone ahead", "剣を大きく振るい、前方の扇形の敵を直接斬ります", "大幅挥剑，直接斩击前方扇形范围内的敌人") },
        { "약하지만 빠른 표창 세례와 그림자 돌진으로 싸우는 암살자.", L("A frail assassin who fights with a hail of fast throwing stars and shadow dashes.", "非力だが素早い手裏剣の雨と影の突進で戦う暗殺者。", "虽然柔弱，却以飞快的飞镖和暗影突进作战的刺客。") },
        { "출혈 돌진", L("Bleeding Dash", "出血突進", "出血突进") },
        { "무적 상태로 마우스 방향으로 돌진해, 지나간 적에게 출혈 피해를 입힙니다 (즉발)", L("Dash toward the mouse while invincible, making every enemy you pass bleed (instant)", "無敵状態でマウスの方向へ突進し、通り過ぎた敵に出血ダメージを与えます（即発動）", "在无敌状态下朝鼠标方向突进，使途经的敌人流血（瞬发）") },
        { "높을수록 늦게 참", L("Higher = fills slower", "高いほど遅く溜まる", "越高积累越慢") },
        // v3.2 캐릭터 전용 레벨업 카드 · Soul Saver
        { "넓은 베기", L("Wide Swing", "広い斬撃", "横扫千军") },
        { "장검을 더 넓게 휘두릅니다.\n( 베는 각도 +30° )", L("Swing the longsword wider.\n( Swing angle +30° )", "長剣をより広く振るいます。\n( 斬る角度 +30° )", "更大幅度地挥舞长剑。\n( 斩击角度 +30° )") },
        { "회전 베기 수련", L("Spin Slash Training", "回転斬りの修練", "回旋斩修炼") },
        { "우클릭 회전 베기의 범위와 피해가 20% 커집니다.", L("Right-click Spin Slash range and damage +20%.", "右クリックの回転斬りの範囲とダメージが20%増加します。", "右键回旋斩的范围和伤害提高20%。") },
        { "긴 칼날", L("Long Blade", "長い刃", "长刃") },
        { "장검이 길어져 더 멀리 벱니다.\n( 사거리 +15% )", L("The longsword grows longer and cuts farther.\n( Range +15% )", "長剣が伸び、より遠くまで斬ります。\n( 射程 +15% )", "长剑变长，斩得更远。\n( 射程 +15% )") },
        { "날랜 손목", L("Quick Wrist", "素早い手首", "灵巧手腕") },
        { "장검을 더 빨리 휘두릅니다.\n( 공격 속도 +12% )", L("Swing the longsword faster.\n( Attack speed +12% )", "長剣をより速く振るいます。\n( 攻撃速度 +12% )", "更快地挥舞长剑。\n( 攻击速度 +12% )") },
        { "관통 표창", L("Piercing Stars", "貫通手裏剣", "穿透飞镖") },
        { "표창이 적을 하나 더 꿰뚫습니다.", L("Throwing stars pierce one more enemy.", "手裏剣が敵をもう1体貫通します。", "飞镖多穿透一个敌人。") },
        { "깊은 상처", L("Deep Wounds", "深い傷", "深重创伤") },
        { "우클릭 출혈 돌진의 피해와 출혈이 25% 강해집니다.", L("Right-click Bleeding Dash damage and bleed +25%.", "右クリックの出血突進のダメージと出血が25%強くなります。", "右键出血突进的伤害与流血提高25%。") },
        { "표창 한 움큼", L("Handful of Stars", "手裏剣ひとつかみ", "一把飞镖") },
        { "한 번에 던지는 표창이 1개 늘어나지만, 개당 피해는 줄어듭니다.", L("Throw one more star at a time, but each deals less damage.", "一度に投げる手裏剣が1つ増えますが、1つあたりのダメージは減ります。", "每次多投出1枚飞镖，但每枚伤害降低。") },
        { "큰 표창 주머니", L("Big Star Pouch", "大きな手裏剣袋", "大飞镖袋") },
        { "표창 탄창이 2발 늘어납니다.", L("Throwing star magazine +2.", "手裏剣の弾倉が2発増えます。", "飞镖弹匣+2。") },
        { "관통 화살", L("Piercing Arrows", "貫通の矢", "穿透箭") },
        { "화살이 적을 하나 더 꿰뚫습니다.", L("Arrows pierce one more enemy.", "矢が敵をもう1体貫通します。", "箭矢多穿透一个敌人。") },
        { "넓은 화살비", L("Wide Arrow Rain", "広い矢の雨", "广域箭雨") },
        { "우클릭 화살비의 범위와 화살 수가 20% 늘어납니다.", L("Right-click Arrow Rain area and arrow count +20%.", "右クリックの矢の雨の範囲と矢の数が20%増えます。", "右键箭雨的范围和箭数提高20%。") },
        { "연발 사격", L("Double Nock", "連発射撃", "连发射击") },
        { "한 번에 쏘는 화살이 1발 늘어나지만, 한 발당 피해는 줄어듭니다.", L("Fire one more arrow at a time, but each deals less damage.", "一度に射る矢が1本増えますが、1本あたりのダメージは減ります。", "每次多射出1支箭，但每支伤害降低。") },
        { "강한 시위", L("Strong Bowstring", "強い弦", "强弓弦") },
        { "화살 피해가 12% 늘어납니다.", L("Arrow damage +12%.", "矢のダメージが12%増えます。", "箭矢伤害提高12%。") },
        { "넓은 폭발", L("Wide Blast", "広い爆発", "广域爆炸") },
        { "플라스크 폭발 범위가 15% 커집니다.", L("Flask explosion radius +15%.", "フラスコの爆発範囲が15%広がります。", "烧瓶爆炸范围扩大15%。") },
        { "대폭발 연구", L("Big Blast Research", "大爆発の研究", "大爆炸研究") },
        { "우클릭 대폭발 플라스크의 범위와 피해가 20% 커집니다.", L("Right-click Mega Flask range and damage +20%.", "右クリックの大爆発フラスコの範囲とダメージが20%増加します。", "右键大爆炸烧瓶的范围和伤害提高20%。") },
        { "연속 투척", L("Rapid Toss", "連続投擲", "连续投掷") },
        { "한 번에 던지는 플라스크가 1개 늘어나지만, 개당 피해는 줄어듭니다.", L("Throw one more flask at a time, but each deals less damage.", "一度に投げるフラスコが1つ増えますが、1つあたりのダメージは減ります。", "每次多投出1个烧瓶，但每个伤害降低。") },
        { "강력한 반응", L("Violent Reaction", "激しい反応", "剧烈反应") },
        { "플라스크 폭발 피해가 15% 늘어납니다.", L("Flask explosion damage +15%.", "フラスコの爆発ダメージが15%増えます。", "烧瓶爆炸伤害提高15%。") },
        { "현재 ", L("Current ", "現在 ", "当前 ") },
        { "영혼을 지켜 세상을 구한 자 — Soul Saver.", L("The one who saved the world's souls — Soul Saver.", "魂を守り世界を救った者 — Soul Saver。", "守护灵魂、拯救世界之人 — Soul Saver。") },
    };
}
