using System.Collections.Generic;

// 번역표: 한국어 → { 한국어(고쳐 쓸 때만), 영어, 일본어, 중국어 }
public static class LocTable
{
    static string[] E(string ko, string en, string ja, string zh) => new[] { ko, en, ja, zh };
    static string[] L(string en, string ja, string zh) => new[] { "", en, ja, zh };

    public static readonly Dictionary<string, string[]> Entries = new Dictionary<string, string[]>
    {
        // ================================================================= 메뉴 · 설정 · 튜토리얼
        { "민근이의 첫번째 게임", L("Mingeun's First Game", "ミングンの初めてのゲーム", "敏根的第一款游戏") },
        { "게임 시작", L("Start Game", "ゲーム開始", "开始游戏") },
        { "게임 종료", L("Quit Game", "ゲーム終了", "退出游戏") },
        { "튜토리얼", L("Tutorial", "チュートリアル", "教程") },
        { "설정", L("Settings", "設定", "设置") },
        { "언어", L("Language", "言語", "语言") },
        { "볼륨", L("Volume", "音量", "音量") },
        { "닫기", L("Close", "閉じる", "关闭") },
        { "이전", L("Prev", "前へ", "上一页") },
        { "다음", L("Next", "次へ", "下一页") },
        { "시작하기", L("Let's Go", "始める", "开始") },
        { "지하 묘역에서 살아남아라", L("Survive the Catacombs", "地下墓所を生き延びろ", "在地下墓穴中活下去") },
        { "나의 첫 유니티 게임", L("My First Unity Game", "初めてのUnityゲーム", "我的第一款Unity游戏") },
        { "다시 시작", L("Restart", "リスタート", "重新开始") },
        { "메인 메뉴로", L("Main Menu", "メインメニューへ", "返回主菜单") },
        { "다시 하기", L("Try Again", "もう一度", "再来一次") },
        { "사망하셨습니다...", L("You Died...", "あなたは死んだ…", "你死了……") },
        { "일시정지", L("Paused", "一時停止", "暂停") },
        { "[ESC] 계속하기", L("[ESC] Resume", "[ESC] 再開", "[ESC] 继续") },
        { "[P] 상점    [ESC] 메뉴", E("[ESC] 메뉴 · 설정", "[ESC] Menu · Settings", "[ESC] メニュー・設定", "[ESC] 菜单 · 设置") },
        { "[P] 또는 [ESC] 로 닫기", E("[ESC] 로 닫기", "[ESC] to close", "[ESC] で閉じる", "按 [ESC] 关闭") },
        { "일시정지 1초", L("Paused 1s", "一時停止 1秒", "暂停 1秒") },
        { "일시정지 ", L("Paused ", "一時停止 ", "暂停 ") },
        { "레벨 업!", L("Level Up!", "レベルアップ！", "升级！") },
        { "좀 쎈 보스", L("A Tough Boss", "ちょっと強いボス", "有点强的首领") },
        { "능력을 하나 선택하세요", L("Choose an ability", "能力を一つ選んでください", "请选择一项能力") },
        { "카드를 눌러 선택", L("Click a card to choose", "カードを押して選択", "点击卡牌选择") },
        { "상점", L("Shop", "ショップ", "商店") },
        { "코인 : 0", L("Coins : 0", "コイン : 0", "金币 : 0") },
        { "신전 문이 열렸다!", L("The temple gate is open!", "神殿の扉が開いた！", "神殿之门开启了！") },
        { "지옥의 문", L("Gate of Hell", "地獄の門", "地狱之门") },
        { "포인트 3개로 세 갈래에서 특수 능력 3개를 고르세요", L("Spend 3 points to pick 3 special abilities from the three branches", "3ポイントで3系統から特殊能力を3つ選んでください", "用3点在三个分支中选择3项特殊能力") },
        { "현재 / 최대", L("Now / Max", "現在 / 最大", "当前 / 最大") },

        // ================================================================= 툴팁
        { "타겟팅 스킬", L("Targeting Skill", "ターゲティングスキル", "锁定技能") },
        { "게이지가 가득 차면 우클릭을 누르고 있는 동안 시간이 느려지며 주변 적을 차례로 조준합니다.\n버튼을 떼면 조준한 모든 적에게 일제 사격!\n\n일반 사격으로 적을 맞히면 게이지가 찹니다.",
          E("게이지가 가득 차면 우클릭으로 필살기를 씁니다. 들고 있는 무기마다 조준 화면과 필살기가 다릅니다.\n\n게이지는 시간이 지나면 차고, 적을 처치하면 잠깐 더 빨리 찹니다.",
            "When the gauge is full, right-click to use your ultimate. Each weapon has its own aiming screen and ultimate.\n\nThe gauge fills over time, and faster for a moment after each kill.",
            "ゲージが満タンになったら右クリックで必殺技。武器ごとに照準画面と必殺技が違います。\n\nゲージは時間で溜まり、敵を倒すと少しの間速く溜まります。",
            "能量满时右键释放必杀技。每种武器的瞄准画面和必杀技都不同。\n\n能量随时间积累，击杀敌人后短时间内积累更快。") },

        // ================================================================= 특수 능력 (이름 · 설명)
        { "지옥불 산탄총", L("Hellfire Shotgun", "獄炎ショットガン", "狱火霰弹枪") },
        { "영혼 저격총", L("Soul Sniper", "ソウルスナイパー", "灵魂狙击枪") },
        { "저주받은 쌍권총", L("Cursed Twin Pistols", "呪われた二丁拳銃", "被诅咒的双枪") },
        { "화염 방사기", L("Flamethrower", "火炎放射器", "火焰喷射器") },
        { "영혼 인도 지팡이", L("Soulguide Staff", "魂導きの杖", "引魂法杖") },
        { "번개 사슬총", L("Chain Lightning Gun", "連鎖雷撃銃", "连锁闪电枪") },
        { "부메랑 낫", L("Boomerang Scythe", "ブーメラン鎌", "回旋镰刀") },
        { "용암 유탄 발사기", L("Lava Grenade Launcher", "溶岩グレネードランチャー", "熔岩榴弹发射器") },
        { "그림자 대시", L("Shadow Dash", "シャドウダッシュ", "暗影冲刺") },
        { "지옥불 장판", L("Hellfire Field", "獄炎フィールド", "狱火领域") },
        { "시간 왜곡", L("Time Warp", "時間歪曲", "时间扭曲") },
        { "희생의 계약", L("Blood Pact", "犠牲の契約", "牺牲契约") },
        { "영혼 폭발", L("Soul Burst", "ソウルバースト", "灵魂爆发") },
        { "해골 소환", L("Summon Skeletons", "スケルトン召喚", "召唤骷髅") },
        { "거울 분신", L("Mirror Image", "鏡の分身", "镜像分身") },
        { "피의 갈고리", L("Blood Hook", "血のフック", "鲜血钩索") },
        { "수호 영혼", L("Guardian Souls", "守護の魂", "守护之魂") },
        { "복수의 가시", L("Thorns of Vengeance", "復讐の棘", "复仇之刺") },
        { "탄창 저주", L("Cursed Magazine", "弾倉の呪い", "弹匣诅咒") },
        { "불사의 맹세", L("Oath of Undying", "不死の誓い", "不死誓约") },
        { "총알 대신 앞쪽 부채꼴(6칸) 안의 적 모두에게\n즉시 250% 피해와 강한 넉백. 발사 간격 1.4배.", L("Instead of bullets, hits every enemy in a cone ahead (6 tiles)\nfor 250% damage with strong knockback. Fire interval x1.4.", "弾の代わりに前方の扇形(6マス)内の敵全員に\n即座に250%ダメージと強いノックバック。発射間隔1.4倍。", "不发射子弹，直接对前方扇形(6格)内所有敌人\n造成250%伤害并强力击退。射击间隔1.4倍。") },
        { "누르고 있다가 떼면 발사합니다. 모든 적을 관통하고\n충전 정도에 따라 피해 150%~300%.", L("Hold and release to fire. Pierces every enemy;\n150%-300% damage depending on charge.", "押し続けて離すと発射。全ての敵を貫通し\nチャージに応じて150%〜300%ダメージ。", "按住后松开发射。穿透所有敌人，\n根据蓄力造成150%~300%伤害。") },
        { "누르고 있으면 연사합니다. 발사 간격 절반, 발당 피해 55%.\n두 발에 탄 1개만 씁니다.", L("Hold for rapid fire. Half the fire interval, 55% damage per shot.\nOnly 1 ammo per 2 shots.", "押し続けると連射。発射間隔半分、1発55%ダメージ。\n2発で弾1つしか使いません。", "按住连射。射击间隔减半，每发55%伤害。\n每2发只消耗1颗子弹。") },
        { "누르고 있으면 불을 뿜어 적을 관통하고 불태웁니다.\n탄약 대신 과열 게이지를 씁니다.", L("Hold to spew fire that pierces and burns enemies.\nUses an overheat gauge instead of ammo.", "押し続けると火を噴き、敵を貫通して燃やします。\n弾薬の代わりに過熱ゲージを使います。", "按住喷火，穿透并点燃敌人。\n使用过热槽代替弹药。") },
        { "가장 가까운 적을 쫓아가는 유도탄을 쏩니다.\n발당 피해 70%, 조준이 필요 없습니다.", L("Fires homing shots that chase the nearest enemy.\n70% damage per shot, no aiming needed.", "最も近い敵を追う誘導弾を撃ちます。\n1発70%ダメージ、照準不要。", "发射追踪最近敌人的导弹。\n每发70%伤害，无需瞄准。") },
        { "맞은 적에게서 최대 4마리에게 번개가 튑니다.\n튈 때마다 피해가 20%씩 줄어듭니다.", L("Lightning jumps from the target to up to 4 enemies.\nEach jump deals 20% less damage.", "命中した敵から最大4体に雷が飛びます。\n飛ぶたびにダメージが20%ずつ減ります。", "闪电从命中的敌人弹射到最多4个敌人。\n每次弹射伤害降低20%。") },
        { "날아갔다 돌아오며 오가는 길의 적을 모두 벱니다.\n피해 150%, 한 번에 하나만 던질 수 있습니다.", L("Flies out and back, cutting every enemy on the way.\n150% damage, only one at a time.", "飛んで戻ってくる間に道中の敵を全て斬ります。\n150%ダメージ、一度に1つだけ投げられます。", "飞出再飞回，斩击沿途所有敌人。\n150%伤害，一次只能投掷一把。") },
        { "마우스 위치에 떨어져 폭발(피해 200%)하고\n잠깐 용암 웅덩이를 남깁니다. 탄 2개 사용.", L("Lands at the cursor and explodes (200% damage),\nleaving a brief lava pool. Uses 2 ammo.", "マウス位置に落ちて爆発(200%ダメージ)し\n一時的に溶岩溜まりを残します。弾2つ使用。", "落在鼠标位置爆炸(200%伤害)，\n并短暂留下熔岩池。消耗2发弹药。") },
        { "마우스 방향으로 짧게 돌진합니다.\n돌진 중에는 무적. 쿨타임 3초.", L("Dash a short distance toward the cursor.\nInvincible while dashing. Cooldown 3s.", "マウス方向に短く突進します。\n突進中は無敵。クールタイム3秒。", "向鼠标方向短距离冲刺。\n冲刺时无敌。冷却3秒。") },
        { "마우스 위치에 4초 동안 불 장판을 깝니다.\n0.5초마다 공격력 75% 피해. 쿨타임 12초.", L("Creates a fire field at the cursor for 4s.\n75% damage every 0.5s. Cooldown 12s.", "マウス位置に4秒間炎のフィールドを敷きます。\n0.5秒ごとに攻撃力75%ダメージ。クールタイム12秒。", "在鼠标位置生成持续4秒的火焰领域。\n每0.5秒造成75%伤害。冷却12秒。") },
        { "5초 동안 모든 적이 50% 느려집니다.\n플레이어는 정상 속도. 쿨타임 20초.", L("All enemies are 50% slower for 5s.\nYou move at normal speed. Cooldown 20s.", "5秒間、全ての敵が50%遅くなります。\nプレイヤーは通常速度。クールタイム20秒。", "5秒内所有敌人减速50%。\n玩家速度不变。冷却20秒。") },
        { "최대 체력 20%를 바쳐 8초 동안\n공격력 2배, 연사 1.5배. 쿨타임 25초.", L("Sacrifice 20% max HP for 8s of\ndouble damage and x1.5 fire rate. Cooldown 25s.", "最大体力の20%を捧げ8秒間\n攻撃力2倍、連射1.5倍。クールタイム25秒。", "献祭20%最大生命，8秒内\n攻击力2倍、射速1.5倍。冷却25秒。") },
        { "적을 처치하면 영혼이 쌓입니다(최대 40).\n5개 이상일 때 모두 터뜨려 주변에 피해. 쿨타임 5초.", L("Kills store souls (max 40).\nWith 5+, detonate them all to damage nearby enemies. Cooldown 5s.", "敵を倒すと魂が溜まります(最大40)。\n5つ以上で全て炸裂させ周囲にダメージ。クールタイム5秒。", "击杀敌人积累灵魂(最多40)。\n达到5个以上时全部引爆伤害周围。冷却5秒。") },
        { "아군 해골 3기를 10초 동안 부릅니다.\n적에게 달려가 자폭(공격력 300%). 쿨타임 15초.", L("Summons 3 allied skeletons for 10s.\nThey run at enemies and explode (300%). Cooldown 15s.", "味方のスケルトン3体を10秒間呼び出します。\n敵に突っ込んで自爆(攻撃力300%)。クールタイム15秒。", "召唤3具友方骷髅，持续10秒。\n冲向敌人自爆(300%)。冷却15秒。") },
        { "제자리에 분신을 남기고 반투명해집니다.\n3초 동안 적이 분신을 쫓습니다. 쿨타임 12초.", L("Leave a decoy behind and turn translucent.\nEnemies chase the decoy for 3s. Cooldown 12s.", "その場に分身を残して半透明になります。\n3秒間、敵は分身を追います。クールタイム12秒。", "原地留下分身并变为半透明。\n敌人会追击分身3秒。冷却12秒。") },
        { "사슬을 던져 적을 끌어오거나(피해 150%)\n벽 쪽으로 날아갑니다. 쿨타임 4초.", L("Throw a chain to pull an enemy in (150%)\nor fly toward a wall. Cooldown 4s.", "鎖を投げて敵を引き寄せる(150%ダメージ)か\n壁の方へ飛びます。クールタイム4秒。", "投出锁链拉回敌人(150%伤害)\n或飞向墙壁。冷却4秒。") },
        { "영혼 구체 3개가 주위를 돌며\n닿은 적에게 공격력 80% 피해를 줍니다.", L("3 soul orbs circle you,\ndealing 80% damage to enemies they touch.", "魂の球3つが周囲を回り\n触れた敵に攻撃力80%のダメージを与えます。", "3颗灵魂球环绕你，\n对接触的敌人造成80%伤害。") },
        { "피격될 때마다 주변 적에게\n공격력 300% 피해를 주고 밀어냅니다.", L("Each time you are hit, nearby enemies\ntake 300% damage and are pushed away.", "被弾するたびに周囲の敵に\n攻撃力300%のダメージを与え押し返します。", "每次受击时对周围敌人\n造成300%伤害并击退。") },
        { "탄창의 마지막 한 발이 피해 3배가 되고\n맞은 곳에서 폭발합니다.", L("The last bullet in each magazine deals triple damage\nand explodes on impact.", "弾倉の最後の1発がダメージ3倍になり\n命中地点で爆発します。", "弹匣最后一发造成3倍伤害\n并在命中处爆炸。") },
        { "한 판에 한 번, 죽을 피해를 받으면\n체력 1로 버티고 3초 동안 무적이 됩니다.", L("Once per run, survive a lethal hit\nwith 1 HP and become invincible for 3s.", "1プレイに1回、致命ダメージを受けても\n体力1で耐え、3秒間無敵になります。", "每局一次，受到致命伤害时\n以1点生命存活并无敌3秒。") },

        // ================================================================= 보스 · 스테이지
        { "킹 슬라임이 둘로 갈라졌다!", L("The King Slime split in two!", "キングスライムが二つに分裂した！", "史莱姆王分裂成了两只！") },
        { "슬라임이 또 갈라진다!", L("The slimes split again!", "スライムがまた分裂する！", "史莱姆又分裂了！") },
        { "리치 왕이 망자의 의식을 시작한다!", L("The Lich King begins the Rite of the Dead!", "リッチ王が死者の儀式を始める！", "巫妖王开始了亡者仪式！") },
        { "지옥의 군주가 십자 불길을 내뿜는다!", L("The Demon Lord unleashes the Hellfire Cross!", "地獄の君主が十字の業火を放つ！", "地狱领主喷出十字烈焰！") },
        { "킹 슬라임이 미친 듯이 뛰어오른다!", L("The King Slime is leaping wildly!", "キングスライムが狂ったように跳ね回る！", "史莱姆王疯狂地跳跃！") },
        { "특수 강화 [", L("Special Upgrade [", "特殊強化 [", "特殊强化 [") },
        { "]   포인트 ", L("]   Points ", "]   ポイント ", "]   点数 ") },
        { "중간 보스 등장!\n쓰러뜨리면 특수 능력 포인트 +1", L("A mid-boss appears!\nDefeat it for +1 special point", "中ボス出現！\n倒すと特殊能力ポイント+1", "中头目出现！\n击败可获得特殊能力点数+1") },
        { "특수 능력 포인트 +1!\n[", L("Special point +1!\n[", "特殊能力ポイント+1！\n[", "特殊能力点数+1！\n[") },
        { "] 또는 아래 버튼으로 강화", L("] or the button below to upgrade", "] または下のボタンで強化", "] 或下方按钮进行强化") },
        { "신전 문이 열렸다!\n문으로 들어가세요", L("The temple gate is open!\nEnter the gate", "神殿の扉が開いた！\n扉に入ってください", "神殿之门开启了！\n请进入大门") },
        { "지옥의 군주를 쓰러뜨렸다!\n성문 너머로 초원이 보인다", L("The Demon Lord has fallen!\nA meadow lies beyond the gate", "地獄の君主を倒した！\n城門の向こうに草原が見える", "击败了地狱领主！\n城门外是一片草原") },
        { "킹 슬라임을 쓰러뜨렸다!\n모든 스테이지 클리어!", L("The King Slime has fallen!\nAll stages cleared!", "キングスライムを倒した！\n全ステージクリア！", "击败了史莱姆王！\n全部关卡通关！") },
        { "3장 · 초원\n특수 능력 포인트 +2", L("Chapter 3 · Meadow\nSpecial points +2", "第3章・草原\n特殊能力ポイント+2", "第3章 · 草原\n特殊能力点数+2") },
        { "2장 · 불타는 지옥", L("Chapter 2 · Burning Hell", "第2章・燃える地獄", "第2章 · 燃烧地狱") },
        { "지옥의 문이 당신을 끌어당긴다!  ", L("The gate is pulling you in!  ", "門があなたを引き寄せる！  ", "大门正在将你吸入！  ") },
        { "신전 문으로 들어가세요  ", L("Enter the gate  ", "門に入ってください  ", "请进入大门  ") },
        { "초", L("s", "秒", "秒") },
        { "떠돌이 상점이 나타났다!\n10초 안에 다가가 [Space]", L("A wandering shop appeared!\nReach it within 10s and press [Space]", "さすらいのショップが現れた！\n10秒以内に近づいて [Space]", "流浪商店出现了！\n10秒内靠近并按 [Space]") },
        { "상점 열기", L("Open Shop", "ショップを開く", "打开商店") },
        { "상점  ", L("Shop  ", "ショップ  ", "商店  ") },

        // ================================================================= 레벨업 능력
        { "관통하는 총알", L("Piercing Bullets", "貫通する弾", "穿透子弹") },
        { "총알의 관통력이 증가합니다 \n( 관통 ", L("Bullets pierce more enemies \n( Pierce ", "弾の貫通力が上がります \n( 貫通 ", "子弹穿透力提升 \n( 穿透 ") },
        { "코인충", L("Coin Hoarder", "コイン好き", "金币狂") },
        { "코인을 더 많이 획득합니다.\n( 코인 획득량 ", L("Gain more coins.\n( Coins per pickup ", "より多くのコインを獲得します。\n( コイン獲得量 ", "获得更多金币。\n( 金币获取量 ") },
        { "재활용 에너지", L("Recycled Energy", "リサイクルエネルギー", "能量回收") },
        { "스킬 게이지가 20% 감소합니다\n( 게이지 -20% )", L("The skill gauge fills 20% faster\n( Gauge -20% )", "スキルゲージが20%早く溜まります\n( ゲージ -20% )", "技能能量积累加快20%\n( 能量 -20% )") },
        { "노려보는 눈빛", L("Piercing Glare", "睨みつける眼光", "凝视之眼") },
        { "스킬을 사용하는 동안 타겟이 된 적이 더 느려집니다. \n( 속도 -20% )", L("Targeted enemies slow down more while aiming. \n( Speed -20% )", "スキル使用中、狙った敵がさらに遅くなります。 \n( 速度 -20% )", "瞄准期间被锁定的敌人更慢。 \n( 速度 -20% )") },
        { "더 많은 경험치", L("More Experience", "経験値アップ", "更多经验") },
        { "킬 경험치 +10%", L("Kill EXP +10%", "撃破経験値 +10%", "击杀经验 +10%") },
        { "코인 자석", L("Coin Magnet", "コインマグネット", "金币磁铁") },
        { "주변의 코인을 끌어옵니다.\n( 범위 ", L("Pulls in nearby coins.\n( Range ", "周囲のコインを引き寄せます。\n( 範囲 ", "吸引附近的金币。\n( 范围 ") },
        { "멀티 샷", L("Multi Shot", "マルチショット", "多重射击") },
        { "한 번에 쏘는 총알이 1발 늘어나지만, 한 발당 피해는 줄어듭니다.\n( ", L("Fire 1 more bullet per shot, but each deals less damage.\n( ", "一度に撃つ弾が1発増えますが、1発あたりのダメージは減ります。\n( ", "每次多射1发子弹，但每发伤害降低。\n( ") },
        { "발 ", L(" shots ", "発 ", "发 ") },
        { "밀어내기", L("Knockback", "押し返し", "击退") },
        { "총알이 적을 밀어내는 효과 +25%\n( 최대 ", L("Bullet knockback +25%\n( Max ", "弾のノックバック +25%\n( 最大 ", "子弹击退效果 +25%\n( 最多 ") },
        { "번 )", L(" times )", "回 )", "次 )") },
        { "강철같은 심장", L("Heart of Steel", "鋼の心臓", "钢铁之心") },
        { "체력을 즉시 모두 회복하며, 최대 체력이 12% 증가합니다.", L("Fully restores HP and increases max HP by 12%.", "体力を即座に全回復し、最大体力が12%増えます。", "立即回满生命，最大生命提高12%。") },
        { "단단한 신체", L("Tough Body", "頑丈な体", "坚韧体魄") },
        { "받는 피해를 12% 감소시킵니다.\n( 최대 ", L("Take 12% less damage.\n( Max ", "受けるダメージを12%減らします。\n( 最大 ", "受到的伤害降低12%。\n( 最多 ") },
        { "생명의 샘", L("Fountain of Life", "生命の泉", "生命之泉") },
        { "시간이 지나면 체력이 조금씩 회복됩니다.\n( 초당 ", L("Slowly regenerate HP over time.\n( Per second ", "時間とともに体力が少しずつ回復します。\n( 毎秒 ", "随时间缓慢恢复生命。\n( 每秒 ") },
        { "피의 굶주림", L("Bloodthirst", "血の飢え", "嗜血") },
        { "적을 처치할 때마다 체력을 회복합니다.\n( 처치당 ", L("Heal each time you kill an enemy.\n( Per kill ", "敵を倒すたびに体力を回復します。\n( 撃破ごと ", "每次击杀恢复生命。\n( 每次击杀 ") },
        { "[Space] 확정 : ", L("[Space] Confirm : ", "[Space] 決定 : ", "[Space] 确认 : ") },
        { "카드를 클릭해 고른 뒤 [Space]로 확정", L("Click a card, then press [Space] to confirm", "カードをクリックして [Space] で決定", "点击卡牌后按 [Space] 确认") },
        { "총알이 적을 뚫고 지나갑니다.", L("Bullets pass through enemies.", "弾が敵を貫通します。", "子弹会穿透敌人。") },
        { "관통: 적 ", L("Pierce: ", "貫通: 敵 ", "穿透: ") },
        { "마리", L(" enemies", "体", "个敌人") },
        { "코인을 주울 때 더 많이 얻습니다.", L("Get more from each coin you pick up.", "コインを拾うとより多く手に入ります。", "拾取金币时获得更多。") },
        { "코인 1개당 획득량: ", L("Per coin: ", "コイン1枚あたり: ", "每枚金币获得: ") },
        { "스킬 게이지가 더 빨리 가득 찹니다. (적을 처치하면 잠깐 더 빨라짐)", L("The skill gauge fills faster. (Even faster for a moment after kills)", "スキルゲージが早く溜まります。(敵を倒すと少しの間さらに速い)", "技能能量积累更快。(击杀后短时间更快)") },
        { "게이지가 가득 차는 시간: ", L("Time to fill: ", "満タンまでの時間: ", "充满时间: ") },
        { "스킬을 쓰는 동안 적이 더 느려집니다.", L("Enemies are slower while you aim.", "スキル使用中、敵がさらに遅くなります。", "使用技能时敌人更慢。") },
        { "스킬 중 시간 속도: ", L("Time speed while aiming: ", "スキル中の時間速度: ", "技能期间时间速度: ") },
        { "적을 처치할 때 얻는 경험치가 늘어납니다.", L("Gain more EXP from kills.", "敵を倒した時の経験値が増えます。", "击杀获得的经验增加。") },
        { "경험치 배율: ", L("EXP multiplier: ", "経験値倍率: ", "经验倍率: ") },
        { "주변의 코인을 끌어옵니다.", L("Pulls in nearby coins.", "周囲のコインを引き寄せます。", "吸引附近的金币。") },
        { "끌어오는 범위: ", L("Pull range: ", "引き寄せ範囲: ", "吸引范围: ") },
        { "한 번에 여러 발을 부채꼴로 발사합니다. 발사 수가 늘수록 한 발당 피해는 줄어듭니다.", L("Fire several bullets in a fan. More bullets means less damage each.", "一度に複数の弾を扇状に撃ちます。弾数が増えるほど1発のダメージは減ります。", "一次呈扇形发射多发子弹。子弹越多每发伤害越低。") },
        { "발사 수: ", L("Shots: ", "発射数: ", "发射数: ") },
        { "발 (최대 5발)\n현재 한 발당 피해: ", L(" (max 5)\nDamage per shot: ", "発 (最大5発)\n現在の1発あたりダメージ: ", "发 (最多5发)\n当前每发伤害: ") },
        { "총알이 적을 더 멀리 밀어냅니다.", L("Bullets push enemies farther.", "弾が敵をより遠くへ押し返します。", "子弹将敌人击退得更远。") },
        { "넉백: 기본의 ", L("Knockback: base x", "ノックバック: 基本の ", "击退: 基础的 ") },
        { "최대 체력이 늘어나고, 선택하는 순간 체력을 모두 회복합니다.", L("Raises max HP and fully heals you when chosen.", "最大体力が増え、選んだ瞬間に体力が全回復します。", "提高最大生命，选择时回满生命。") },
        { "최대 체력: ", L("Max HP: ", "最大体力: ", "最大生命: ") },
        { "적에게 받는 피해가 줄어듭니다.", L("Take less damage from enemies.", "敵から受けるダメージが減ります。", "受到敌人的伤害降低。") },
        { "받는 피해 감소: ", L("Damage reduction: ", "被ダメージ軽減: ", "减伤: ") },
        { "시간이 지나면 체력이 조금씩 회복됩니다.", L("Slowly regenerate HP over time.", "時間とともに体力が少しずつ回復します。", "随时间缓慢恢复生命。") },
        { "초당 회복: ", L("Regen per second: ", "毎秒回復: ", "每秒恢复: ") },
        { "적을 처치할 때마다 체력을 회복합니다.", L("Heal each time you kill an enemy.", "敵を倒すたびに体力を回復します。", "每次击杀恢复生命。") },
        { "처치당 회복: ", L("Heal per kill: ", "撃破ごとの回復: ", "每次击杀恢复: ") },
        { "\n\n<color=#F5D478>현재 ", L("\n\n<color=#F5D478>Now ", "\n\n<color=#F5D478>現在 ", "\n\n<color=#F5D478>当前 ") },

        // ================================================================= 상점
        { "최대", L("MAX", "最大", "已满") },
        { "구매\n", L("Buy\n", "購入\n", "购买\n") },
        { " 코인", L(" coins", " コイン", " 金币") },
        { "코인 : ", L("Coins : ", "コイン : ", "金币 : ") },
        { "총알 공격력\n", L("Bullet Damage\n", "弾の攻撃力\n", "子弹攻击力\n") },
        { "발, 발당 ", L(" shots, each ", "発、1発 ", "发，每发 ") },
        { "공격 속도\n초당 ", L("Fire Rate\n", "攻撃速度\n毎秒 ", "攻击速度\n每秒 ") },
        { "발 (최대)", L("/s (MAX)", "発 (最大)", "发 (已满)") },
        { "공격 속도 (초당)\n", L("Fire Rate (per sec)\n", "攻撃速度 (毎秒)\n", "攻击速度 (每秒)\n") },
        { "발", L("", "発", "发") },
        { "재장전 속도\n", L("Reload Time\n", "リロード速度\n", "换弹速度\n") },
        { "초 (최대)", L("s (MAX)", "秒 (最大)", "秒 (已满)") },
        { "초 -> ", L("s -> ", "秒 -> ", "秒 -> ") },
        { "최대 탄창\n", L("Magazine Size\n", "最大弾倉\n", "弹匣容量\n") },
        { "이동 속도\n", L("Move Speed\n", "移動速度\n", "移动速度\n") },
        { " (최대)", L(" (MAX)", " (最大)", " (已满)") },
        { "스킬 강화", L("Skill Upgrades", "スキル強化", "技能强化") },
        { "우클릭 필살기를 무기마다 따로 강화합니다 · 위력 +20% · 특성은 무기마다 다름", L("Upgrade each weapon's right-click ultimate · Power +20% · Traits differ per weapon", "右クリック必殺技を武器ごとに強化します・威力+20%・特性は武器ごとに異なる", "分别强化每种武器的右键必杀技 · 威力+20% · 特性因武器而异") },
        { "상점으로", L("Back to Shop", "ショップへ", "返回商店") },
        { "기본 권총", L("Basic Pistol", "基本拳銃", "基础手枪") },
        { "위력", L("Power", "威力", "威力") },
        { "<color=#a39aa8>최대</color>", L("<color=#a39aa8>MAX</color>", "<color=#a39aa8>最大</color>", "<color=#a39aa8>已满</color>") },
        { " 코인</color>", L(" coins</color>", " コイン</color>", " 金币</color>") },
        { "코인이 부족합니다 (", L("Not enough coins (", "コインが足りません (", "金币不足 (") },
        { "무기 강화", L("Weapon Upgrades", "武器強化", "武器强化") },
        { "무기마다 따로 강화됩니다 (권총 강화와 별개) · 피해 +15% · 연사 +10% · 탄창 +25% · 특성은 무기마다 다름", L("Each weapon is upgraded separately (not the pistol) · Damage +15% · Fire rate +10% · Magazine +25% · Traits differ", "武器ごとに個別に強化されます(拳銃とは別) · ダメージ+15% · 連射+10% · 弾倉+25% · 特性は武器ごと", "每种武器单独强化(与手枪无关) · 伤害+15% · 射速+10% · 弹匣+25% · 特性因武器而异") },
        { "피해", L("Damage", "ダメージ", "伤害") },
        { "연사", L("Fire Rate", "連射", "射速") },
        { "탄창", L("Magazine", "弾倉", "弹匣") },
        { "\n<color=#a39aa8>해당 없음</color>", L("\n<color=#a39aa8>N/A</color>", "\n<color=#a39aa8>対象外</color>", "\n<color=#a39aa8>不适用</color>") },

        // ================================================================= 필살기 · 강화 특성
        { "지옥불 포격", L("Hellfire Barrage", "獄炎砲撃", "狱火炮击") },
        { "관통 레일건", L("Piercing Railgun", "貫通レールガン", "穿透电磁炮") },
        { "총알 폭풍", L("Bullet Storm", "弾丸の嵐", "子弹风暴") },
        { "화염 회오리", L("Fire Tornado", "炎の竜巻", "火焰龙卷") },
        { "영혼 떼", L("Soul Swarm", "魂の群れ", "灵魂群") },
        { "뇌운", L("Thunderstorm", "雷雲", "雷云") },
        { "죽음의 춤", L("Dance of Death", "死の舞", "死亡之舞") },
        { "용암 융단폭격", L("Lava Carpet Bombing", "溶岩絨毯爆撃", "熔岩地毯轰炸") },
        { "일제 사격", L("Volley", "一斉射撃", "齐射") },
        { "타겟 수", L("Targets", "ターゲット数", "目标数") },
        { "영혼 구슬", L("Soul Orbs", "魂の球", "灵魂球") },
        { "포격 횟수", L("Blasts", "砲撃回数", "炮击次数") },
        { "광선 굵기", L("Beam Width", "光線の太さ", "光束宽度") },
        { "지속 시간", L("Duration", "持続時間", "持续时间") },
        { "회오리 지속", L("Tornado Time", "竜巻の持続", "龙卷持续") },
        { "뇌운 지속", L("Storm Time", "雷雲の持続", "雷云持续") },
        { "폭격 줄", L("Bomb Rows", "爆撃の列", "轰炸行数") },
        { "특성", L("Trait", "特性", "特性") },
        { "+2마리", L("+2", "+2体", "+2个") },
        { "+1개", L("+1", "+1個", "+1个") },
        { "+1회", L("+1", "+1回", "+1次") },
        { "+0.4초", L("+0.4s", "+0.4秒", "+0.4秒") },
        { "+1.5초", L("+1.5s", "+1.5秒", "+1.5秒") },
        { "+0.8초", L("+0.8s", "+0.8秒", "+0.8秒") },
        { "+2줄", L("+2 rows", "+2列", "+2行") },
        { "사거리", L("Range", "射程", "射程") },
        { "충전 속도", L("Charge Speed", "チャージ速度", "蓄力速度") },
        { "관통", L("Pierce", "貫通", "穿透") },
        { "냉각", L("Cooling", "冷却", "冷却") },
        { "연쇄", L("Chain", "連鎖", "连锁") },
        { "낫 크기", L("Blade Size", "鎌の大きさ", "镰刀大小") },
        { "폭발 범위", L("Blast Radius", "爆発範囲", "爆炸范围") },
        { "사거리 +1", L("Range +1", "射程 +1", "射程 +1") },
        { "충전 시간 -15%", L("Charge time -15%", "チャージ時間 -15%", "蓄力时间 -15%") },
        { "관통 +1", L("Pierce +1", "貫通 +1", "穿透 +1") },
        { "열 발생 -20%", L("Heat -20%", "発熱 -20%", "发热 -20%") },
        { "연쇄 +1", L("Chain +1", "連鎖 +1", "连锁 +1") },
        { "크기·거리 +15%", L("Size·Reach +15%", "大きさ・距離 +15%", "大小·距离 +15%") },
        { "범위 +0.6", L("Radius +0.6", "範囲 +0.6", "范围 +0.6") },

        // ================================================================= 진화
        { " 진화!", L(" evolved!", " 進化！", " 进化！") },
        { "사거리 +2, 부채꼴이 넓어지고 피해 320%. 맞은 적이 불탑니다.", L("Range +2, wider cone, 320% damage. Hit enemies burn.", "射程+2、扇形が広がりダメージ320%。命中した敵が燃えます。", "射程+2，扇形更宽，伤害320%。命中的敌人会燃烧。") },
        { "충전 시간 0.8초. 완충 사격이 맞은 곳에서 폭발합니다.", L("0.8s charge. Fully charged shots explode where they hit.", "チャージ0.8秒。フルチャージ射撃が命中地点で爆発します。", "蓄力0.8秒。满蓄力射击在命中处爆炸。") },
        { "두 총구에서 동시에 발사합니다 (탄약 소모는 그대로).", L("Fires from both barrels at once (same ammo use).", "両方の銃口から同時に発射します(弾薬消費はそのまま)。", "两把枪同时开火(弹药消耗不变)。") },
        { "열이 40% 덜 오르고 불길 화상 피해가 강해집니다.", L("40% less heat and stronger burn damage.", "熱が40%上がりにくくなり、炎の燃焼ダメージが強くなります。", "发热降低40%，燃烧伤害增强。") },
        { "한 번에 유도탄 2발을 쏩니다.", L("Fires 2 homing shots at once.", "一度に誘導弾を2発撃ちます。", "一次发射2发导弹。") },
        { "번개가 7번 튀고, 튈 때 피해가 덜 줄어듭니다.", L("Lightning jumps 7 times and loses less damage per jump.", "雷が7回飛び、飛ぶたびのダメージ減少が小さくなります。", "闪电弹射7次，每次弹射伤害衰减更少。") },
        { "낫이 더 커지고 더 멀리 날아가며 피해 220%.", L("Bigger scythe that flies farther, 220% damage.", "鎌が大きくなり遠くまで飛び、ダメージ220%。", "镰刀更大、飞得更远，伤害220%。") },
        { "폭발 후 작은 용암탄 3개로 흩어집니다.", L("Splits into 3 small lava bombs after exploding.", "爆発後、小さな溶岩弾3つに分かれます。", "爆炸后分裂成3颗小熔岩弹。") },
        { "쿨타임 1.8초. 도착 지점에서 충격파가 터집니다.", L("1.8s cooldown. A shockwave bursts where you land.", "クールタイム1.8秒。到着地点で衝撃波が炸裂します。", "冷却1.8秒。在落点爆发冲击波。") },
        { "장판이 더 넓고 6초 동안 지속됩니다. 쿨타임 9초.", L("Wider field that lasts 6s. 9s cooldown.", "フィールドが広くなり6秒間持続します。クールタイム9秒。", "领域更大，持续6秒。冷却9秒。") },
        { "적이 75% 느려지고 7초 동안 지속됩니다.", L("Enemies are 75% slower for 7s.", "敵が75%遅くなり7秒間持続します。", "敌人减速75%，持续7秒。") },
        { "체력을 잃지 않고 12초 동안 지속됩니다.", L("No HP cost and lasts 12s.", "体力を失わず12秒間持続します。", "不消耗生命，持续12秒。") },
        { "영혼 3개부터 쓸 수 있고 폭발 범위가 넓어집니다.", L("Usable from 3 souls with a larger blast.", "魂3つから使え、爆発範囲が広がります。", "3个灵魂即可使用，爆炸范围更大。") },
        { "해골 5마리를 부르고 쿨타임 10초.", L("Summons 5 skeletons, 10s cooldown.", "スケルトンを5体呼び、クールタイム10秒。", "召唤5具骷髅，冷却10秒。") },
        { "분신이 5초 동안 남고 사라질 때 폭발합니다.", L("The decoy lasts 5s and explodes when it fades.", "分身が5秒間残り、消える時に爆発します。", "分身持续5秒，消失时爆炸。") },
        { "쿨타임 2초, 갈고리 피해 300%.", L("2s cooldown, 300% hook damage.", "クールタイム2秒、フックダメージ300%。", "冷却2秒，钩索伤害300%。") },
        { "영혼이 5개로 늘고 피해가 강해집니다.", L("5 orbs with stronger damage.", "魂が5つに増え、ダメージが強くなります。", "灵魂增至5个，伤害增强。") },
        { "반격 범위와 피해가 크게 늘어납니다.", L("Much larger counterattack radius and damage.", "反撃範囲とダメージが大きく増えます。", "反击范围和伤害大幅提升。") },
        { "탄창의 마지막 두 발이 저주탄이 됩니다.", L("The last two bullets become cursed.", "弾倉の最後の2発が呪い弾になります。", "弹匣最后两发成为诅咒弹。") },
        { "두 번 부활하고, 부활할 때 체력 50%로 일어납니다.", L("Revive twice, getting up with 50% HP.", "2回復活し、復活時は体力50%で起き上がります。", "可复活两次，复活时恢复50%生命。") },

        // ================================================================= 특수 능력 상태 글자
        { "낫 준비", L("Scythe ready", "鎌 準備完了", "镰刀就绪") },
        { "낫 회수 중", L("Scythe returning", "鎌 回収中", "镰刀回收中") },
        { "완충!", L("Full charge!", "フルチャージ！", "蓄满！") },
        { "충전 ", L("Charge ", "チャージ ", "蓄力 ") },
        { "냉각 완료", L("Cooled down", "冷却完了", "冷却完成") },
        { "과열!", L("Overheated!", "オーバーヒート！", "过热！") },
        { "열기 ", L("Heat ", "熱 ", "热量 ") },
        { "시간 왜곡!", L("Time Warp!", "時間歪曲！", "时间扭曲！") },
        { "희생의 계약! 공격력 2배", L("Blood Pact! Double damage", "犠牲の契約！攻撃力2倍", "牺牲契约！攻击力2倍") },
        { "영혼 부족 ", L("Not enough souls ", "魂が足りない ", "灵魂不足 ") },
        { "해골 소환!", L("Skeletons!", "スケルトン召喚！", "召唤骷髅！") },
        { "저주탄 장전!", L("Cursed round loaded!", "呪い弾 装填！", "诅咒弹上膛！") },
        { "계약 종료", L("Pact ended", "契約終了", "契约结束") },
        { "가시 반격!", L("Thorns!", "棘の反撃！", "荆棘反击！") },
        { "불사의 맹세가 발동했다!", L("Oath of Undying activated!", "不死の誓いが発動した！", "不死誓约发动了！") },
        { "영혼 폭발 준비", L("Soul Burst ready", "ソウルバースト準備完了", "灵魂爆发就绪") },
        { "무기  [Q] 교체  [R] 장전", L("Weapons  [Q] Swap  [R] Reload", "武器  [Q] 切替  [R] リロード", "武器  [Q] 切换  [R] 换弹") },
        { "스킬", L("Skills", "スキル", "技能") },
        { "패시브", L("Passives", "パッシブ", "被动") },
        { "사용 중 · ", L("In hand · ", "使用中・", "使用中 · ") },
        { "과열", L("Overheated", "過熱", "过热") },
        { "준비", L("Ready", "準備完了", "就绪") },
        { "회수 중", L("Returning", "回収中", "回收中") },
        { "] 준비", L("] Ready", "] 準備完了", "] 就绪") },
        { " · 영혼 ", L(" · Souls ", "・魂 ", " · 灵魂 ") },
        { "부활 ", L("Revives ", "復活 ", "复活 ") },
        { "사용함", L("Used", "使用済み", "已使用") },
        { "장전 중", L("Reloading", "リロード中", "换弹中") },

        // ================================================================= 스킬 트리
        { "무기  [Q] 교체", L("Weapons  [Q] Swap", "武器  [Q] 切替", "武器  [Q] 切换") },
        { "패시브  항상 적용", L("Passives  Always on", "パッシブ  常時発動", "被动  始终生效") },
        { "스킬  [E] 사용", L("Skills  [E] Use", "スキル  [E] 使用", "技能  [E] 使用") },
        { "선택을 취소했습니다.", L("Selection cancelled.", "選択を取り消しました。", "已取消选择。") },
        { "이미 진화한 능력입니다.", L("Already evolved.", "すでに進化した能力です。", "该能力已进化。") },
        { "스킬 칸(E · F · Space)이 가득 찼습니다. 가진 스킬을 진화시켜 보세요.", L("Skill slots (E · F · Space) are full. Try evolving a skill you have.", "スキル枠(E・F・Space)がいっぱいです。持っているスキルを進化させてみましょう。", "技能栏(E · F · Space)已满。试试进化已有的技能。") },
        { "포인트를 모두 썼습니다. 다른 능력을 먼저 취소하세요.", L("No points left. Cancel another ability first.", "ポイントを使い切りました。先に他の能力を取り消してください。", "点数已用完。请先取消其他能力。") },
        { "진화 완료", L("Evolved", "進化完了", "已进化") },
        { "진화!", L("Evolve!", "進化！", "进化！") },
        { "진화 가능", L("Can evolve", "進化可能", "可进化") },
        { "진화: ", L("Evolve: ", "進化: ", "进化: ") },
        { "강화 완료", L("Upgrade", "強化完了", "强化完成") },
        { "포인트 ", L("Points ", "ポイント ", "点数 ") },
        { "선택 완료", L("Confirm", "選択完了", "确认选择") },
        { "남은 포인트 ", L("Points left ", "残りポイント ", "剩余点数 ") },
        { "특수 능력 포인트 ", L("Special points ", "特殊能力ポイント ", "特殊能力点数 ") },
        { "새 능력을 배우거나 가진 능력을 진화", L("Learn a new ability or evolve one you have", "新しい能力を覚えるか、持っている能力を進化", "学习新能力或进化已有能力") },
        { "파란 테두리는 이미 가진 능력입니다. 한 번 더 고르면 진화해서 더 강해집니다. 남은 포인트는 아껴 두었다가 나중에 써도 됩니다.", L("Abilities with a blue frame are ones you own. Pick them again to evolve them. You can save leftover points for later.", "青い枠はすでに持っている能力です。もう一度選ぶと進化して強くなります。残ったポイントは取っておいて後で使えます。", "蓝框表示已拥有的能力。再次选择即可进化变强。剩余点数可以留到以后使用。") },
        { "능력 ", L("Choose ", "能力を ", "请选择 ") },
        { "개를 고르세요", L(" abilities", "つ選んでください", "项能力") },
        { "개 · 노드를 눌러 선택", L(" · click nodes to choose", "つ・ノードを押して選択", "点 · 点击节点选择") },
        { "무기는 Q로 기본 권총과 번갈아 쓰고, 스킬은 고른 순서대로 E · F · Space에 배정됩니다. 다시 누르면 선택이 취소됩니다.", L("Swap weapons with the pistol using Q; skills go to E · F · Space in the order you pick them. Click again to cancel.", "武器はQで基本拳銃と切り替え、スキルは選んだ順にE・F・Spaceに割り当てられます。もう一度押すと選択を取り消します。", "武器用Q与基础手枪切换，技能按选择顺序分配到E · F · Space。再次点击取消选择。") },
        { " → 진화", L(" → Evolve", " → 進化", " → 进化") },
        { "  (선택됨)", L("  (selected)", "  (選択中)", "  (已选择)") },
        { "  (진화 완료)", L("  (evolved)", "  (進化済み)", "  (已进化)") },
        { "<color=#9fd8ff>진화</color>  ", L("<color=#9fd8ff>Evolve</color>  ", "<color=#9fd8ff>進化</color>  ", "<color=#9fd8ff>进化</color>  ") },
        { "무기 · Q로 교체", L("Weapon · Swap with Q", "武器・Qで切替", "武器 · Q切换") },
        { "스킬 · E/F/Space", L("Skill · E/F/Space", "スキル・E/F/Space", "技能 · E/F/Space") },
        { "패시브 · 항상 적용", L("Passive · Always on", "パッシブ・常時発動", "被动 · 始终生效") },

        // ================================================================= 능력치 창
        { "공격력", L("Attack", "攻撃力", "攻击力") },
        { "방어력", L("Defense", "防御力", "防御力") },
        { "공격 속도", L("Fire Rate", "攻撃速度", "攻击速度") },
        { "재장전", L("Reload", "リロード", "换弹") },
        { "이동 속도", L("Move Speed", "移動速度", "移动速度") },
        { "능력치", L("Stats", "ステータス", "属性") },
        { "눌러서 능력치 창을 열고 닫습니다.", L("Click to open or close the stats panel.", "押してステータス画面を開閉します。", "点击打开或关闭属性面板。") },
        { "/초", L("/s", "/秒", "/秒") },
        // ================================================================= 튜토리얼
        { "기본 조작", L("Basic Controls", "基本操作", "基本操作") },
        { "이동", L("Move", "移動", "移动") },
        { "좌클릭", L("Left Click", "左クリック", "左键") },
        { "우클릭", L("Right Click", "右クリック", "右键") },
        { "마우스 방향으로 사격", L("Shoot toward the cursor", "マウスの方向に射撃", "朝鼠标方向射击") },
        { "무기 교체 (특수 무기를 얻은 뒤)", L("Swap weapons (after getting special weapons)", "武器切替(特殊武器を手に入れた後)", "切换武器(获得特殊武器后)") },
        { "일시정지 · 설정", L("Pause · Settings", "一時停止・設定", "暂停 · 设置") },
        { "필살기", L("Ultimates", "必殺技", "必杀技") },
        { "스킬 게이지", L("Skill Gauge", "スキルゲージ", "技能能量") },
        { "시간이 지나면 차고, 적을 처치하면 잠깐 더 빨리 찹니다", L("Fills over time, and faster for a moment after each kill", "時間で溜まり、敵を倒すと少しの間速く溜まります", "随时间积累，击杀后短时间积累更快") },
        { "게이지가 가득 차면 필살기를 씁니다", L("Use your ultimate when the gauge is full", "ゲージが満タンになったら必殺技を使います", "能量满时释放必杀技") },
        { "조준형", L("Aimed", "照準型", "瞄准型") },
        { "누르고 있으면 시간이 느려지며 적을 조준, 떼면 발동", L("Hold to slow time and mark enemies, release to fire", "押し続けると時間が遅くなり敵を狙い、離すと発動", "按住时时间变慢并锁定敌人，松开释放") },
        { "즉발형", L("Instant", "即発型", "瞬发型") },
        { "산탄총 · 저격총 · 쌍권총 · 화염 · 유탄은 누르는 즉시 발동", L("Shotgun · Sniper · Twin Pistols · Flame · Grenade fire instantly", "ショットガン・スナイパー・二丁拳銃・火炎・グレネードは押した瞬間に発動", "霰弹枪 · 狙击枪 · 双枪 · 火焰 · 榴弹按下即释放") },
        { "성장", L("Growth", "成長", "成长") },
        { "레벨업", L("Level Up", "レベルアップ", "升级") },
        { "카드를 클릭해 고르고 Space로 확정", L("Click a card and press Space to confirm", "カードをクリックして選び、Spaceで決定", "点击卡牌选择，按Space确认") },
        { "상점 제단", L("Shop Altar", "ショップの祭壇", "商店祭坛") },
        { "적 35마리마다 나타남 · 다가가서 Space로 열기", L("Appears every 35 kills · walk up and press Space", "敵35体ごとに出現・近づいてSpaceで開く", "每击杀35个敌人出现 · 靠近后按Space打开") },
        { "능력치 · 무기 강화 · 스킬 강화", L("Stats · Weapon upgrades · Skill upgrades", "ステータス・武器強化・スキル強化", "属性 · 武器强化 · 技能强化") },
        { "코인", L("Coins", "コイン", "金币") },
        { "적이 떨어뜨림 · 코인 자석 능력으로 끌어올 수 있음", L("Dropped by enemies · pull them in with Coin Magnet", "敵が落とす・コインマグネットで引き寄せられる", "敌人掉落 · 可用金币磁铁吸引") },
        { "특수 능력", L("Special Abilities", "特殊能力", "特殊能力") },
        { "1장 보스를 쓰러뜨리고 문에 들어가면 특수 능력 3개를 고릅니다", L("Beat the chapter 1 boss and enter the gate to pick 3 special abilities", "第1章のボスを倒して門に入ると特殊能力を3つ選びます", "击败第1章首领并进入大门后，选择3项特殊能力") },
        { "무기 · 스킬 · 패시브", L("Weapons · Skills · Passives", "武器・スキル・パッシブ", "武器 · 技能 · 被动") },
        { "무기는 Q로 교체, 스킬은 E · F · Space", L("Swap weapons with Q; skills on E · F · Space", "武器はQで切替、スキルはE・F・Space", "武器用Q切换，技能用E · F · Space") },
        { "특수 강화 (T)", L("Special Upgrade (T)", "特殊強化 (T)", "特殊强化 (T)") },
        { "중간 보스를 잡으면 포인트 · 새 능력을 배우거나 가진 능력을 진화", L("Mid-bosses give points · learn new abilities or evolve yours", "中ボスを倒すとポイント・新しい能力を覚えるか持っている能力を進化", "击败中头目获得点数 · 学习新能力或进化已有能力") },
        { "적과 보스", L("Enemies & Bosses", "敵とボス", "敌人与首领") },
        { "경고 표시", L("Warnings", "警告表示", "警告标记") },
        { "붉은 원 · 선 · 머리 위 ! 가 보이면 그 자리를 피하세요", L("Red circles, lines and a ! above heads mean: get out of the way", "赤い円・線・頭上の！が見えたらその場から離れましょう", "看到红圈、红线或头顶的！就快躲开") },
        { "중간 보스", L("Mid-bosses", "中ボス", "中头目") },
        { "2장부터 단계가 오를 때마다 등장 · 특수 능력 포인트를 줌", L("From chapter 2, one appears each time the phase rises · gives a special point", "第2章から段階が上がるたびに出現・特殊能力ポイントをくれる", "从第2章起每次阶段提升时出现 · 给予特殊能力点数") },
        { "보스", L("Bosses", "ボス", "首领") },
        { "리치 왕 → 지옥의 군주 → 킹 슬라임", L("Lich King → Demon Lord → King Slime", "リッチ王 → 地獄の君主 → キングスライム", "巫妖王 → 地狱领主 → 史莱姆王") },
        { "특수 스킬", L("Special Skills", "特殊スキル", "特殊技能") },
        { "보스는 체력이 절반 아래로 떨어지면 특수 스킬을 씁니다", L("Bosses use a special skill below half HP", "ボスは体力が半分を切ると特殊スキルを使います", "首领生命低于一半时会使用特殊技能") },
        { "목표", L("Goal", "目標", "目标") },
        { "3개의 스테이지", L("Three Stages", "3つのステージ", "三个关卡") },
        { "지하 묘역 → 불타는 지옥 → 초원", L("Catacombs → Burning Hell → Meadow", "地下墓所 → 燃える地獄 → 草原", "地下墓穴 → 燃烧地狱 → 草原") },
        { "문", L("Gates", "門", "大门") },
        { "보스를 쓰러뜨리면 30초 안에 문으로 들어가세요", L("After beating a boss, enter the gate within 30 seconds", "ボスを倒したら30秒以内に門に入りましょう", "击败首领后请在30秒内进入大门") },
        { "행운을 빌어요!", L("Good luck!", "幸運を祈ります！", "祝你好运！") },
        { "모든 보스를 쓰러뜨리면 승리합니다", L("Defeat every boss to win", "全てのボスを倒せば勝利です", "击败所有首领即可获胜") },
    };
}
